/* RESTLESS - pixel art (palette-letter strings, see gfx.h). All drawn for
 * UFO 40: Old Gaunt and his crook, his wisp, the Hollow Host, the treasure
 * of Mossfold, Blink the owlet and Grandmother Ash. The ground, the falls
 * and the Hollow King's face are drawn in rsl_draw.c. */
#include "rsl.h"

Sprite rsl_spr[SPR_COUNT];

/* Old Gaunt, 14 x 22, facing right: antler crown, white beard, wine cloak */
static const char GAUNT0[] =
    "..k.k.kk..kk.."
    "..kakaak.kbbk."
    "...kaaak..kbk."
    "...kttttk..bk."
    "..kttwktk..bk."
    "..ktttttk..bk."
    "..kwwwwwk..bk."
    ".kvkwwwkvk.bk."
    "kvvvkwkvvvhbk."
    "kvvvvkvvvvhbk."
    "kvmvvvvvvvkbk."
    "kvmvvvvvvk.bk."
    "kvmvvaavvk.bk."
    "kvvvvvvvvk.bk."
    ".kvvvvvvk..bk."
    ".kvvvvvvk..bk."
    ".kmvvvvmk..bk."
    ".kmmvvmmk..bk."
    "..kek.kek..bk."
    "..kek.kek..bk."
    ".kbbk.kbbk.bk."
    ".kkkk.kkkk.kk.";
static const char GAUNT1[] =
    "..k.k.kk..kk.."
    "..kakaak.kbbk."
    "...kaaak..kbk."
    "...kttttk..bk."
    "..kttwktk..bk."
    "..ktttttk..bk."
    "..kwwwwwk..bk."
    ".kvkwwwkvk.bk."
    "kvvvkwkvvvhbk."
    "kvvvvkvvvvhbk."
    "kvmvvvvvvvkbk."
    "kvmvvvvvvk.bk."
    "kvmvvaavvk.bk."
    "kvvvvvvvvk.bk."
    ".kvvvvvvk..bk."
    ".kvvvvvvk..bk."
    ".kmvvvvmk..bk."
    ".kmmvvmmk..bk."
    ".kek...kek.bk."
    "kek.....kekbk."
    "kbbk....kbbkk."
    "kkkk....kkkk..";
static const char GAUNT2[] =
    "..k.k.kk..kk.."
    "..kakaak.kbbk."
    "...kaaak..kbk."
    "...kttttk..bk."
    "..kttwktk..bk."
    "..ktttttk..bk."
    "..kwwwwwk..bk."
    ".kvkwwwkvk.bk."
    "kvvvkwkvvvhbk."
    "kvvvvkvvvvhbk."
    "kvmvvvvvvvkbk."
    "kvmvvvvvvk.bk."
    "kvmvvaavvk.bk."
    "kvvvvvvvvk.bk."
    ".kvvvvvvk..bk."
    ".kvvvvvvk..bk."
    ".kmvvvvmk..bk."
    ".kmmvvmmk..bk."
    "...kekek...bk."
    "...kekek...bk."
    "..kbbkbbk..bk."
    "..kkkkkkk..kk.";
static const char GAUNT_JUMP[] =
    "..k.k.kk..kk.."
    "..kakaak.kbbk."
    "...kaaak..kbk."
    "...kttttk..bk."
    "..kttwktk..bk."
    "..ktttttk..bk."
    "..kwwwwwk..bk."
    ".kvkwwwkvk.bk."
    "kvvvkwkvvvhbk."
    "kvvvvkvvvvhbk."
    "kvmvvvvvvvkbk."
    "kvmvvaavvk.bk."
    "kvvvvvvvvk.bk."
    ".kvvvvvvk..bk."
    ".kmvvvvmk..bk."
    ".kmmvvmmk..bk."
    "..kekkek...bk."
    "..keeeek...bk."
    "..kbbbbk...bk."
    "..kkkkkk...kk."
    ".............."
    "..............";
static const char GAUNT_DUCK[] =
    "..k.k.kk......"
    "..kakaak..kk.."
    "...kaaak.kbbk."
    "...kttttk.kbk."
    "..kttwktk..bk."
    "..kwwwwwk..bk."
    ".kvkwwwkvkhbk."
    "kvvvkwkvvvhbk."
    "kvmvvaavvvkbk."
    "kvvvvvvvvk.bk."
    "kmmvvvvmmk.bk."
    "kekkekkekk.bk."
    "kbbkkbbkbbkbk."
    "kkkkkkkkkkkkk.";
static const char GAUNT_DEAD[] =
    "......................"
    "..kk.................."
    ".kbbk..kkkkkkkkk.kkk.."
    "kbbbkkkvvvvvvvvvkwwtkk"
    "kbkkvvvvmvvvvvvvkwttak"
    ".kk.kkkkkkkkkkkkkkkkk."
    ".bbbbbbbbbbbbbbbb....."
    ".kkkkkkkkkkkkkkkk.....";

/* the Low Glow */
static const char WISP[] =
    "..kkkk.."
    ".kIIIIk."
    "kIwwwwIk"
    "kIwkwkIk"
    "kIwwwwIk"
    "kIIwwIIk"
    ".kIIIk.."
    "..kIk...";
static const char PIECE[] =
    ".kkkk."
    "kyyyyk"
    "kywyyk"
    "kyyyak"
    "kyaaak"
    ".kkkk.";
static const char GUARD[] =
    "..kkkkkk.."
    ".kVVVVVVk."
    "kVVppVVVVk"
    "kVwkVVwkVk"
    "kVwkVVwkVk"
    "kVVVVVVVVk"
    "kVVkkkkVVk"
    "kVVVVVVVVk"
    "kVkVVkVVkk"
    ".k.kk.kk..";
static const char FLAME[] =
    "...kk..."
    "..kCk..."
    "..kCCk.."
    ".kCuCk.."
    ".kCuuCk."
    "kCuIuCk."
    "kCuIIuCk"
    "kCuIIuCk"
    ".kCuuCk."
    "..kkkk..";

/* the Hollow Host */
static const char LACKEY0[] =
    "k......k.."
    "kr....rk.."
    ".krrrrk..."
    ".krwrwk..."
    ".krrrrk..."
    ".kryyrk..."
    "..kkkk...."
    ".kmrrmk..."
    "kmrrrrmk.."
    "kmrrrrmkk."
    "kmrrrrmkbk"
    ".kmrrmk.bk"
    ".kmrrmk.bk"
    ".kbbbbk..."
    ".kmrrmk..."
    ".kr..rk..."
    ".kr..rk..."
    ".kr..rk..."
    "kkr..rkk.."
    "kkk..kkk..";
static const char LACKEY1[] =
    "k......k.."
    "kr....rk.."
    ".krrrrk..."
    ".krwrwk..."
    ".krrrrk..."
    ".kryyrk..."
    "..kkkk...."
    ".kmrrmk..."
    "kmrrrrmk.."
    "kmrrrrmkk."
    "kmrrrrmkbk"
    ".kmrrmk.bk"
    ".kmrrmk.bk"
    ".kbbbbk..."
    ".kmrrmk..."
    "..kr.rk..."
    "..kr.rk..."
    ".kr..kr..."
    ".kr...kr.."
    "kkk...kkk.";
static const char BLOOM[] =
    "....kkkkkkkk...."
    "...kPPKKPPKPk..."
    "..kPKKPPKKPPPk.."
    ".kPPKkkkkkKPPk.."
    ".kPKkrrrrrkKPk.."
    "kPPKkrkkkrkKPPk."
    "kPKKkrkkkrkKKPk."
    ".kPKkrrrrrkKPk.."
    ".kPPKkkkkkKPPk.."
    "..kPPKKPPKKPk..."
    "...kkPPkkPPk...."
    "......kzk......."
    "....kkkzk.kk...."
    "...kzzkzkkzzk..."
    "..kzzzzzzzzzzk.."
    "...kkkkzzkkkk..."
    "......kzzk......"
    "......kzzk......"
    ".....kfzzfk....."
    "....kkkkkkkk....";
static const char SPITTER[] =
    "....kkkkkk...."
    "...kooooook..."
    "..kooaoaooak.."
    ".kooookkoooak."
    ".kookkrrkkook."
    "kookrrrrrrkook"
    "kookrkkkkrkook"
    "kookrrrrrrkook"
    "koookkkkkkoook"
    "kooooooooooook"
    ".kooaooooaook."
    ".koooooooooak."
    "..kooooooook.."
    "..kok.kk.kok.."
    "..kek....kek.."
    "..kkk....kkk..";
static const char HIVE[] =
    ".....kkkkk......"
    "....kbbbbbk....."
    "...kaaaaaaak...."
    "..kbbbbbbbbbk..."
    ".kaaaaaaaaaaak.."
    "kbbbbbkkkbbbbbk."
    "kaaaaakkkaaaaak."
    "kbbbbbbbbbbbbbk."
    "kaaaaaaaaaaaaak."
    ".kbbbbbbbbbbbk.."
    "..kaaaaaaaaak..."
    "...kbbbbbbbk...."
    "....kaaaaak....."
    ".....kkkkk......"
    "................"
    "................";
static const char GNAT[] =
    "kk..kk"
    "kIkkIk"
    ".kggk."
    "kgwwgk"
    ".kggk."
    "..kk..";
static const char WISPFOE[] =
    "...kkkk..."
    "..kiiiik.."
    ".kiziiizk."
    "kiiwkiwkik"
    "kiiiiiiiik"
    "kziiiiiizk"
    ".kizzzzik."
    "..kiiiik.."
    "...kzzk..."
    "....kk....";
static const char TUMBLER[] =
    "...kkkkkk..."
    "..kbbbbbbk.."
    ".kbtttttbbk."
    "kbtwkttwkbbk"
    "kbtttttttbbk"
    "kbttkkkttbbk"
    "kbbttttttbbk"
    "kbbbbbbbbbbk"
    ".kbbkbbkbbk."
    ".kbk.kk.kbk."
    "..kk....kk.."
    "............";
static const char TOAD[] =
    "...kkk..kkk..."
    "..kjwjkkjwjk.."
    "..kjkjkkjkjk.."
    ".kjjjjjjjjjjk."
    "kjjjjjjjjjjjjk"
    "kjrrrrrrrrrrjk"
    "kjjjjjjjjjjjjk"
    "kjjiijjjjiijjk"
    "kjjiiiiiiiijjk"
    ".kjjjjjjjjjjk."
    "kjjkk....kkjjk"
    "kkkk......kkkk";
static const char BOULDER[] =
    "......kkkkkk......"
    "....kkggggggkk...."
    "...kggglllggggk..."
    "..kgglllggggsggk.."
    ".kggllggggggsgggk."
    ".kgglggggwkgggsgk."
    "kgggggwkgkkggggsgk"
    "kgggggkkggggggsggk"
    "kggsggggggggggsggk"
    "kgggsggkkkkggssggk"
    "kgggsgggggggggsggk"
    "kggggsgggggggsgggk"
    ".kgggssgggggssggk."
    ".kggggsssssssgggk."
    "..kggggggggggggk.."
    "...kkggggggggkk..."
    ".....kkkkkkkk....."
    "..................";
static const char CRAB[] =
    "kk..........kk"
    "kuk........kuk"
    ".kuk.kwkw.kuk."
    "..kkukkkkukk.."
    ".kuuuuuuuuuuk."
    "kuBuuBuuBuuBuk"
    "kuuuuuuuuuuuuk"
    ".kuuuuuuuuuuk."
    "k.kk.kk.kk.k.k"
    ".k..k..k..k.k.";
static const char CRAB_FLIP[] =
    ".k..k..k..k.k."
    "k.kk.kk.kk.k.k"
    ".kuuuuuuuuuuk."
    "kuuuuuuuuuuuuk"
    "kuBuuBuuBuuBuk"
    ".kuuuuuuuuuuk."
    "..kkukkkkukk.."
    ".kuk.kgkg.kuk."
    "kuk........kuk"
    "kk..........kk";
static const char LEAPER[] =
    "...kkk...."
    "..kyyyk..k"
    ".kywkyykkk"
    "kyyyyyyyak"
    "kyaayyyyak"
    "kyyyyyyyak"
    ".kyyyykkak"
    "..kkkk..kk"
    ".........."
    "..........";
static const char WEEPER_SHUT[] =
    "kkkkkkkkkkkkkkkk"
    "kssssssssssssssk"
    ".kssgggggggsssk."
    ".ksggggggggggsk."
    "..ksgkkkkkkgsk.."
    "..ksggggggggsk.."
    "...ksggggggsk..."
    "...ksggggggsk..."
    "....ksggggsk...."
    "....kssggssk...."
    ".....kssssk....."
    "......kssk......"
    ".......kk......."
    "................";
static const char WEEPER_OPEN[] =
    "kkkkkkkkkkkkkkkk"
    "kssssssssssssssk"
    ".kssgggggggsssk."
    ".ksgkkkkkkkkgsk."
    "..kswwwrrwwwsk.."
    "..kswwrkkrwwsk.."
    "...kswrkkrwsk..."
    "...kswwrrwwsk..."
    "....ksggggsk...."
    "....kssggssk...."
    ".....kssssk....."
    "......kssk......"
    ".......kk......."
    "................";
static const char SHADE[] =
    "...kkkk..."
    "..knnnnk.."
    "..knrrnk.."
    "..knnnnk.."
    "...kkkk..."
    "..knnnnkk."
    ".knnnnnnrk"
    "knnnnnnk.."
    "knknnnnk.."
    "kk.knnk..."
    "...knnk..."
    "...knnk..."
    "..knnnnk.."
    "..knkknk.."
    ".knk..knk."
    ".knk..knk."
    "knk....knk"
    "kkk....kkk";
static const char CROW0[] =
    "kk..................kk"
    "knk................knk"
    "knnk..............knnk"
    "knnnk....kkkk....knnnk"
    ".knnnk..kpppk...knnnk."
    ".knnnnkkpwkpkkkknnnnk."
    "..knnnnnpppppaannnnk.."
    "..knnnnnppppppkknnnk.."
    "...knnnnpppppknnnnk..."
    "....kknnppppknnnkk...."
    "......kkpppppkkk......"
    "........kpppk........."
    "........kpkpk........."
    ".......kak.kak........"
    ".......kk...kk........"
    "......................";
static const char CROW1[] =
    "......................"
    "......................"
    "......................"
    ".........kkkk........."
    "........kpppk........."
    "......kkpwkpkkk......."
    "....kknnpppppaak......"
    "..kknnnnppppppkkk....."
    ".knnnnnnpppppknnnkk..."
    "knnnnnnkppppknnnnnnk.."
    "knnnkkkpppppknnnnnnnk."
    "kkkk...kpppk.kknnnnnk."
    "........kpkpk..kkknnk."
    ".......kak.kak....kkk."
    ".......kk...kk........"
    "......................";
static const char FIREMAW[] =
    "....kkkkkkkkkk...."
    "...kmmmmmmmmmmk..."
    "..kmmrrmmmmrrmmk.."
    ".kmmryrmmmmryrmmk."
    ".kmmrrmmmmmmrrmmk."
    "kmmmmmmmmmmmmmmmmk"
    "kmmkkkkkkkkkkkkmmk"
    "kmmkooooooooookmmk"
    "kmmkoyyyyyyyyokmmk"
    "kmmkooooooooookmmk"
    "kmmkwkwkwkwkwkkmmk"
    "kmmmkkkkkkkkkkmmmk"
    ".kmmmmmmmmmmmmmmk."
    ".kmmkmmmmmmmmkmmk."
    "..kmkkmmmmmmkkmk.."
    "..kmk.kmmmmk.kmk.."
    "..kkk.kkkkkk.kkk.."
    "..................";
static const char SHIELDLING[] =
    "...kkkk....."
    "..kVVVVk...."
    "..kVwVwk...."
    "..kVVVVk...."
    "...kkkk....."
    "..kpppppk..."
    ".kpppppppk.."
    "kpkpppppkpk."
    "kk.kpppk.kk."
    "...kpppk...."
    "...kp.pk...."
    "...kp.pk...."
    "..kpk.kpk..."
    "..kkk.kkk...";
static const char SHIELD[] =
    ".kkkk."
    "kggggk"
    "kgllgk"
    "kglygk"
    "kglygk"
    "kgllgk"
    "kggggk"
    "kgllgk"
    "kglygk"
    "kglygk"
    "kgllgk"
    "kggggk"
    "kggggk"
    ".kggk."
    "..kk.."
    "......";
static const char HULK0[] =
    ".......kkkkkkkkk........"
    "......kssssssssssk......"
    ".....ksssssssssssk......"
    ".....ksswkssswkssk......"
    ".....kssssssssssssk....."
    ".....kssskkkkkssssk....."
    "......kssskwwksssk......"
    "...kkkkksssssssskkkkk..."
    "..ksssssskkkkksssssssk.."
    ".kssssssssssssssssssssk."
    "kssssssssssssssssssssssk"
    "kssskssssssssssssskssssk"
    "kssskssssssssssssskssssk"
    "kssskssssssssssssskssssk"
    "ksssk.kssssssssssk.ksssk"
    "ksssk.kssssssssssk.ksssk"
    ".kkk..kssseeeeesssk.kkk."
    "......ksseeeeeeessk....."
    "......kseeeeeeeeesk....."
    "......ksssssssssssk....."
    "......kssssk.kssssk....."
    "......kssssk.kssssk....."
    "......kssssk.kssssk....."
    "......kssssk.kssssk....."
    "......kssssk.kssssk....."
    "......kssssk.kssssk....."
    ".....ksssssk.ksssssk...."
    ".....ksssssk.ksssssk...."
    ".....kkkkkkk.kkkkkkk...."
    "........................";
static const char HULK1[] =
    ".......kkkkkkkkk........"
    "......kssssssssssk......"
    ".....ksssssssssssk......"
    ".....ksswkssswkssk......"
    ".....kssssssssssssk....."
    ".....kssskkkkkssssk....."
    "......kssskwwksssk......"
    "...kkkkksssssssskkkkk..."
    "..ksssssskkkkksssssssk.."
    ".kssssssssssssssssssssk."
    "kssssssssssssssssssssssk"
    "kssskssssssssssssskssssk"
    "kssskssssssssssssskssssk"
    "kssskssssssssssssskssssk"
    "ksssk.kssssssssssk.ksssk"
    "ksssk.kssssssssssk.ksssk"
    ".kkk..kssseeeeesssk.kkk."
    "......ksseeeeeeessk....."
    "......kseeeeeeeeesk....."
    "......ksssssssssssk....."
    ".....kssssk...kssssk...."
    ".....kssssk...kssssk...."
    "....kssssk.....kssssk..."
    "....kssssk.....kssssk..."
    "....kssssk.....kssssk..."
    "...kssssk.......kssssk.."
    "...kssssk.......kssssk.."
    "..ksssssk.......ksssssk."
    "..kkkkkkk.......kkkkkkk."
    "........................";
static const char CLOCKFIRE[] =
    ".....kk......."
    "....kok..kk..."
    "...koak.kok..."
    "..koyyakoak..."
    ".koyyyyyyak..."
    "koyywkywkyak.."
    "koyyyyyyyyak.."
    "koyykkkkyyak.."
    ".koyyyyyyak..."
    "..koyyyyak...."
    "...koaaak....."
    "....kook......"
    ".....kk......."
    "..............";
static const char CLOUD[] =
    "........kkkkk............."
    "......kklllllkk...kkkk...."
    "....kkllllllllllkklllllk.."
    "...klllllllllllllllllllllk"
    "..kllllgllllllllllllllllk."
    ".kllllgwkglllllgwkglllllk."
    "klllllggggllllggggllllllk."
    "kllllllllllkkkkllllllllk.."
    "kllgllllllllllllllllgllk.."
    ".kggglllllllllllllllgggk.."
    "..kkggggggggggggggggkk...."
    "....kkkkkkkkkkkkkkkk......"
    "......ky....ky....ky......"
    ".......k.....k.....k......";

/* the bosses */
static const char KEEPER[] =
    "........kkkkkkkkkkkkk........."
    ".......krrrrrrrrrrrrrk........"
    "......krrkkrrrrrrkkrrrk......."
    "......krkwykrrrrkywkrrk......."
    "......krrkkrrrrrrkkrrrk......."
    "......krrrrrrkkrrrrrrrk......."
    "......krrkkkkkkkkkkkrrk......."
    "......krrkwkwkwkwkwkrrk......."
    ".......krrkkkkkkkkkrrk........"
    "....kkkkrrrrrrrrrrrrrkkkkk...."
    "...krrrrrrrrrrrrrrrrrrrrrrk..."
    "..krrrrrrrrrrrrrrrrrrrrrrrrk.."
    ".krrrkrrrrrrrrrrrrrrrrrkrrrrk."
    ".krrrkrrrrrrrrrrrrrrrrrkrrrrk."
    "krrrrkrrrrrrrrrrrrrrrrrkrrrrrk"
    "krrrk.krrrrrrrrrrrrrrrk.krrrrk"
    "krrrk.krrrrrrrrrrrrrrrk.krrrrk"
    "kwwwk.krrrrbbbbbbbrrrrk.kwwwwk"
    "kwkwk.krrrbbbbbbbbbrrrk.kwkwkk"
    ".kkk..krrrbbbbbbbbbrrrk..kkk.."
    "......krrrrrrrrrrrrrrrk......."
    "......krrrrrrrrrrrrrrrk......."
    "......krrrrrkkkkkrrrrrk......."
    "......krrrrrk...krrrrrk......."
    "......krrrrrk...krrrrrk......."
    "......krrrrrk...krrrrrk......."
    "......krrrrrk...krrrrrk......."
    "......krrrrrk...krrrrrk......."
    ".....krrrrrrk...krrrrrrk......"
    ".....krrrrrrk...krrrrrrk......"
    "....kwkwkwkwk...kwkwkwkwk....."
    "....kkkkkkkkk...kkkkkkkkk....."
    ".............................."
    "..............................";
static const char RATTLE[] =
    "........kkkkkkkkkk........"
    ".......kllllllllllk......."
    "......klllkkllkklllk......"
    "......kllkrkllkrklllk....."
    "......klllkkllkkllllk....."
    "......kllllllllllllk......"
    ".......klkwkwkwkwlk......."
    "........kllllllllk........"
    "....kkkkkkkkkkkkkkkkk....."
    "...kgllllllllllllllllgk..."
    "..kglkkkkklllkkkkkllglk..."
    ".kgllllllllllllllllllglk.."
    "kglk.kgkkkkkkkkkkgk.klglk."
    "kglk.kgllllllllllgk.klglk."
    "kglk.kgkkkkkkkkkkgk.klglk."
    "kllk.kgllllllllllgk.kllk.."
    ".kk..kgkkkkkkkkkkgk..kk..."
    ".....kglllllllllllgk......"
    "......kglllllllllgk......."
    ".......kkgllllgkk........."
    "........kglk.kglk........."
    "........kglk.kglk........."
    "........kglk.kglk........."
    "........kglk.kglk........."
    ".......kgllk.kgllk........"
    ".......kgllk.kgllk........"
    ".......kkkkk.kkkkk........"
    "..........................";
static const char HEAD[] =
    "....kkkkkkkk......"
    "..kkjjjjjjjjkk...."
    ".kjjjjjjjjjjjjk..."
    "kjjykkjjjjjjjjjk.."
    "kjjyrkjjjjjjjjjjk."
    "kjjkkjjjjjjjjjjjjk"
    "kjjjjjjjjjjjkkkkkk"
    "kjjjjjjjjjjkwkwkwk"
    "kjjjjjjjjjjkkkkkk."
    "kjjiijjjjjjkwkwkwk"
    ".kjjiiijjjjjkkkkkk"
    "..kjjjjjjjjjjjjjk."
    "...kkjjjjjjjjjkk.."
    ".....kkkkkkkkkk..."
    "......kjjjjjk....."
    "......kjjjjjk.....";
static const char GUST[] =
    "kk........................kk"
    "kVk......................kVk"
    "kVVk.......kkkkkk.......kVVk"
    "kVVVk.....kVVVVVVk.....kVVVk"
    ".kVVVk...kVyVVVyVVk...kVVVk."
    ".kVVVVk..kVVVVVVVVk..kVVVVk."
    "..kVVVVkkkVVkkkkVVkkkVVVVk.."
    "..kVVVVVVkVkwkwkVkVVVVVVVk.."
    "...kVVVVVVkkkkkkkVVVVVVVk..."
    "....kkVVVVVVVVVVVVVVVVkk...."
    "......kkVVVVVVVVVVVVkk......"
    "........kVVVVVVVVVVk........"
    "........kVpVVVVVVpVk........"
    ".........kVVVVVVVVk........."
    ".........kVVkkkkVVk........."
    "........kak......kak........"
    "........kak......kak........"
    ".......kaak......kaak......."
    ".......kkk........kkk......."
    "............................";
static const char GASH[] =
    "......kkkkkk......l."
    ".....koooooook...klk"
    "....koookkookook.klk"
    "....kooyrkooyrok.klk"
    "....koookkoooook.kbk"
    ".....kokwkwkwok..kbk"
    "......kooooook...kbk"
    "...kkkkkooooookkkkbk"
    "..koooooooooooooohbk"
    ".koooooooooooooooobk"
    "kooookooooooooookkbk"
    "kooookooooooooook.bk"
    "kooookooooooooook.bk"
    "kkkkkkoooooooook..bk"
    ".....koooooooook..bk"
    ".....kooaaaaaook..bk"
    ".....koooooooook..bk"
    ".....kooooooooook.bk"
    ".....koook..koook.bk"
    ".....koook..koook.bk"
    ".....koook..koook.bk"
    ".....koook..koook.bk"
    ".....koook..koook.bk"
    ".....koook..koook.bk"
    ".....koook..koook.bk"
    "....kooook..kooook.k"
    "....kooook..kooook.."
    "....kkkkkk..kkkkkk.."
    "...................."
    "....................";
static const char RAMMER[] =
    "kk......................kk"
    "kwk....................kwk"
    ".kwk..kkkkkkkkkkkkkk..kwk."
    "..kwkkbbbbbbbbbbbbbbkkwk.."
    "...kwbbbbbbbbbbbbbbbbwk..."
    "...kbbbkkbbbbbbbbkkbbbk..."
    "...kbbkrykbbbbbbkyrkbbk..."
    "...kbbbkkbbbbbbbbkkbbbk..."
    "...kbbbbbbbbbbbbbbbbbbk..."
    "..kbbbbbbbkkkkkkbbbbbbbk.."
    ".kbbbbbbbkwkwkwkkbbbbbbbk."
    "kbbbbbbbbbkkkkkkbbbbbbbbbk"
    "kbbbbbbbbbbbbbbbbbbbbbbbbk"
    "kbbebbbbbbbbbbbbbbbbbbebbk"
    "kbbebbbbbbbbbbbbbbbbbbebbk"
    "kbbbebbbbbbbbbbbbbbbbebbbk"
    ".kbbbbbbbbbbbbbbbbbbbbbbk."
    "..kbbbbbbbbbbbbbbbbbbbbk.."
    "..kbbbk.kbbbbbbbbk.kbbbk.."
    "..kbbbk.kbbk..kbbk.kbbbk.."
    "..kbbbk.kbbk..kbbk.kbbbk.."
    ".kbbbbk.kbbk..kbbk.kbbbbk."
    ".kwkwkk.kwkk..kwkk.kwkwkk."
    ".kkkkk..kkkk..kkkk..kkkkk.";
static const char SKULL[] =
    "...kkkkkkkk..."
    "..kllllllllk.."
    ".klllllllllllk"
    "klllllllllllk."
    "kllkkllllkkllk"
    "kllkrkllkrkllk"
    "kllkkllllkkllk"
    "klllllkklllllk"
    ".klllkkkklllk."
    "..klkwkwkwlk.."
    "..kllllllllk.."
    "...kkkkkkkk..."
    "....kk..kk...."
    "...kk....kk...";

/* torches and treasure */
static const char TORCH0[] =
    "....yy...."
    "...yooy..."
    "..yoaaoy.."
    "..oayyao.."
    "...oyyo..."
    ".kkkkkkkk."
    ".kbbbbbbk."
    "..kbbbbk.."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "..kbbbbk.."
    ".kkkkkkkk.";
static const char TORCH1[] =
    "...y......"
    "...oy.y..."
    "..yoayoy.."
    "..oayyao.."
    "...oyyo..."
    ".kkkkkkkk."
    ".kbbbbbbk."
    "..kbbbbk.."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "..kbbbbk.."
    ".kkkkkkkk.";
static const char TORCH_OUT[] =
    ".........."
    ".........."
    "....g....."
    "...g.g...."
    "....s....."
    ".kkkkkkkk."
    ".kbsssskk."
    "..kbbbbk.."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "...kbbk..."
    "..kbbbbk.."
    ".kkkkkkkk.";
static const char POT[] =
    "..kkkk.."
    ".kbttbk."
    "..kttk.."
    ".kbbbbk."
    "kbtbbbbk"
    "kbbbbbbk"
    ".kbbbbk."
    "..kkkk..";
static const char URN[] =
    "..kkkk.."
    ".kooook."
    "..kaak.."
    ".kooook."
    "koaooook"
    "kooooaok"
    ".kooook."
    "..kkkk..";
static const char JAR[] =
    ".kkkkkk."
    "kyyyyyyk"
    ".kayyak."
    "kyywyyyk"
    "kywyyyak"
    "kyyyyyak"
    "kayyyaak"
    ".kkkkkk.";
static const char COIN[] =
    "..kkk..."
    ".kyyyk.."
    "kyywyak."
    "kywyyak."
    "kyyyaak."
    ".kaaak.."
    "..kkk..."
    "........";
static const char IDOL[] =
    "..k.k.k."
    ".kykykyk"
    ".kykykyk"
    "kkyyyyyk"
    "kyyyyyyk"
    "kywyyyak"
    ".kyyyak."
    "..kkkk..";
static const char BEETLE[] =
    ".k....k."
    "..kkkk.."
    ".kyyyyk."
    "kywykyak"
    "kyyykyak"
    "kyyykyak"
    ".kyakak."
    "k.kkkk.k";
static const char CLOCK[] =
    "kkkkkkkk"
    ".kccccck"
    "..kyyyk."
    "...kyk.."
    "...kck.."
    "..kcyck."
    ".kyyyyyk"
    "kkkkkkkk";
static const char LILY[] =
    "...kk..."
    "..kKKk.."
    ".kKwwKk."
    "kKKwwKKk"
    "kwKKKKwk"
    ".kKKKKk."
    "kzzkkzzk"
    ".kzzzzk.";
static const char CHARM[] =
    "..kkkk.."
    ".kggggk."
    "kgkllkgk"
    "kglkklgk"
    "kgllllgk"
    ".kgllgk."
    "..kggk.."
    "...kk...";
static const char EGG[] =
    "..kkk..."
    ".kiiik.."
    "kiziiik."
    "kiiiizk."
    "kizziik."
    "kiiiiik."
    ".kiiik.."
    "..kkk...";
static const char BELL[] =
    "...kk..."
    "..kyyk.."
    ".kyyyyk."
    ".kywyyk."
    "kyywyyak"
    "kyyyyyak"
    "kkkkkkkk"
    "...kk...";
static const char ASH[] =
    ".....kkkk....."
    "....kllllk...."
    "...kllllllk..."
    "...klkllklk..."
    "...kllllllk..."
    "....kllllk...."
    "...kkIIIIkk..."
    "..kIIIIIIIIk.."
    ".kIIkIIIIkIIk."
    "kIIk.kIIk.kIIk"
    "kIk..kIIk..kIk"
    "kk...kIIk...kk"
    "....kIIIIk...."
    "....kIIIIk...."
    "...kIIIIIIk..."
    "...kIIIIIIk..."
    "..kIIIIIIIIk.."
    "..kIIIIIIIIk.."
    ".kIIIIIIIIIIk."
    ".kkkkkkkkkkkk.";
static const char ICON_SEEKER[] =
    "..kkkkk..."
    ".kppppppk."
    "kppkkkkppk"
    "kpk....kpk"
    "kpk.VV.kpk"
    "kpk.VV.kpk"
    "kpk....kpk"
    "kppkkkkppk"
    ".kppppppk."
    "..kkkkk...";
static const char ICON_EMBER[] =
    "...kk....."
    "..kok....."
    "..kook.k.."
    ".kooakkok."
    ".koyaoook."
    "kooyyaaok."
    "koyyyyaook"
    "koyyyyyaok"
    ".koyyyyok."
    "..kkkkkk..";
static const char ICON_SCATTER[] =
    ".........."
    ".kk....kk."
    "kIIk..kIIk"
    "kIIk..kIIk"
    ".kk.kk.kk."
    "...kIIk..."
    "...kIIk..."
    ".kk.kk.kk."
    "kIIk..kIIk"
    ".kk....kk.";
static const char ICON_STAFF[] =
    ".......kk."
    "......kbbk"
    ".....kbk.k"
    "....kbk..."
    "...kbk...."
    "..kbk....."
    ".kbk......"
    "kbk......."
    "kk........"
    "..........";
static const char OWLET0[] =
    "k........k"
    "kik....kik"
    ".kiikkiik."
    ".kiwkiwik."
    ".kikkikik."
    ".kiiaaiik."
    "kiiiiiiiik"
    "kzkiiiikzk"
    "k.kkkkkk.k"
    "...k..k...";
static const char OWLET1[] =
    ".........."
    ".k......k."
    "kik.kk.kik"
    "kziiwkiwik"
    "kziikkikik"
    ".kiiaaiik."
    "..kiiiik.."
    "..kziizk.."
    "...kkkk..."
    "...k..k...";
static const char FLAG[] =
    "kkkkkk.."
    "kwwwwwk."
    "kwwwwwwk"
    "kwwwwwk."
    "kkkkkk.."
    "k......."
    "k......."
    "k.......";
static const char SKULL_ICON[] =
    ".kkkkk."
    "kwwwwwk"
    "kwkwkwk"
    "kwwwwwk"
    ".kwkwk."
    "..kkk..";

typedef struct { int id, w, h; const char *px; } ArtDef;

static const ArtDef ART[] = {
    {SPR_GAUNT0, 14, 22, GAUNT0}, {SPR_GAUNT1, 14, 22, GAUNT1}, {SPR_GAUNT2, 14, 22, GAUNT2},
    {SPR_GAUNT_JUMP, 14, 22, GAUNT_JUMP}, {SPR_GAUNT_DUCK, 14, 14, GAUNT_DUCK}, {SPR_GAUNT_DEAD, 22, 8, GAUNT_DEAD},
    {SPR_WISP, 8, 8, WISP}, {SPR_PIECE, 6, 6, PIECE}, {SPR_GUARD, 10, 10, GUARD}, {SPR_FLAME, 8, 10, FLAME},
    {SPR_LACKEY0, 10, 20, LACKEY0}, {SPR_LACKEY1, 10, 20, LACKEY1}, {SPR_BLOOM, 16, 20, BLOOM},
    {SPR_SPITTER, 14, 16, SPITTER}, {SPR_HIVE, 16, 16, HIVE}, {SPR_GNAT, 6, 6, GNAT}, {SPR_WISPFOE, 10, 10, WISPFOE},
    {SPR_TUMBLER, 12, 12, TUMBLER}, {SPR_TOAD, 14, 12, TOAD}, {SPR_BOULDER, 18, 18, BOULDER},
    {SPR_CRAB, 14, 10, CRAB}, {SPR_CRAB_FLIP, 14, 10, CRAB_FLIP}, {SPR_LEAPER, 10, 10, LEAPER},
    {SPR_WEEPER_SHUT, 16, 14, WEEPER_SHUT}, {SPR_WEEPER_OPEN, 16, 14, WEEPER_OPEN}, {SPR_SHADE, 10, 18, SHADE},
    {SPR_CROW0, 22, 16, CROW0}, {SPR_CROW1, 22, 16, CROW1}, {SPR_FIREMAW, 18, 18, FIREMAW},
    {SPR_SHIELDLING, 12, 14, SHIELDLING}, {SPR_SHIELD, 6, 16, SHIELD}, {SPR_HULK0, 24, 30, HULK0},
    {SPR_HULK1, 24, 30, HULK1}, {SPR_CLOCKFIRE, 14, 14, CLOCKFIRE}, {SPR_CLOUD, 26, 14, CLOUD},
    {SPR_KEEPER, 30, 34, KEEPER}, {SPR_RATTLE, 26, 28, RATTLE}, {SPR_HEAD, 18, 16, HEAD}, {SPR_GUST, 28, 20, GUST},
    {SPR_GASH, 20, 30, GASH}, {SPR_RAMMER, 26, 24, RAMMER}, {SPR_SKULL, 14, 14, SKULL},
    {SPR_TORCH0, 10, 16, TORCH0}, {SPR_TORCH1, 10, 16, TORCH1}, {SPR_TORCH_OUT, 10, 16, TORCH_OUT},
    {SPR_POT, 8, 8, POT}, {SPR_URN, 8, 8, URN}, {SPR_JAR, 8, 8, JAR}, {SPR_COIN, 8, 8, COIN}, {SPR_IDOL, 8, 8, IDOL},
    {SPR_BEETLE, 8, 8, BEETLE}, {SPR_CLOCK, 8, 8, CLOCK}, {SPR_LILY, 8, 8, LILY}, {SPR_CHARM, 8, 8, CHARM},
    {SPR_EGG, 8, 8, EGG}, {SPR_BELL, 8, 8, BELL}, {SPR_ASH, 14, 20, ASH}, {SPR_WP_SEEKER, 10, 10, ICON_SEEKER},
    {SPR_WP_EMBER, 10, 10, ICON_EMBER}, {SPR_WP_SCATTER, 10, 10, ICON_SCATTER}, {SPR_WP_STAFF, 10, 10, ICON_STAFF},
    {SPR_OWLET0, 10, 10, OWLET0}, {SPR_OWLET1, 10, 10, OWLET1}, {SPR_FLAG, 8, 8, FLAG},
    {SPR_SKULL_ICON, 7, 6, SKULL_ICON},
};

int rsl_art_check(void);
int rsl_art_check(void) {
    /* tests: every sprite string has exactly w * h pixels */
    int bad = 0;
    for (int i = 0; i < ARRAY_LEN(ART); i++)
        if ((int)strlen(ART[i].px) != ART[i].w * ART[i].h) bad++;
    return bad;
}

void rsl_art_load(void) {
    static bool done;
    if (done) return;
    done = true;
    for (int i = 0; i < ARRAY_LEN(ART); i++)
        if ((int)strlen(ART[i].px) == ART[i].w * ART[i].h) spr_make(&rsl_spr[ART[i].id], ART[i].w, ART[i].h, ART[i].px);
}
