/* UNDERDELVE - all pixel art, authored as palette-letter strings.
 * Palette letters (see gfx.h):
 *   k ink  n night  d dusk  s slate  g grey  l light  w white
 *   m maroon v wine r red o orange a amber y yellow c cream
 *   b brown t tan e earth h hide   q teal f forest j jade z leaf i lime
 *   N navy B blue u sky C cyan I ice   p purple V violet P magenta K pink
 *   '.' = transparent
 * Tiles use the neutral rock ramp (k n d s g) and are recoloured per zone. */
#include "underdelve.h"

Sprite ud_spr[S_COUNT];

typedef struct { int id, w, h; const char *px; } ArtDef;

/* ------------------------------------------------------------ Mo */
static const char MO_IDLE[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    "..kddddddddddkk."
    ".ksddddddkwddk.."
    ".ksddddddkkdkKk."
    ".kdddddddddkKKPk"
    ".knddddddddkkkk."
    ".kndddlllldddk.."
    "..knddllllddKKk."
    "..kkndddddddKPk."
    "...kKKkkkkkKKk.."
    "...kkkk...kkkk..";
static const char MO_BLINK[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    "..kddddddddddkk."
    ".ksddddddddddk.."
    ".ksddddddkkdkKk."
    ".kdddddddddkKKPk"
    ".knddddddddkkkk."
    ".kndddlllldddk.."
    "..knddllllddKKk."
    "..kkndddddddKPk."
    "...kKKkkkkkKKk.."
    "...kkkk...kkkk..";
static const char MO_WALK1[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    "..kddddddddddkk."
    ".ksddddddkwddk.."
    ".ksddddddkkdkKk."
    ".kdddddddddkKKPk"
    ".knddddddddkkkk."
    ".kndddlllldddk.."
    "..knddllllddKKk."
    "..kkndddddddKPk."
    "..kKKkkk.kkKKk.."
    "..kkkk....kkk...";
static const char MO_WALK2[] =
    "................"
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    "..kddddddddddkk."
    ".ksddddddkwddk.."
    ".ksddddddkkdkKk."
    ".kdddddddddkKKPk"
    ".knddddddddkkkk."
    ".kndddllllddKKk."
    "..kndddddddkKPk."
    "....kKKkkKKkkk.."
    "....kkkkkkkk....";
static const char MO_JUMP[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    ".kKddddddddddkk."
    "kKPddddddkwddk.."
    ".kkddddddkkdkKk."
    ".kdddddddddkKKPk"
    ".knddddddddkkkk."
    ".kndddllllddk..."
    "..knddlllldk...."
    "...kkndddkkk...."
    "...kKKkkKKk....."
    "....kk..kk......";
static const char MO_FALL[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    "..kddddddddddkkk"
    ".ksddddddkwddkKk"
    ".ksddddddkkdkKPk"
    ".kdddddddddkkkk."
    ".knddddddddk...."
    ".kndddllllddk..."
    "..knddlllldddk.."
    "..kkndddddddkk.."
    "..kKKk....kKKk.."
    "..kkkk....kkkk..";
static const char MO_CLIMB[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyyyyyyyyk..."
    "...kyyyyyyyyk.kk"
    "..kkaaaaaaaakkKk"
    ".kddddddddddddPk"
    ".kdsddddddddsdkk"
    "kKkdddddddddddk."
    "kPkddddddddddk.."
    ".kkdddddddddddk."
    "..kndddddddddnk."
    "..knddddddddndk."
    "...knnddddnnkk.."
    "...kKKk..kKKk..."
    "...kkkk..kkkk...";
static const char MO_SWING1[] =
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    ".kkaaaaaaaaaakck"
    "kKkddddddddddkk."
    "kPsddddddkwddk.."
    ".ksddddddkkdkKk."
    ".kdddddddddkKKPk"
    ".knddddddddkkkk."
    ".kndddlllldddk.."
    "..knddllllddk..."
    "..kkndddddddk..."
    "...kKKkkkkkKKk.."
    "...kkkk...kkkk..";
static const char MO_SWING2[] =
    "................"
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyyk..."
    "...kyyyyyyyyykk."
    "..kaaaaaaaaaakck"
    "..kddddddddddkk."
    ".ksddddddkwddk.."
    ".ksddddddkkdkKk."
    ".kdddddddddkKKkk"
    ".knddddddddkKKPk"
    ".kndddllllddkkk."
    "..kndddddddddk.."
    "..kKKkkkkkkKKk.."
    "..kkkk....kkkk..";
static const char MO_HURT[] =
    "................"
    "................"
    ".....kkkkkk....."
    "....kyyyyyyk...."
    "...kyccyyyyykk.."
    "..kaaaaaaaaaakck"
    ".kKdddddddddkkk."
    "kKPddddddkdkdk.."
    ".kkdddddddkddKk."
    ".kddddddddkdkKPk"
    ".knddddddddkkkk."
    ".kndddllllddKKk."
    "..knddllllddKPk."
    "..kkndddddddkk.."
    "..kKKk....kKKk.."
    "..kkkk....kkkk..";

static const char PICK_UP[] =
    "..kkkkkkkkkk...."
    ".kllllllllggk..."
    "..kkkkeekkkk...."
    "......ktk......."
    "......kek......."
    "......ktk......."
    "......kek......."
    "......kkk.......";
static const char PICK_FWD[] =
    "...........kk..."
    "..........kglk.."
    "..........kglk.."
    "kkkkkkkkkkkglk.."
    "ketetetetekglk.."
    "kkkkkkkkkkkglk.."
    "..........kglk.."
    "..........kgk..."
    "...........k....";
static const char ROD_FWD[] =
    "..........kkk..."
    ".........kCIck.."
    "kkkkkkkkkkIwIk.."
    "kpVpVpVpVkCIuk.."
    "kkkkkkkkkkkuk..."
    "...........k....";
static const char HUNGRY_FWD[] =
    "...........kk..."
    "..........kPrk.."
    "..........kwkk.."
    "kkkkkkkkkkkrPk.."
    "kvmvmvmvmkkPrk.."
    "kkkkkkkkkkkrPk.."
    "..........kPrk.."
    "..........kPk..."
    "...........k....";

/* ------------------------------------------------------------ tiles */
static const char T_ROCK[] =
    "dssssddnddsssdnd"
    "ssgssddnddsgsdnd"
    "sssddnnddssssdnd"
    "sdddnnddddsddnnd"
    "ddnnnddssdddnddd"
    "nnnddssgssddnddd"
    "ddddsgssssddnnnn"
    "dsssssssddnnnddd"
    "ssgsssddnnddsssd"
    "sssddnnnddssgssd"
    "sddnnnddsssssddn"
    "dnnddddsssssddnd"
    "nndssddssddnnddd"
    "ddsgsdddddnnddsd"
    "dssssddnnnddssgd"
    "ddddnnnddddsssdd";
static const char T_ROCK2[] =
    "dddnnddsssssdddd"
    "ssddnddsgssssddn"
    "sgsddnddsssddnnd"
    "sssdddnndddddndd"
    "dssddddnnnddnddd"
    "ddnnnddsssnnnsss"
    "nnddddssgsdddsgs"
    "dddsssssssdddsss"
    "ddsgsssddddnnddd"
    "ndsssddnnnnddssd"
    "nndddnnddddssgsd"
    "ddnnnddssddsssdd"
    "dsddddsgssdddnnd"
    "ssssdssssddnnddd"
    "sgssddddnnnddsss"
    "dddddnnnddddssgs";
static const char T_BRICK[] =
    "gsssssskgsssssss"
    "sdddddnksddddddd"
    "sdddddnksddddddd"
    "nnnnnnnknnnnnnnn"
    "kkkkkkkkkkkkkkkk"
    "ssskgsssssssskgs"
    "dddksddddddddksd"
    "dddksddddddddksd"
    "nnnknnnnnnnnnknn"
    "kkkkkkkkkkkkkkkk"
    "gsssssskgsssssss"
    "sdddddnksddddddd"
    "sdddddnksddddddd"
    "nnnnnnnknnnnnnnn"
    "kkkkkkkkkkkkkkkk"
    "ssskgsssssssskgs";
static const char T_PLANK[] =
    "kkkkkkkkkkkkkkkk"
    "heeeeeeheeeeeehe"
    "etteeetteetteett"
    "tttttbtttttbtttt"
    "bbbbbbbbbbbbbbbb"
    "kkkkkkkkkkkkkkkk"
    ".kbk........kbk."
    ".kbk........kbk."
    "..k..........k.."
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................";
static const char T_LADDER[] =
    "..kek......kek.."
    "..ktk......ktk.."
    "..ktkkkkkkkktk.."
    "..kteeeeeeeetk.."
    "..ktbbbbbbbbtk.."
    "..ktkkkkkkkktk.."
    "..kek......kek.."
    "..ktk......ktk.."
    "..kek......kek.."
    "..ktk......ktk.."
    "..ktkkkkkkkktk.."
    "..kteeeeeeeetk.."
    "..ktbbbbbbbbtk.."
    "..ktkkkkkkkktk.."
    "..kek......kek.."
    "..ktk......ktk..";
static const char T_ROPE[] =
    "......kek......."
    "......ket......."
    ".......kek......"
    "......kte......."
    "......ket......."
    ".......kek......"
    "......kte......."
    "......ket......."
    ".......kek......"
    "......kte......."
    "......ket......."
    ".......kek......"
    "......kte......."
    "......ket......."
    ".......kek......"
    "......kte.......";
static const char T_SPIKES[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "..w...w...w...w."
    "..l...l...l...l."
    ".klk.klk.klk.klk"
    ".kgk.kgk.kgk.kgk"
    "klgskklgskklgskk"
    "kggskkggskkggskk"
    "kssskksssskssskk"
    "kkkkkkkkkkkkkkkk"
    "ndsdnndsdnndsdnn"
    "nnnnnnnnnnnnnnnn";
static const char T_CRYSTAL[] =
    "kkk.....kk....kk"
    "kIck...kIck..kIk"
    "kICuk.kICCuk.kCk"
    "kICuukIICCuukICk"
    ".kCuukICCCuukCuk"
    ".kCCukICCuuukCuk"
    "kkCuukICCCuukuuk"
    "kIkCukICCuuuBkuk"
    "kICkukkCCuuBkIuk"
    "kICCkkuCuuuBkCuk"
    "kCCuukuuuuBkICuk"
    "kCCuuBkuuuBkCCuk"
    "kCuuuBkuuBBkCuuk"
    "kuuuBBkuBBBkuuBk"
    "kuuBBBkBBBBkuBBk"
    "kkkkkkkkkkkkkkkk";
static const char T_DRIP[] =
    "dddddddddddddddd"
    "dsddnddddsddnddd"
    "dddddddddddddddd"
    "kdddddddddddddk."
    ".kddddddddddddk."
    ".kddsdddddsdddk."
    "..kddddddddddk.."
    "..kdddddddddk..."
    "...kddddddddk..."
    "...kdddsdddk...."
    "....kddddddk...."
    ".....kdddk......"
    ".....kddk......."
    "......kdk......."
    "......kCk......."
    ".......k........";
static const char T_OOZE1[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "......iii......."
    "..iiiizzzii...i."
    "iizzzzzzzzziiiz."
    "zzzzjzzzzzzzzzzz"
    "zjjjjjjzzjjjjjjz"
    "jjjjjjjjjjjjjjjj"
    "jjfjjjjjjjjfjjjj"
    "fjjjjjfjjjjjjjjf"
    "jjjjjjjjjfjjjjjj"
    "jfjjjjjjjjjjjfjj"
    "jjjjjfjjjjjjjjjj";
static const char T_OOZE2[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "..i..........ii."
    "iizii....iiiizzi"
    "zzzzziiiizzzzzzz"
    "zzzzzzzzzzzjzzzz"
    "zjjjzzzjjjjjjzjj"
    "jjjjjjjjjjjjjjjj"
    "jjjjfjjjjjjfjjjj"
    "jfjjjjjjfjjjjjjf"
    "jjjjjjjjjjjjjjjj"
    "jjjfjjjjjfjjjjjj"
    "jjjjjjjfjjjjjjfj";
static const char T_OOZEBODY[] =
    "jjjjjjjjjjjjjjjj"
    "jjfjjjjjjjjfjjjj"
    "fjjjjjfjjjjjjjjf"
    "jjjjjjjjjfjjjjjj"
    "jfjjjjjjjjjjjfjj"
    "jjjjjfjjjjjjjjjj"
    "jjjjjjjjjjjjjjjj"
    "jjjfjjjjjfjjjjjj"
    "jjjjjjjjjjjjjjfj"
    "fjjjjjjfjjjjjjjj"
    "jjjjjjjjjjjjjjjj"
    "jjfjjjjjjjjfjjjj"
    "jjjjjjjjjjjjjjjj"
    "jjjjjfjjjjjjjjjf"
    "jfjjjjjjjjfjjjjj"
    "jjjjjjjjjjjjjjjj";
static const char T_GATE[] =
    "kkkkkkkkkkkkkkkk"
    "kgsgkgsgkgsgkgsk"
    "kgskkgskkgskkgsk"
    "kgskkgskkgskkgsk"
    "kkkkkkkkkkkkkkkk"
    "kgskkgskkgskkgsk"
    "kgskkayyakskkgsk"
    "kgskkyaayksskgsk"
    "kgskkyakyksskgsk"
    "kgskkayyakskkgsk"
    "kkkkkkkkkkkkkkkk"
    "kgskkgskkgskkgsk"
    "kgskkgskkgskkgsk"
    "kgskkgskkgskkgsk"
    "kssskssskssskssk"
    "kkkkkkkkkkkkkkkk";
static const char T_SEAL[] =
    "kkkkkkkkkkkkkkkk"
    "kvrrvkkvrrvkkvrk"
    "krmmrkkrmmrkkrmk"
    "kvrrvkkvrrvkkvrk"
    "kkkkkkkkkkkkkkkk"
    "kkvrrvkkvrrvkkvk"
    "kkrmmrkkrmmrkkrk"
    "kkvrrvkkvrrvkkvk"
    "kkkkkkkkkkkkkkkk"
    "kvrrvkkvrrvkkvrk"
    "krmmrkkrmmrkkrmk"
    "kvrrvkkvrrvkkvrk"
    "kkkkkkkkkkkkkkkk"
    "kkvrrvkkvrrvkkvk"
    "kkrmmrkkrmmrkkrk"
    "kkkkkkkkkkkkkkkk";
static const char T_BEAM[] =
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbteek....."
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbbtek....."
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......"
    ".....kbtek......";
static const char T_TORCH1[] =
    "................"
    "................"
    "......y........."
    ".....yay........"
    ".....ayo..y....."
    "....yacoy.a....."
    "....aoccaoo....."
    ".....acca......."
    ".....kbbk......."
    "....ktbbtk......"
    ".....kbbk......."
    ".....ktbk......."
    ".....kbbk......."
    "......kk........"
    "................"
    "................";
static const char T_TORCH2[] =
    "................"
    "................"
    ".......y........"
    "..y...yay......."
    "..o..yoa........"
    ".....oacoy......"
    "....ooccao......"
    ".....acca......."
    ".....kbbk......."
    "....ktbbtk......"
    ".....kbbk......."
    ".....ktbk......."
    ".....kbbk......."
    "......kk........"
    "................"
    "................";
static const char T_MUSH[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "...kkkk........."
    "..kCIICk....kk.."
    ".kCIICCuk..kCIk."
    ".kuuuuuuk.kCCuuk"
    "..kkhhkk..kkhkk."
    "....hh.....kh..."
    "....hh.....kh..."
    "...khhk...khhk..";
static const char T_CRYS_DECOR[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "..........k....."
    "......k..kIk...."
    ".....kIk.kCuk..."
    ".....kICkkCuk..."
    "..k..kICukCuk..."
    ".kIk.kICukCuuk.."
    ".kCukkCCukuuBk.."
    "kkCuukCuukuBBk.."
    "kkkkkkkkkkkkkkk.";
static const char T_BGROCK[] =
    "................"
    "................"
    "....nn.........."
    "...nnnn........."
    "....nn.........."
    "................"
    "..........n....."
    ".........nnn...."
    "................"
    "................"
    "..n............."
    ".nnn............"
    "..........nn...."
    ".........nnnn..."
    "................"
    "................";

/* ------------------------------------------------------------ things */
static const char NUGGET[] =
    "..........."
    "...kkkk...."
    "..kyccyk..."
    ".kyyycayk.."
    ".kayyyyak.."
    "kaaayyaaak."
    "koaaaaaaok."
    ".kkooookk.."
    "...kkkk....";
static const char GEM1[] =
    "..kkkkk..."
    ".kIwICuk.."
    "kIIICCuuk."
    "kuuCCuuBk."
    ".kuCuuBk.."
    "..kuuBk..."
    "...kBk...."
    "....k.....";
static const char GEM2[] =
    "..kkkkk..."
    ".kICwCuk.."
    "kICCIwuuk."
    "kuuCCuuBk."
    ".kuCuuBk.."
    "..kuuBk..."
    "...kBk...."
    "....k.....";
static const char CHEST[] =
    "................"
    "................"
    "................"
    "..kkkkkkkkkkkk.."
    ".kheeeeeeeeeehk."
    ".ketttttttttttk."
    "kkkkkkkkkkkkkkkk"
    "kaytttkyykttttak"
    "kyatttkaakttttyk"
    "kkkkkkkkkkkkkkkk"
    "ketttttkktttttek"
    "ktbbbbbkkbbbbbtk"
    "ktbbbbbbbbbbbbtk"
    "kabbbbbbbbbbbbak"
    "kkkkkkkkkkkkkkkk"
    "................";
static const char CHEST_OPEN[] =
    "..kkkkkkkkkkkk.."
    ".kheeeeeeeeeehk."
    ".ketttttttttttk."
    ".kbbbbbbbbbbbbk."
    ".kkkkkkkkkkkkkk."
    "................"
    "kkkkkkkkkkkkkkkk"
    "kknnnnnnnnnnnnkk"
    "kanndnnndnnnnnak"
    "kkkkkkkkkkkkkkkk"
    "ketttttkktttttek"
    "ktbbbbbkkbbbbbtk"
    "ktbbbbbbbbbbbbtk"
    "kabbbbbbbbbbbbak"
    "kkkkkkkkkkkkkkkk"
    "................";
static const char CAGE[] =
    ".......kk......."
    "......kaak......"
    "....kkkaakkk...."
    "...kaaaaaaaak..."
    "..ka.a.a.a.a.k.."
    "..ka.a.a.a.a.k.."
    "..ka.a.kkkaa.k.."
    "..ka.akyyyk.ak.."
    "..ka.kyykwkkak.."
    "..ka.kyyyyoka.k."
    "..ka.kyyyyka..k."
    "..ka.a.kkkaa.ak."
    "..ka.a.o.o.a.ak."
    "..kaaaaaaaaaaak."
    "..kkkkkkkkkkkkk."
    "................";
static const char CAGE_OPEN[] =
    ".......kk......."
    "......kaak......"
    "....kkkaakkk...."
    "...kaaaaaaaak..."
    "..ka.a.a...a.k.."
    "..ka.a.a...a.k.."
    "..ka.a.a......k."
    "..ka.a.a........"
    "..ka.a.a........"
    "..ka.a.a........"
    "..ka.a.a.......k"
    "..ka.a.a...a.ak."
    "..ka.a.a...a.ak."
    "..kaaaaaaaaaaak."
    "..kkkkkkkkkkkkk."
    "................";
static const char SUNSTONE[] =
    "......kkkk......"
    "....kkyyyykk...."
    "...kyyccccyyk..."
    "..kyccwwccccyk.."
    "..kycwwccccayk.."
    ".kyccwccccccayk."
    ".kycccccccccayk."
    ".kyccccccccaayk."
    ".kyacccccccaayk."
    ".kyaaccccaaaayk."
    "..kyaaaaaaaayk.."
    "..kyyaaaaaayyk.."
    "...kyyyyyyyyk..."
    "....kkyyyykk...."
    "......kkkk......"
    "................";
static const char PEDESTAL[] =
    "kkkkkkkkkkkkkkkk"
    "kgggggggggggggsk"
    "kssssssssssssssk"
    ".kkkkkkkkkkkkkk."
    "..ksddsdddsdsk.."
    "..kdsddsdsddsk.."
    "..ksdsddddsdsk.."
    ".kkkkkkkkkkkkkk.";
static const char LIFT[] =
    "kkkkkkkkkkkkkkkk"
    "kglgglgglgglgglk"
    "kssssssssssssssk"
    "knknknknknknknkk"
    "kkkkkkkkkkkkkkkk"
    "..ka........ak.."
    "..kk........kk..";

static const char KEEPER_TOAD1[] =
    "......kkkk......"
    ".....kaaaak....."
    "...kkkkkkkkkk..."
    "....kjjjjjjk...."
    "...kwkjjjjkwk..."
    "...kkkjjjjkkk..."
    "..kjjjjjjjjjjk.."
    "..kjzkkkkkkzjk.."
    "..kjjjjjjjjjjk.."
    ".ktttjjjjjjtttk."
    "kteettiiiitteetk"
    "kttettiiiittettk"
    ".kttttiiiittttk."
    "..kjjjkkkkjjjk.."
    "..kffk....kffk.."
    "..kkkk....kkkk..";
static const char KEEPER_TOAD2[] =
    "................"
    "......kkkk......"
    ".....kaaaak....."
    "...kkkkkkkkkk..."
    "....kjjjjjjk...."
    "...kwkjjjjkwk..."
    "...kkkjjjjkkk..."
    "..kjjjjjjjjjjk.."
    "..kjzkkrrkkzjk.."
    ".ktttjkkkkjtttk."
    "kteettiiiitteetk"
    "kttettiiiittettk"
    ".kttttiiiittttk."
    "..kjjjkkkkjjjk.."
    "..kffk....kffk.."
    "..kkkk....kkkk..";
static const char KEEPER_OWL1[] =
    "...kk......kk..."
    "...ktkkkkkktk..."
    "...kttttttttk..."
    "..kttkkttkkttk.."
    "..ktkyykkyyktk.."
    "..ktkykkkykktk.."
    "..kttkkaakkttk.."
    "..ktttteatttk..."
    ".kttehhhhhhettk."
    ".ktehhthhthhetk."
    ".ktehhhhhhhhetk."
    ".kttehhthhhettk."
    "..kttehhhhettk.."
    "...kttttttttk..."
    "...kaak..kaak..."
    "...kkkk..kkkk...";
static const char KEEPER_OWL2[] =
    "...kk......kk..."
    "...ktkkkkkktk..."
    "...kttttttttk..."
    "..kttkkttkkttk.."
    "..ktkttkkttktk.."
    "..ktkkkkkkkktk.."
    "..kttkkaakkttk.."
    "..ktttteatttk..."
    ".kttehhhhhhettk."
    ".ktehhthhthhetk."
    ".ktehhhhhhhhetk."
    ".kttehhthhhettk."
    "..kttehhhhettk.."
    "...kttttttttk..."
    "...kaak..kaak..."
    "...kkkk..kkkk...";
static const char KEEPER_LIZ1[] =
    ".....kkkk......."
    "....kzzzzk......"
    "...kzwkzzzk....."
    "...kzkkzzzzkk..."
    "...kzzzzzzzzzk.."
    "....kzzrrrzzk..."
    ".....kzzzzkk...."
    "....kjzzzzjk...."
    "...kjlllllljk..."
    "..kzjlllllljzk.."
    "..kzjlltttljzk.."
    "..kzjlllllljzk.."
    "...kjlllllljk..."
    "....kjjkkjjk...."
    "....kzzk.kzzk..."
    "....kkkk.kkkk...";
static const char KEEPER_LIZ2[] =
    ".....kkkk......."
    "....kzzzzk......"
    "...kzkkzzzk....."
    "...kzkkzzzzkk..."
    "...kzzzzzzzzzk.."
    "....kzzzzzzzk..."
    ".....kzzzzkk...."
    "....kjzzzzjk...."
    "...kjlllllljk..."
    "..kzjlllllljzk.."
    "..kzjlltttljzk.."
    "..kzjlllllljzk.."
    "...kjlllllljk..."
    "....kjjkkjjk...."
    "....kzzk.kzzk..."
    "....kkkk.kkkk...";
static const char VENDOR1[] =
    ".......kk......."
    "......kyyk......"
    "......kyck......"
    ".......kk......."
    ".....kkkkkk....."
    "....kppppppk...."
    "...kppkkkkppk..."
    "...kpkyykyykk..."
    "...kpkkkkkkpk..."
    "..kppppppppppk.."
    "..kpVppppppVpk.."
    ".kppVpppppppVpk."
    ".kpVVpppppppVVk."
    ".kpVppppppppVpk."
    ".kpppppppppppppk"
    ".kkkkkkkkkkkkkkk";
static const char VENDOR2[] =
    "................"
    ".......kk......."
    "......kyyk......"
    "......kcyk......"
    ".....kkkkkk....."
    "....kppppppk...."
    "...kppkkkkppk..."
    "...kpkyykyykk..."
    "...kpkkkkkkpk..."
    "..kppppppppppk.."
    "..kpVppppppVpk.."
    ".kppVpppppppVpk."
    ".kpVVpppppppVVk."
    ".kpVppppppppVpk."
    ".kpppppppppppppk"
    ".kkkkkkkkkkkkkkk";

static const char SMITH1[] =
    "..........kkkk.."
    ".........kgssgk."
    ".........kgsssk."
    "....kkkk..kkkk.."
    "...knnnnk..kk..."
    "..knddddnk.kt..."
    "..kdwdddddkkt..."
    "..kdkdddKKdkt..."
    "..kddddddPPkt..."
    ".ktttttttkkkt..."
    "kdktbbbbtkdkk..."
    "kdktbbbbtkdk...."
    ".kktttttttk....."
    "..kdddkdddk....."
    "..kKKk.kKKk....."
    "..kkk..kkk......";
static const char SMITH2[] =
    "................"
    "................"
    "....kkkk........"
    "...knnnnk......."
    "..knddddnk......"
    "..kdwdddddk....."
    "..kdkdddKKdk...."
    "..kddddddPPk...."
    ".ktttttttkk....."
    "kdktbbbbtkdk.kk."
    "kdktbbbbtkdkkgsk"
    ".kktttttttkktgsk"
    "..kdddkdddkt.kk."
    "..kKKk.kKKkt...."
    "..kkk..kkk.t...."
    "...........k....";
static const char LEVER_UP[] =
    "................"
    "................"
    "..........kk...."
    ".........krrk..."
    ".........kwrk..."
    "..........kk...."
    ".........kgk...."
    "........kgk....."
    ".......kgk......"
    "......kgk......."
    "....kkkkkkkk...."
    "...ksssssssssk.."
    "...kgggggggggk.."
    "...kssdssdsssk.."
    "...kkkkkkkkkkk.."
    "................";
static const char LEVER_DOWN[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "....kk.........."
    "...krrk........."
    "...kwrk........."
    "....kkgk........"
    "......kgk......."
    "....kkkkkkkk...."
    "...ksssssssssk.."
    "...kgggggggggk.."
    "...kssdssdsssk.."
    "...kkkkkkkkkkk.."
    "................";
static const char SHRINE[] =
    "................"
    "................"
    ".......kk......."
    "......kggk......"
    ".....kgllgk....."
    "....kgllllgk...."
    "...kkkkkkkkkk..."
    "...kgsssssssk..."
    "...kgsknnksgk..."
    "...kgsknnksgk..."
    "...kgsssssssk..."
    "..kkkkkkkkkkkk.."
    "..kgggggggggsk.."
    "..kssssssssssk.."
    "..kkkkkkkkkkkk.."
    "................";
static const char SHRINE_OPEN[] =
    "................"
    "................"
    ".......kk......."
    "......kggk......"
    ".....kgllgk....."
    "....kgllllgk...."
    "...kkkkkkkkkk..."
    "...kgsssssssk..."
    "...kgskyaksgk..."
    "...kgskaaksgk..."
    "...kgsssssssk..."
    "..kkkkkkkkkkkk.."
    "..kgggggggggsk.."
    "..kssssssssssk.."
    "..kkkkkkkkkkkk.."
    "................";
static const char PUSH[] =
    "kkkkkkkkkkkkkkkk"
    "kheeeeeeeeeeeetk"
    "ketttttttttttttk"
    "ketbtttttttttbtk"
    "kettbtttttttbttk"
    "ketttbtttttbtttk"
    "kettttbtttbttttk"
    "ketttttbtbtttttk"
    "ketttttbtbtttttk"
    "kettttbtttbttttk"
    "ketttbtttttbtttk"
    "kettbtttttttbttk"
    "ketbtttttttttbtk"
    "ketttttttttttttk"
    "ktbbbbbbbbbbbbbk"
    "kkkkkkkkkkkkkkkk";
static const char I_BOOT[] =
    "............"
    "..kkkk......"
    "..ktttk....."
    "..ktbtk....."
    "..ktttk....."
    "..ktbtk....."
    "..ktttkkkk.."
    ".kttttttttk."
    ".ktbbbbbttk."
    ".kkkkkkkkkk."
    "............"
    "............";
static const char AXE[] =
    "..kk...."
    ".kssk..."
    "kslsk..."
    "kssktk.."
    ".kk.ktk."
    "....ktk."
    ".....kk."
    "........";

/* item icons 12x12 */
static const char I_POT[] =
    "............"
    "....kkkk...."
    "..kkaooakk.."
    ".kaoooooook."
    ".koaaaaaaok."
    "kkkkkkkkkkkk"
    "koaoooooooak"
    "kooaaooaaook"
    ".kooooooook."
    "..koooooak.."
    "...kkkkkk..."
    "............";
static const char I_FORK[] =
    "............"
    ".kk....kk..."
    ".kIk..kIk..."
    ".kIk..kIk..."
    ".kIk..kIk..."
    ".kIk..kIk..."
    "..kIkkIk...."
    "...kIIk....."
    "....kIk....."
    "....kuk....."
    "....kuk....."
    ".....k......";
static const char I_CRANK[] =
    "............"
    "..k.kkk.k..."
    ".kgkgggkgk.."
    "..kggkggk..."
    ".kggk.kggk.."
    ".kggk.kggkk."
    "..kggkggktek"
    ".kgkgggkktek"
    "..k.kkk..kek"
    "..........k."
    "............"
    "............";
static const char I_GLOVES[] =
    "............"
    "..kk.kk....."
    ".kok.kok.kk."
    ".kok.kokkok."
    ".kookkookok."
    ".kooookooook"
    ".koooooooook"
    "..koooooook."
    "..kaaaaaaak."
    "..kaaaaaaak."
    "..kkkkkkkkk."
    "............";
static const char I_KEY[] =
    "............"
    "..kkkk......"
    ".kyyyyk....."
    "kyakkayk...."
    "kyk..kyk...."
    "kyakkayk...."
    ".kyyyykk...."
    "..kkkyyyyyk."
    "....kakayak."
    "....kk.kkyk."
    "........kk.."
    "............";
static const char I_CANARY[] =
    "............"
    "....kkkk...."
    "...kyyyyk..."
    "..kyykwyykk."
    "..kyyyyyyoak"
    ".kyyyyyyykk."
    "kyaayyyyyk.."
    ".kaaayyyak.."
    "..kkaaaakk.."
    "....kokk...."
    "....kk......"
    "............";
static const char I_ROD[] =
    "........kkk."
    ".......kCIck"
    "......kkIwIk"
    ".....kVkCIuk"
    "....kVpkkuk."
    "...kVpk.kk.."
    "..kVpk......"
    ".kVpk......."
    "kVpk........"
    "kpk........."
    ".k.........."
    "............";
static const char I_HUNGRY[] =
    ".......kk..."
    "......kPrk.."
    ".....kPwkrk."
    "....kPrkkPk."
    "...kvkkPrk.."
    "..kvmk.kk..."
    ".kvmk......."
    "kvmk........"
    "kmk........."
    ".k.........."
    "............"
    "............";
static const char I_LANTERN[] =
    "....kkkk...."
    "....k..k...."
    "...kkkkkk..."
    "..ksggggsk.."
    "..kgyccygk.."
    "..kgycwcgk.."
    "..kgyaacgk.."
    "..kgyyyygk.."
    "..ksggggsk.."
    "...kkkkkk..."
    "............"
    "............";

/* ------------------------------------------------------------ enemies */
static const char MOTH1[] =
    "................"
    "....k......k...."
    ".....k....k....."
    "..kkkk.kk.kkkk.."
    ".kllllkddkllllk."
    "klwlggkddkgglwlk"
    "kllgggkddkggllk."
    ".klggkkddkkggkl."
    "..kkk.kddk.kkk.."
    "......kddk......"
    ".......kk......."
    "................";
static const char MOTH2[] =
    "................"
    "....k......k...."
    ".....k....k....."
    "......kkkk......"
    "......kddk......"
    "..kkkkkddkkkkk.."
    ".kllggkddkggllk."
    "klwlggkddkgglwlk"
    "klllgk.kk.kglllk"
    ".kkkk......kkkk."
    "................"
    "................";
static const char TOAD1[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "....kk....kk...."
    "...kwkk..kkwk..."
    "...kkjkkkkjkk..."
    "..kjjjjjjjjjjk.."
    ".kjzzjjjjjjzzjk."
    ".kjjjjrrrrjjjjk."
    "kjjjkkkkkkkkjjjk"
    "kjjk.kiiiik.kjjk"
    "kffjkiiiiiikjffk"
    "kfffkkkkkkkkfffk"
    ".kkk........kkk.";
static const char TOAD2[] =
    "................"
    "....kk....kk...."
    "...kwkk..kkwk..."
    "...kkjkkkkjkk..."
    "..kjjjjjjjjjjk.."
    ".kjzzjjjjjjzzjk."
    ".kjjjjrrrrjjjjk."
    ".kjjjkkkkkkjjjk."
    "..kjkiiiiiikjk.."
    "..kjkiiiiiikjk.."
    "..kfkkkkkkkkfk.."
    "..kfk......kfk.."
    ".kffk......kffk."
    ".kfk........kfk."
    "..k..........k.."
    "................";
static const char GRUB1[] =
    "................"
    "................"
    "...kkkkkkkkkk..."
    "..kccchccchcbk.."
    ".kcchccchcctbbk."
    ".kccchccchcbtwk."
    ".kkkkkkkkkkkkkk."
    "..k.k.k.k.k.k...";
static const char GRUB2[] =
    "................"
    "....kkkkkkkkk..."
    "..kkccchccchbk.."
    ".kcchccchcctbbk."
    ".kccchccchcbtwk."
    ".kkkkkkkkkkkkkk."
    "...k.k.k.k.k.k.."
    "................";
static const char SPIT1[] =
    "................"
    "................"
    "................"
    "......kkkk......"
    "....kksggskk...."
    "...ksgggggggk..."
    "..ksgwkgggwkgk.."
    "..ksgkkgggkkgk.."
    "..kssgggggggsk.."
    ".ksssskkkkksssk."
    ".kdsssssssssdk.."
    ".kddssssssssddk."
    "kdddddsssddddddk"
    "kddnddddddddnddk"
    ".kkkkkkkkkkkkkk."
    "................";
static const char SPIT2[] =
    "................"
    "................"
    "................"
    "......kkkk......"
    "....kksggskk...."
    "...ksgggggggk..."
    "..ksgwkgggwkgk.."
    "..ksgkkgggkkgk.."
    "..kssgkkkkgssk.."
    ".ksssk.....kssk."
    ".kdssk.....ksdk."
    ".kddsskkkkksddk."
    "kdddddsssddddddk"
    "kddnddddddddnddk"
    ".kkkkkkkkkkkkkk."
    "................";
static const char SWOOP_HANG[] =
    "......k..k......"
    "......k..k......"
    ".....kpkkpk....."
    "....kpVVVVpk...."
    "...kpVVVVVVpk..."
    "...kpVVVVVVpk..."
    "...kppVVVVppk..."
    "...kpkpVVpkpk..."
    "....kpkyykpk...."
    "....kpkkkkpk...."
    ".....kKppKk....."
    "......kkkk......"
    "................"
    "................"
    "................"
    "................";
static const char SWOOP1[] =
    "................"
    "................"
    ".kk..........kk."
    "kpVk..k..k..kVpk"
    "kpVVkkKkkKkkVVpk"
    "kpVVVpVVVVpVVVpk"
    ".kpVVVyVVyVVVpk."
    "..kpVVkVVkVVpk.."
    "...kkpVVVVpkk..."
    ".....kpkkpk....."
    "......k..k......"
    "................";
static const char SWOOP2[] =
    "................"
    "................"
    "................"
    "......k..k......"
    "......KkkK......"
    "....kpVVVVpk...."
    "..kkpVyVVyVpkk.."
    ".kpVVVkVVkVVVpk."
    "kpVVpppVVpppVVpk"
    "kpVpk.kppk.kpVpk"
    "kppk...kk...kppk"
    ".kk..........kk.";
static const char SACK[] =
    "................"
    "................"
    "................"
    ".....kk..kk....."
    "......kkkk......"
    ".....kteetk....."
    "......kttk......"
    "....kkteetkk...."
    "...kteeeeeettk.."
    "..kteeyyyyeettk."
    "..kteyaeeaeettk."
    "..kteeyyyyeettk."
    "..ktteeaaeettbk."
    "..kbtteeeettbbk."
    "...kbbttttbbbk.."
    "....kkkkkkkkk...";
static const char SACK_HOP[] =
    "................"
    ".....kk..kk....."
    "......kkkk......"
    ".....kteetk....."
    "......kttk......"
    "....kkteetkk...."
    "...kteeeeeettk.."
    "..ktekwkekwkttk."
    "..kteekeeekettk."
    "..ktkwkwkwkwktk."
    "..ktkrrrrrrrktk."
    "..ktkwkwkwkwkbk."
    "..kbtkkkkkkkbbk."
    "...kbbttttbbbk.."
    "....kkkkkkkkk..."
    "................";
static const char BEETLE1[] =
    "................"
    "................"
    "......kkkkk....."
    "....kkNBBuukk..."
    "...kNBBBBBuuIk.."
    "..kNNBBBBBBuuk.k"
    "..kNNBBBBBBBukgk"
    "..kNNNBBBBBBkgsk"
    "..kkNNNNBBBkggk."
    "...kkkkkkkkkkk.."
    "...k.k..k.k.k..."
    "..k..k..k..k.k..";
static const char BEETLE2[] =
    "................"
    "................"
    "......kkkkk....."
    "....kkNBBuukk..."
    "...kNBBBBBuuIk.."
    "..kNNBBBBBBuuk.k"
    "..kNNBBBBBBBukgk"
    "..kNNNBBBBBBkgsk"
    "..kkNNNNBBBkggk."
    "...kkkkkkkkkkk.."
    "....k.k..k.k.k.."
    "....k..kk..k.k..";
static const char WISP1[] =
    "....kk......"
    "...kIk......"
    "..kICk..k..."
    "..kICCkkIk.."
    ".kICCCCICk.."
    ".kCwkCCwkk.."
    "kCCkkCCkkCk."
    "kCCCCCCCCCk."
    "kuCCCCCCCuk."
    ".kuCuuCuuk.."
    "..kukkuk...."
    "...k..k.....";
static const char WISP2[] =
    ".......kk..."
    "......kIk..."
    "..k..kCIk..."
    ".kIkkCCIk..."
    ".kCICCCCIk.."
    ".kkwkCCwkCk."
    "kCkkCCCkkCk."
    "kCCCCCCCCCk."
    "kuCCCCCCCuk."
    ".kuuCuuCuk.."
    "...kukkuk..."
    "....k..k....";
static const char GLOOM1[] =
    "........kkkkkkkk........"
    "......kknnnnnnnnkk......"
    ".....knnnnnnnnnnnnk....."
    "....knnnnnnnnnnnnnnk...."
    "...knnnkkkkkkkkknnnnk..."
    "...knnkkkkkkkkkkknnnk..."
    "..knnkkkIkkkkIkkkknnnk.."
    "..knnkkkIIkkkIIkkknnnk.."
    "..knnkkkkkkkkkkkkknnnk.."
    "..knnnkkkkkkkkkkknnnnk.."
    "..knnnnkkkkkkkkknnnnnk.."
    "..knnnnnnnnnnnnnnnnnnk.."
    ".kdnnnnnnnnnnnnnnnnnndk."
    ".kdnnnnnnnnnnnnnnnnnndk."
    ".kddnnnnnnnnnnnnnnnnddk."
    "kddnnnnnnnnnnnnnnnnnnddk"
    "kdnnnnnnnnnnnnnnnnnnnndk"
    "kdnnnnnnnnnnnnnnnnnnnndk"
    ".kdnnnkdnnnkdnnnkdnnndk."
    ".kddnk.kdnk.kdnk.kdnddk."
    "..kdk...kdk..kdk..kdk..."
    "...k.....k....k....k...."
    "........................"
    "........................";
static const char GLOOM2[] =
    "........kkkkkkkk........"
    "......kknnnnnnnnkk......"
    ".....knnnnnnnnnnnnk....."
    "....knnnnnnnnnnnnnnk...."
    "...knnnkkkkkkkkknnnnk..."
    "...knnkkkkkkkkkkknnnk..."
    "..knnkkkkIkkkkIkkknnnk.."
    "..knnkkkkIIkkkIIkknnnk.."
    "..knnkkkkkkkkkkkkknnnk.."
    "..knnnkkkkkkkkkkknnnnk.."
    "..knnnnkkkkkkkkknnnnnk.."
    "..knnnnnnnnnnnnnnnnnnk.."
    ".kdnnnnnnnnnnnnnnnnnndk."
    ".kdnnnnnnnnnnnnnnnnnndk."
    ".kddnnnnnnnnnnnnnnnnddk."
    "kddnnnnnnnnnnnnnnnnnnddk"
    "kdnnnnnnnnnnnnnnnnnnnndk"
    "kdnnnnnnnnnnnnnnnnnnnndk"
    ".kdnnkdnnnkdnnnkdnnnndk."
    "..kdnk.kdnk.kdnk.kdndk.."
    "...kdk..kdk..kdk.kdk...."
    "....k....k....k...k....."
    "........................"
    "........................";
static const char CANARY1[] =
    "..kkkk...."
    ".kyyyyk..."
    "kyykwyyk.."
    "kyyyyyyoak"
    ".kyyyyykk."
    "kyaayyyyk."
    "kaaaayyk.."
    ".kkkkkk...";
static const char CANARY2[] =
    "..kkkk...."
    ".kyyyyk..."
    "kyykwyyk.."
    "kyyyyyyoak"
    "kaayyyykk."
    "kaaayyyyk."
    ".kkayyyk.."
    "...kkkk...";

/* ------------------------------------------------------------ boss (48x40) */
static const char BOSS_SHUT[] =
    "..................kkkkkkkkkkkk.................."
    "..............kkkkddddddddddddkkkk.............."
    "...........kkkddddsddddddddsddddddkkk..........."
    ".........kkddddddddddnnnnddddddddddddkk........."
    "........kddddsddddnnnkkkknnnddddddsddddk........"
    "......kkdddddddnnkkVVVVVVVVkknnddddddddkk......."
    ".....kddddddnnkkVVPPPPPPPPPPVVkknnddddddk......."
    "....kddsdddnkkVPPKKKKKKKKKKPPPVkknddddddk......."
    "...kddddddnkVPPKKKwwKKKKKKKKKPPVknddsdddk......."
    "...kddddnnkVPKKKwwKKKKKKKKKKKKPPVknddddddk......"
    "..kdsdddnkVPKKKKKKKKKKKKKKKKKKKPPVkndddddk......"
    "..kddddnkVPKKKKKKKKKKKKKKKKKKKKKPPVknddsddk....."
    ".kdddddnkVPKKKKKKKKKKKKKKKKKKKKKKPVkndddddk....."
    ".kddsddnkVPKKKKkkkkkkkkkkkkKKKKKKPVknddddddk...."
    ".kdddddnkVPKKKkppppppppppppkKKKKKPVkndddsddk...."
    "kdddddnkVPKKKkppppppppppppppkKKKKPVknddddddk...."
    "kddsddnkVPKKKkppppppppppppppkKKKKPVkndddddddk..."
    "kdddddnkVPKKKKkkkkkkkkkkkkkkKKKKKPVknddsddddk..."
    "kdddddnkVPKKKKKKKKKKKKKKKKKKKKKKKPVknddddddk...."
    "kddsddnkVPPKKKKKKKKKKKKKKKKKKKKKPPVkndddddk....."
    ".kdddddnkVPPKKKKKKKKKKKKKKKKKKKPPVknddddddk....."
    ".kddddddnkVPPKKKKKKKKKKKKKKKKKPPVknddsdddk......"
    ".kddsddddnkVPPPKKKKKKKKKKKKKPPPVknddddddk......."
    "..kdddddddnkVVPPPPPPPPPPPPPPPVVknddddddk........"
    "..kdddsddddnkkVVVVVVVVVVVVVVVkknddddsdk........."
    "...kddddddddnnkkkkkkkkkkkkkkknnddddddk.........."
    "...kddddsdddddnnnnnnnnnnnnnnnddddddk............"
    "....kdddddddddddddddsddddddddddddk.............."
    ".....kkddsdddddddddddddddsddddkk................"
    ".......kkdddddddsdddddddddddkk.................."
    ".........kkkddddddddddddkkkk...................."
    "............kkkkkkkkkkkk........................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................";
static const char BOSS_OPEN[] =
    "..................kkkkkkkkkkkk.................."
    "..............kkkkddddddddddddkkkk.............."
    "...........kkkddddsddddddddsddddddkkk..........."
    ".........kkddddddddddnnnnddddddddddddkk........."
    "........kddddsddddnnnkkkknnnddddddsddddk........"
    "......kkdddddddnnkkVVVVVVVVkknnddddddddkk......."
    ".....kddddddnnkkVVPPPPPPPPPPVVkknnddddddk......."
    "....kddsdddnkkVPPKKKKKKKKKKPPPVkknddddddk......."
    "...kddddddnkVPPKKKwwKKKKKKKKKPPVknddsdddk......."
    "...kddddnnkVPKKKwwKKKKKKKKKKKKPPVknddddddk......"
    "..kdsdddnkVPKKKKKkkkkkkkkkkKKKKPPVkndddddk......"
    "..kddddnkVPKKKKkkwwwwwwwwwkkKKKKPPVknddsddk....."
    ".kdddddnkVPKKKkwwwwwkkkwwwwwkKKKKPVkndddddk....."
    ".kddsddnkVPKKkwwwwwkrrrkwwwwwkKKKKPVknddddddk..."
    ".kdddddnkVPKKkwwwwkrrkkrkwwwwkKKKKPVkndddsddk..."
    "kdddddnkVPKKKkwwwwkrkkkrkwwwwkKKKKPVknddddddk..."
    "kddsddnkVPKKKkwwwwwkrrrkwwwwwkKKKKPVkndddddddk.."
    "kdddddnkVPKKKKkwwwwwkkkwwwwwkKKKKKPVknddsddddk.."
    "kdddddnkVPKKKKKkkwwwwwwwwwkkKKKKKPVknddddddk...."
    "kddsddnkVPPKKKKKKkkkkkkkkkKKKKKKPPVkndddddk....."
    ".kdddddnkVPPKKKKKKKKKKKKKKKKKKKPPVknddddddk....."
    ".kddddddnkVPPKKKKKKKKKKKKKKKKKPPVknddsdddk......"
    ".kddsddddnkVPPPKKKKKKKKKKKKKPPPVknddddddk......."
    "..kdddddddnkVVPPPPPPPPPPPPPPPVVknddddddk........"
    "..kdddsddddnkkVVVVVVVVVVVVVVVkknddddsdk........."
    "...kddddddddnnkkkkkkkkkkkkkkknnddddddk.........."
    "...kddddsdddddnnnnnnnnnnnnnnnddddddk............"
    "....kdddddddddddddddsddddddddddddk.............."
    ".....kkddsdddddddddddddddsddddkk................"
    ".......kkdddddddsdddddddddddkk.................."
    ".........kkkddddddddddddkkkk...................."
    "............kkkkkkkkkkkk........................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................"
    "................................................";

/* ------------------------------------------------------------ fx */
static const char STONE[] =
    ".kkkk."
    "kgssdk"
    "ksddnk"
    "ksdnnk"
    "kdnnnk"
    ".kkkk.";
static const char SHARD[] =
    "..kk.."
    ".kKPk."
    "kKwPPk"
    "kKPPVk"
    ".kPVk."
    ".kPVk."
    "..kk.."
    "......";
static const char DRIP_FALL[] =
    ".kk."
    "kCIk"
    "kuCk"
    "kuuk"
    ".kk."
    "....";
static const char SPARK[] =
    "..y..."
    ".yay.."
    "yacay."
    ".yay.y"
    "..y..."
    "......";
static const char BOLT[] =
    "...kkk.."
    "kkkCICk."
    "kuCIwICk"
    "kkkCICk."
    "...kkk.."
    "........";
static const char COIN[] =
    ".kkkk."
    "kyccyk"
    "kyaayk"
    "kyaayk"
    "koaaok"
    ".kkkk.";
static const char PUFF1[] =
    "............"
    "............"
    "............"
    "....llll...."
    "...lwwwwl..."
    "...lwwwwl..."
    "...lwwwwl..."
    "....llll...."
    "............"
    "............"
    "............"
    "............";
static const char PUFF2[] =
    "............"
    "..l..ll..l.."
    "...lllllll.."
    ".llwwllwwll."
    ".lwwlllllwl."
    "..lwl..lwll."
    ".llwl..lwl.."
    ".lwwlllwwll."
    "..llwwwwll.."
    "..l.llll..l."
    "............"
    "............";
static const char PUFF3[] =
    ".l........l."
    "..g..gg..g.."
    "...g....g..."
    ".g........g."
    "g..........g"
    "............"
    "............"
    "g..........g"
    ".g........g."
    "...g....g..."
    "..g..gg..g.."
    ".l........l.";
static const char LANTERN_HUD[] =
    "..kkk.."
    "..k.k.."
    ".kkkkk."
    "kgyyygk"
    "kgycygk"
    "kgyaygk"
    "kgyyygk"
    ".kkkkk."
    ".......";
static const char LANTERN_HUD_OFF[] =
    "..kkk.."
    "..k.k.."
    ".kkkkk."
    "kdnnndk"
    "kdnnndk"
    "kdnnndk"
    "kdnnndk"
    ".kkkkk."
    ".......";

static const ArtDef ART[] = {
    {S_MO_IDLE, 16, 16, MO_IDLE}, {S_MO_BLINK, 16, 16, MO_BLINK}, {S_MO_WALK1, 16, 16, MO_WALK1},
    {S_MO_WALK2, 16, 16, MO_WALK2}, {S_MO_JUMP, 16, 16, MO_JUMP}, {S_MO_FALL, 16, 16, MO_FALL},
    {S_MO_CLIMB1, 16, 16, MO_CLIMB}, {S_MO_CLIMB2, 16, 16, MO_CLIMB}, {S_MO_SWING1, 16, 16, MO_SWING1},
    {S_MO_SWING2, 16, 16, MO_SWING2}, {S_MO_HURT, 16, 16, MO_HURT},
    {S_PICK_UP, 16, 8, PICK_UP}, {S_PICK_FWD, 16, 9, PICK_FWD}, {S_ROD_FWD, 16, 6, ROD_FWD},
    {S_HUNGRY_FWD, 16, 9, HUNGRY_FWD},
    {S_T_ROCK, 16, 16, T_ROCK}, {S_T_ROCK2, 16, 16, T_ROCK2}, {S_T_BRICK, 16, 16, T_BRICK},
    {S_T_PLANK, 16, 16, T_PLANK}, {S_T_LADDER, 16, 16, T_LADDER}, {S_T_ROPE, 16, 16, T_ROPE},
    {S_T_SPIKES, 16, 16, T_SPIKES}, {S_T_CRYSTAL, 16, 16, T_CRYSTAL}, {S_T_DRIP, 16, 16, T_DRIP},
    {S_T_OOZE1, 16, 16, T_OOZE1}, {S_T_OOZE2, 16, 16, T_OOZE2}, {S_T_OOZEBODY, 16, 16, T_OOZEBODY},
    {S_T_GATE, 16, 16, T_GATE}, {S_T_SEAL, 16, 16, T_SEAL}, {S_T_BEAM, 16, 16, T_BEAM},
    {S_T_TORCH1, 16, 16, T_TORCH1}, {S_T_TORCH2, 16, 16, T_TORCH2}, {S_T_MUSH, 16, 16, T_MUSH},
    {S_T_CRYS_DECOR, 16, 16, T_CRYS_DECOR}, {S_T_BGROCK, 16, 16, T_BGROCK},
    {S_NUGGET, 11, 9, NUGGET}, {S_GEM1, 10, 8, GEM1}, {S_GEM2, 10, 8, GEM2},
    {S_CHEST, 16, 16, CHEST}, {S_CHEST_OPEN, 16, 16, CHEST_OPEN}, {S_CAGE, 16, 16, CAGE},
    {S_CAGE_OPEN, 16, 16, CAGE_OPEN}, {S_SMITH1, 16, 16, SMITH1}, {S_SMITH2, 16, 16, SMITH2},
    {S_LEVER_UP, 16, 16, LEVER_UP}, {S_LEVER_DOWN, 16, 16, LEVER_DOWN}, {S_SHRINE, 16, 16, SHRINE},
    {S_SHRINE_OPEN, 16, 16, SHRINE_OPEN}, {S_PUSH, 16, 16, PUSH}, {S_I_BOOT, 12, 12, I_BOOT}, {S_AXE, 8, 8, AXE},
    {S_SUNSTONE, 16, 16, SUNSTONE}, {S_PEDESTAL, 16, 8, PEDESTAL}, {S_LIFT, 16, 7, LIFT},
    {S_KEEPER_TOAD1, 16, 16, KEEPER_TOAD1}, {S_KEEPER_TOAD2, 16, 16, KEEPER_TOAD2},
    {S_KEEPER_OWL1, 16, 16, KEEPER_OWL1}, {S_KEEPER_OWL2, 16, 16, KEEPER_OWL2},
    {S_KEEPER_LIZ1, 16, 16, KEEPER_LIZ1}, {S_KEEPER_LIZ2, 16, 16, KEEPER_LIZ2},
    {S_VENDOR1, 16, 16, VENDOR1}, {S_VENDOR2, 16, 16, VENDOR2},
    {S_I_POT, 12, 12, I_POT}, {S_I_FORK, 12, 12, I_FORK}, {S_I_CRANK, 12, 12, I_CRANK},
    {S_I_GLOVES, 12, 12, I_GLOVES}, {S_I_KEY, 12, 12, I_KEY}, {S_I_CANARY, 12, 12, I_CANARY},
    {S_I_ROD, 12, 12, I_ROD}, {S_I_HUNGRY, 12, 12, I_HUNGRY}, {S_I_LANTERN, 12, 12, I_LANTERN},
    {S_MOTH1, 16, 12, MOTH1}, {S_MOTH2, 16, 12, MOTH2}, {S_TOAD1, 16, 16, TOAD1}, {S_TOAD2, 16, 16, TOAD2},
    {S_GRUB1, 16, 8, GRUB1}, {S_GRUB2, 16, 8, GRUB2}, {S_SPIT1, 16, 16, SPIT1}, {S_SPIT2, 16, 16, SPIT2},
    {S_SWOOP_HANG, 16, 16, SWOOP_HANG}, {S_SWOOP1, 16, 12, SWOOP1}, {S_SWOOP2, 16, 12, SWOOP2},
    {S_SACK, 16, 16, SACK}, {S_SACK_HOP, 16, 16, SACK_HOP}, {S_BEETLE1, 16, 12, BEETLE1},
    {S_BEETLE2, 16, 12, BEETLE2}, {S_WISP1, 12, 12, WISP1}, {S_WISP2, 12, 12, WISP2},
    {S_GLOOM1, 24, 24, GLOOM1}, {S_GLOOM2, 24, 24, GLOOM2}, {S_CANARY1, 10, 8, CANARY1},
    {S_CANARY2, 10, 8, CANARY2},
    {S_BOSS_SHUT, 48, 40, BOSS_SHUT}, {S_BOSS_OPEN, 48, 40, BOSS_OPEN}, {S_BOSS_HURT, 48, 40, BOSS_OPEN},
    {S_STONE, 6, 6, STONE}, {S_SHARD, 6, 8, SHARD}, {S_DRIP_FALL, 4, 6, DRIP_FALL}, {S_SPARK, 6, 6, SPARK},
    {S_BOLT, 8, 6, BOLT}, {S_COIN, 6, 6, COIN}, {S_PUFF1, 12, 12, PUFF1}, {S_PUFF2, 12, 12, PUFF2},
    {S_PUFF3, 12, 12, PUFF3}, {S_LANTERN_HUD, 7, 9, LANTERN_HUD}, {S_LANTERN_HUD_OFF, 7, 9, LANTERN_HUD_OFF},
};

void ud_art_load(void) {
    static int loaded;
    if (loaded) return;
    for (int i = 0; i < ARRAY_LEN(ART); i++) {
        const ArtDef *a = &ART[i];
        int len = (int)strlen(a->px);
        if (len != a->w * a->h) {
            fprintf(stderr, "underdelve art %d: expected %d px, got %d\n", a->id, a->w * a->h, len);
            /* pad safely */
            char *tmp = (char *)calloc((size_t)(a->w * a->h + 1), 1);
            memset(tmp, '.', (size_t)(a->w * a->h));
            memcpy(tmp, a->px, (size_t)(len < a->w * a->h ? len : a->w * a->h));
            spr_make(&ud_spr[a->id], a->w, a->h, tmp);
            free(tmp);
        } else {
            spr_make(&ud_spr[a->id], a->w, a->h, a->px);
        }
    }
    loaded = 1;
}
