/* LOST LINKS - every word in the cartridge, all written for UFO 40.
 * Tables of things are in map order (the overworld row by row, then the
 * underground); ln_01_world checks the counts. */
#include "lostlinks.h"

const char *const LNK_ZONE_NAME[LNK_LAYERS][LNK_ZY][LNK_ZX] = {
    {
        {"CLUBHOUSE MOAT", "CLUBHOUSE HALL", "CRAG WEST", "HIGHCROWN", "HIGHCROWN", "CRAG EAST", "HERON FEN", "HERON FEN"},
        {"CLUBHOUSE GARDENS", "CLUBHOUSE GATE", "THE STONE RING", "UPPER LAWN", "UPPER LAWN", "CRAG SLOPES", "HERON FEN", "HERON FEN"},
        {"BRACKENWOOD", "BRACKENWOOD PATH", "WEST MEADOW", "THE COMMONS", "THE COMMONS", "EAST LAWN", "FEN SHORE", "HERON FEN"},
        {"BRACKENWOOD", "BRACKENWOOD EDGE", "WEST MEADOW", "COTTAGE ROW", "LOWER LAWN", "EAST LAWN", "THE SANDSEA", "THE SANDSEA"},
        {"SALT ISLES", "SALT ISLES", "THE BRAMBLES", "MILL LAWN", "LANTERNBY", "THE SANDSEA", "HAWTHORN HALL", "THE SANDSEA"},
        {"SALT ISLES", "SALT ISLES", "THE BEACH", "SOUTH SHORE", "SOUTH SHORE", "THE SANDSEA", "THE SANDSEA", "THE SANDSEA"},
    },
    {
        {"BADGER'S DEN", "THE SANCTUM", "THE CRYPT", "CROWN VAULTS", "CROWN VAULTS", "SOLID ROCK", "TIDE NOTCH", "PEARL GROTTO"},
        {"CLUBHOUSE CELLARS", "CLUBHOUSE CELLARS", "RANGE WELL", "ECHO HALL", "SOLID ROCK", "SOLID ROCK", "SPRING HOLLOW", "THE SLUICE"},
        {"BRACKEN ROOTS", "ROOTCRAWL", "SOLID ROCK", "THE UNDERCROFT", "THE UNDERCROFT", "THE LOOPWAY", "THE BOG DRAIN", "THE SLUICE"},
        {"SOLID ROCK", "BRACKEN ROOTS", "KNOBBLE'S NOOK", "BURROWTON", "KEEPERS' REFUGE", "SOLID ROCK", "SOLID ROCK", "SOLID ROCK"},
        {"THE CRAB HOLE", "SOLID ROCK", "SOLID ROCK", "SOLID ROCK", "THE CRADLE", "THE SAND CELLAR", "THE GRIT VAULT", "SHALE POCKET"},
        {"THE STILL POOL", "THE STILL POOL", "BRINE WELL", "THE SCRAPE", "THE SCRAPE", "SOLID ROCK", "HAWTHORN CELLARS", "THE FUNNEL"},
    },
};

const char *const LNK_PIN_NAME[LNK_PINS] = {
    "THE CRYPT", "SPRING HOLLOW", "ECHO HALL", "ROOTCRAWL", "THE SLUICE",
    "KNOBBLE'S NOOK", "BURROWTON", "THE CRADLE", "THE SAND CELLAR", "THE SCRAPE",
};

const char *const LNK_NPC_NAME[LNK_NPCS] = {
    "LOOKOUT", "STARGAZER", "MOSSY BALL", "COTTAGER", "PROSPECTOR", "LAMPLIGHTER", "PUDDLE", "DUNE WALKER",
    "BEACHCOMBER", "BELL-RINGER", "OASIS KEEPER", "THINKER", "THE MAYOR", "OLD KNOBBLE", "BAKER", "LOOKER",
    "TWIN", "OTHER TWIN", "SANDY BALL", "HERMIT",
};

const char *const LNK_NPC_LINE[LNK_NPCS][2] = {
    {"I WATCH THE HALL FOR THE KEEPERS. NOTHING HAS MOVED IN FORTY YEARS. I'M VERY GOOD AT THIS.",
     "THOSE ORANGE STONES ARE CRACKED RIGHT THROUGH. SOMETHING HARD WOULD GO STRAIGHT IN."},
    {"THE STONES IN THE RING LINE UP WITH NOTHING AT ALL. I CHECK EVERY NIGHT.",
     "THAT FLOWER BY THE RING THROWS YOU SKY-HIGH. HIT IT AT A GOOD LICK."},
    {"IN BRACKENWOOD SOME BUSHES HIDE HOLES, AND SOME HIDE NOTHING BUT A DROP.",
     "IF THE GROUND SWALLOWS YOU, YOU'RE BACK WHERE YOU SWUNG. NO HARM, JUST SHAME."},
    {"THE KEEPERS BUILT THESE COTTAGES. NOBODY HAS LIT A FIRE HERE SINCE.",
     "THE BIG TOWN IS UNDERGROUND NOW: BURROWTON, THROUGH THE HOLES ROUND HERE."},
    {"THE SANDSEA HIDES A GOOD DEAL. MOSTLY MORE SAND.",
     "WITHOUT GOOD TREADS YOU CAN ONLY CHIP OUT OF IT, ONE STROKE AT A TIME."},
    {"WELCOME TO LANTERNBY! YOU CAME UP OUT OF OUR HOLE? THEN YOU'RE ONE OF US NOW.",
     "LOST TRACK? THE SIGNPOST KEEPS COUNT OF WHO'S BEEN FOUND."},
    {"I ROLLED INTO THE POND ONCE. I WAS BACK ON THE BANK BEFORE I KNEW IT.",
     "WATER COSTS YOU NOTHING BUT THE STROKE YOU WASTED GETTING THERE."},
    {"HOLES IN THE SAND AREN'T TRAPS. THEY'RE DOORS.", "THE FUNNEL, DOWN SOUTH, GOES A LONG WAY DOWN."},
    {"FROM SAND YOU CAN CHIP OVER A LITTLE WATER.",
     "ISLAND TO ISLAND, IF YOU HAVE THE STROKES. THE FLOWER ON THE BEACH HELPS."},
    {"I RING THE BELL WHEN A STRAY COMES HOME. MY ARM IS VERY WELL RESTED.",
     "BIRDS COME BACK EVERY TIME YOU GO DOWN A HOLE AND UP AGAIN. SO DO THE BUGS, SADLY."},
    {"THE OASIS HAS A BRIDGE NOW. NOBODY ASKED FOR ONE.",
     "THE MANOR CELLARS KEEP TREADS FOR SAND, THEY SAY: PAST THE SAND CELLAR'S CRACKED STONE."},
    {"BIRDS GIVE US STROKES. SIPPERS TAKE THEM. WHICH ONE LOVES US MORE?",
     "KNOCK A BUG INTO WATER OR DOWN A HOLE AND IT STOPS THINKING ALTOGETHER."},
    {"BURROWTON WELCOMES YOU. PLEASE DON'T ROLL ON THE MOSS, WE EAT THAT.",
     "THE KEEPERS USED TO VISIT. THEN THEY STOPPED. I THINK THEY'RE HIDING SOMEWHERE CLOSE."},
    {"YOU ROLL AND ROLL AND NEVER STOP WHERE YOU MEANT TO.",
     "FAR TO THE SOUTHWEST, UNDER THE STILL POOL, THERE'S A TRICK FOR THAT. THE CLUBHOUSE IS NORTHWEST."},
    {"MOSS BREAD, MOSS CAKE, MOSS SOUP. ASK ME ABOUT THE SPECIALS.", "THE SPECIAL IS MOSS."},
    {"I SAW A WALL IN THE UNDERCROFT THAT WASN'T QUITE A WALL.",
     "HOLD " GLYPH_B " AND LOOK ROUND. THE MIDDLE OF THE VIEW NEVER LIES."},
    {"MY TWIN THINKS WE'RE IDENTICAL.", "WE ARE NOT. I HAVE MORE DIMPLES."},
    {"MY TWIN THINKS WE'RE DIFFERENT.", "WE ARE NOT. I COUNTED."},
    {"THE SAND UP THERE EATS STROKES. I CHIPPED FOR A WEEK.",
     "THE KEEPERS' OLD BUNKER ROOM IS PAST THOSE CRACKED BLOCKS."},
    {"I CAME DOWN HERE FOR SOME PEACE. THEN THE SIPPERS CAME DOWN FOR ME.", "THEY CAN'T SWIM. NOBODY TELL THEM."},
};

const char *const LNK_KEEPER_NAME[LNK_KEEPERS] = {
    "ELDER ROWAN", "MAPLE", "ASH", "WILLOW", "BIRCH, HAZEL'S SON", "OAK", "HOLLY", "ELM",
};

const char *const LNK_KEEPER_LINE[LNK_KEEPERS] = {
    "A WARDEN! I'D KNOW THAT SPARK ANYWHERE. SIT DOWN, IF A BALL CAN SIT. NOBODY FINDS OUR REFUGE.",
    "WE CAME DOWN WHEN THE MOWERS TURNED. WE NEVER WENT BACK UP.",
    "THE MOSS KEEPS US FED. IT TASTES OF NOTHING, WHICH IS BETTER THAN SOME THINGS.",
    "THE SLICERS DIG AND THE SIPPERS DRINK. THE BADGER TELLS THEM WHERE.",
    "MY MOTHER STAYED UP TOP WHEN WE CAME DOWN. SHE SAID SOMEONE HAD TO WAKE THE LAST WARDEN. SO... YOU.",
    "THE STAR PIN WAS OURS. WE BROKE IT IN FOUR SO THE BADGER'S DOOR WOULD STAY SHUT.",
    "SET IT WHOLE IN THE CRYPT AND THE BADGER WILL COME UP TO MEET YOU. BE READY FOR IT.",
    "WHEN IT'S QUIET UP THERE, WE'LL COME HOME. PROMISE US YOU'LL MAKE IT QUIET.",
};

const char *const LNK_STRAY_NAME[LNK_STRAYS] = {
    "SPROCKET", "CLOVER", "DRIFT", "RIVET", "BARNACLE", "GRIT", "PEBBLE", "ACE",
};

const char *const LNK_STRAY_LINE[LNK_STRAYS] = {
    "I CLIMBED UP HERE FOR THE VIEW, AND NOW I SEE IT EVERY DAY. SOUTHWEST, UNDERGROUND, THERE'S A TRICK FOR STOPPING.",
    "I'VE BEEN PRACTISING MY PUTTS ON THIS LAWN ALL ALONE. TWO'S BETTER. LET'S GO.",
    "A FLOWER THREW ME HERE AND FORGOT TO THROW ME BACK. SHALL WE?",
    "I GUARDED THIS SLUICE FOR YEARS. IT TURNS OUT IT CAN GUARD ITSELF.",
    "A CRAB TOOK ME FOR ITS EGG. I DIDN'T CORRECT IT. PLEASE, GET ME OUT.",
    "I'VE BEEN COLLECTING SAND. I HAVE ALL OF IT NOW. I'M DONE.",
    "I WAS WAITING FOR THE TIDE TO GO OUT. IT'S UNDERGROUND. IT DOESN'T.",
    "I CAN SINK A PUTT FROM ANYWHERE. EXCEPT, IT SEEMS, FROM IN HERE.",
};

const char *const LNK_CROW_TAPE[LNK_CROWS] = {
    "TAPE: THE LINKS WERE GREEN FROM THE SEA TO THE SAND. THE KEEPERS MOWED, AND THE MOWERS HUMMED.",
    "TAPE: ONE MOWER WOULD NOT STOP. THEN ALL OF THEM. THEY BECAME SLICERS AND SIPPERS, AND SUPPED ON SPARKS.",
    "TAPE: THE KEEPERS WENT BELOW. THEY DUG A REFUGE IN THE DARK AND LEARNED TO EAT THE MOSS.",
    "TAPE: UNDER THE CLUBHOUSE THEY MADE WARDENS: BALLS WITH A SPARK, TO ROLL WHERE FEET COULD NOT.",
    "TAPE: THE WARDENS ROLLED OUT, SANK THEIR FIRST PUTTS... AND SAT DOWN TO THINK ABOUT WHY.",
    "TAPE: THE BRASS BADGER WOKE UNDER THE HALL. IT DIGS, IT SHOOTS, IT COUNTS EVERY STROKE.",
    "TAPE: THE STAR PIN WAS BROKEN IN FOUR AND HIDDEN, SO THE BADGER'S DOOR WOULD STAY SHUT.",
    "TAPE: HAZEL, LAST KEEPER ON THE LINKS, GAVE HER SPARK TO THE LAST WARDEN, UNDER LANTERNBY.",
    "TAPE: WE SCORECROWS WATCH. WE COUNT. WE TELL THE BADGER. FIVE STROKES, THEN WE FLY.",
    "TAPE: IF THE LAST WARDEN SETS THE STAR PIN, THE BADGER MUST COME UP TO MEET IT.",
};

const char *const LNK_ABILITY_NAME[AB_COUNT] = {"THE HAMMERHEAD", "BACKSPIN", "THE DUNE TREAD", "THE SKIPPER"};
const char *const LNK_ABILITY_LINE[AB_COUNT] = {
    "ROLL INTO CRACKED STONE AND CRASH RIGHT THROUGH IT.",
    "HOLD " GLYPH_A " WHILE ROLLING TO SLOW DOWN, FOR A LITTLE WHILE. HILLS WEAR IT OUT FAST.",
    "ROLL OVER SAND LIKE GRASS. TAP " GLYPH_B " ON SAND TO JUMP.",
    "ROLL ONTO WATER AND SKIM IT. DON'T STOP OR LAND ON IT, AND NO BRAKING THERE.",
};

const char *const LNK_INTRO[] = {
    "A SPARK. A DIMPLE. SOMETHING SMALL AND ROUND WAKES IN THE DARK.",
    "EVERY ROLL IS A STROKE, AND STROKES ARE ALL YOU HAVE.",
    "RUN OUT, AND YOU WAKE AGAIN AT THE LAST PIN YOU TOUCHED.",
    NULL,
};

const char *const LNK_ENDING =
    "THE BRASS BADGER RATTLES, SPARKS AND LIES STILL, AND EVERY SLICER AND SIPPER STOPS WHERE IT IS. "
    "THE LINKS ARE SAFE AGAIN, AND THE KEEPERS CLIMB UP INTO THE SUN.";
const char *const LNK_ENDING_ALL = "EVERYTHING FOUND. THE WARDENS ROLL OUT TOGETHER TO KEEP THE LINKS.";

const char *const LNK_TREE_LINE =
    "A TREE OF A DIFFERENT COLOUR. CARVED IN THE BARK: \"THE GROUNDS CREW WAS HERE. MIND THE DIVOTS.\"";
const char *const LNK_SAUCER_LINE =
    "A SAUCER, NOSE DOWN IN THE SAND. A BALL SITS BESIDE IT, VERY STILL, TRYING HARD TO LOOK LIKE A ROCK.";
const char *const LNK_ALTAR_LINE[3] = {
    "AN ALTAR WITH A STAR-SHAPED SOCKET. IT WANTS FOUR PIECES.",
    "THE SOCKET TAKES THE PIECES YOU CARRY. IT WANTS FOUR.",
    "THE STAR PIN IS WHOLE! THE GATE GRINDS OPEN.",
};
