/* LOST LINKS - every word in the cartridge, all written for UFO 40.
 * Tables of things are in map order (the overworld row by row, then the
 * underground); ll_02_world checks the counts. */
#include "lostlinks.h"

const char *const LNK_ZONE_NAME[LNK_LAYERS][LNK_ZY][LNK_ZX] = {
    {
        {"CLUBHOUSE MOAT", "CLUBHOUSE HALL", "CRAG WEST", "MASHIE PEAK", "MASHIE PEAK", "CRAG EAST", "HERON FEN", "HERON FEN"},
        {"CLUBHOUSE GARDENS", "CLUBHOUSE GATE", "THE OLD RANGE", "NORTH GREEN", "NORTH GREEN", "CRAG SLOPES", "HERON FEN", "HERON FEN"},
        {"ROOTWOOD", "ROOTWOOD TRAIL", "WEST GREEN", "MIDDLE GREENS", "MIDDLE GREENS", "EAST GREEN", "FEN SHORE", "HERON FEN"},
        {"ROOTWOOD", "ROOTWOOD EDGE", "WEST GREEN", "TEETON", "SOUTH GREENS", "EAST GREEN", "THE DUNES", "THE DUNES"},
        {"SALT ISLES", "SALT ISLES", "SOUTH ROUGH", "SOUTH LINKS", "SOUTH LINKS", "THE DUNES", "GIMME MANOR", "THE DUNES"},
        {"SALT ISLES", "SALT ISLES", "THE BEACH", "SOUTH SHORE", "SOUTH SHORE", "THE DUNES", "THE DUNES", "THE DUNES"},
    },
    {
        {"BADGER'S DEN", "THE SANCTUM", "MASHIE DEPTHS", "MASHIE DEPTHS", "MASHIE DEPTHS", "SOLID ROCK", "WATER-WEDGE", "PEARL GROTTO"},
        {"CLUBHOUSE CELLARS", "CLUBHOUSE CELLARS", "SOLID ROCK", "HUSH CAVERN", "SOLID ROCK", "SOLID ROCK", "GURGLE GROTTO", "THE DRAINWAY"},
        {"ROOTWOOD ROOTS", "THE WORMWAY", "SOLID ROCK", "UNDERPUTT", "UNDERPUTT", "THE LOOPWAY", "SOGGY SUMP", "THE DRAINWAY"},
        {"SOLID ROCK", "ROOTWOOD ROOTS", "SAGE'S BURROW", "BURROWTON", "SOLID ROCK", "SOLID ROCK", "SOLID ROCK", "SOLID ROCK"},
        {"THE COVE", "SOLID ROCK", "SOLID ROCK", "SOLID ROCK", "WAKING HOLLOW", "UNDER-BUNKER", "SANDY SUBTERRA", "GRITTY GROTTO"},
        {"STILLWATER SINK", "STILLWATER SINK", "THE OCEAN PIT", "TUMBLE DIP", "TUMBLE DIP", "SOLID ROCK", "MANOR CELLARS", "THE SINKHOLE"},
    },
};

const char *const LNK_PIN_NAME[LNK_PINS] = {
    "CLUBHOUSE HALL", "ROOTWOOD TRAIL", "GURGLE GROTTO", "HUSH CAVERN", "THE DRAINWAY",
    "SAGE'S BURROW", "BURROWTON", "WAKING HOLLOW", "UNDER-BUNKER", "TUMBLE DIP",
};

const char *const LNK_NPC_NAME[LNK_NPCS] = {
    "TIRED BALL", "OLD RANGER", "MOSSY BALL", "PORTER", "PROSPECTOR", "CROSSER",
    "BEACHCOMBER", "OASIS KEEPER", "THINKER", "THE SAGE", "SANDY BALL",
};

const char *const LNK_NPC_LINE[LNK_NPCS][2] = {
    {"ONE STROKE LEFT. I'LL JUST REST HERE A WHILE... A LONG WHILE.",
     "THE HALL IS SEALED WITH CRACKED STONE. SOMETHING HARD WOULD BREAK IT."},
    {"THESE WERE THE KEEPERS' PRACTICE BAYS. THEY HID THINGS UNDER EVERYTHING.",
     "LOOK FOR HOLES. THERE IS ALWAYS SOMETHING UNDER A HOLE."},
    {"CAREFUL IN ROOTWOOD. SOME HOLES HIDE IN THE GRASS.",
     "FALL IN ONE AND YOU'LL SEE THE ROOTS FROM BELOW."},
    {"WELCOME TO TEETON! THE TOWN IS DOWN BELOW, THROUGH THE HOLES.",
     "EVERY HOLE GOES SOMEWHERE. TRY THE ONES ROUND HERE FIRST."},
    {"THE DUNES ARE FULL OF TREASURE. AND SAND. MOSTLY SAND.",
     "WITHOUT GOOD TREADS YOU CAN ONLY CHIP OUT OF IT, ONE STROKE AT A TIME."},
    {"A HOLE IN THE SAND ISN'T A TRAP. IT'S A DOOR.",
     "THE SINKHOLE DOWN SOUTH GOES DEEP. SOMEBODY LIVES DOWN THERE."},
    {"FROM SAND YOU CAN CHIP OVER A LITTLE WATER.",
     "ISLAND TO ISLAND, IF YOU HAVE THE STROKES. THE FAR ONES ARE WORTH IT."},
    {"THE OASIS IS WET. THE SAND ROUND IT IS NOT.",
     "THE MANOR'S CELLAR KEEPS TREADS FOR SAND, THEY SAY. PAST THE BUNKER'S CRACKED STONE."},
    {"LARKS GIVE US STROKES. SLICERS TAKE THEM. WHICH ONE LOVES US MORE?",
     "KNOCK A SLICER INTO WATER, OR DOWN A HOLE, AND IT STOPS THINKING ALTOGETHER."},
    {"YOU ROLL AND ROLL AND NEVER STOP WHERE YOU MEANT TO.",
     "A BALL IN THE STILLWATER SINK, FAR SOUTHWEST, LEARNED TO STOP. THE CLUBHOUSE IS NORTHWEST."},
    {"THE SAND UP THERE EATS STROKES. I CHIPPED FOR DAYS.",
     "THE KEEPERS' OLD BUNKER ROOM IS PAST THOSE CRACKED BLOCKS."},
};

const char *const LNK_STRAY_NAME[LNK_STRAYS] = {
    "SPROCKET", "CLOVER", "DRIFT", "RIVET", "BARNACLE", "GRIT", "PEBBLE", "ACE",
};

const char *const LNK_STRAY_LINE[LNK_STRAYS] = {
    "I THOUGHT I WOKE LAST. I KNEW A BALL THAT COULD STOP DEAD... SOUTHWEST, UNDER THE WATER.",
    "MY BROTHERS ARE IN BURROWTON, UNDER TEETON. I'M COMING WITH YOU!",
    "HOW DID I GET ON THIS ISLAND? NEVER MIND. TAKE ME ALONG!",
    "WE WERE MADE TO GUARD THE LINKS. WE ROLLED OFF AND THOUGHT INSTEAD. LET'S DO BETTER.",
    "AGES! I'VE BEEN DOWN HERE FOR AGES! THANK YOU!",
    "SAND, SAND, SAND. I COULDN'T CHIP MY WAY OUT. LET'S GO.",
    "I NEED TREADS TO REACH MY FRIEND IN THE DUNES... YOU HAVE THEM! LEAD ON.",
    "THE CROWS WATCH ME PRACTISE. LET THEM WATCH US BOTH.",
};

const char *const LNK_CROW_TAPE[LNK_CROWS] = {
    "TAPE: THE LINKS WERE GREEN FROM THE SEA TO THE SAND. THE KEEPERS MOWED, AND THE MOWERS HUMMED.",
    "TAPE: ONE MOWER WOULD NOT STOP. THEN ALL OF THEM. THEY CALLED THEMSELVES SLICERS AND SUPPED ON SPARKS.",
    "TAPE: THE KEEPERS WENT BELOW. THEY DUG TOWNS IN THE DARK AND LEARNED TO EAT THE MOSS.",
    "TAPE: UNDER THE CLUBHOUSE THEY MADE WARDENS: BALLS WITH A SPARK, TO ROLL WHERE FEET COULD NOT.",
    "TAPE: THE WARDENS ROLLED OUT, SANK THEIR FIRST PUTTS... AND SAT DOWN TO THINK ABOUT WHY.",
    "TAPE: THE BRASS BADGER WOKE UNDER THE HALL. IT DIGS, IT SHOOTS, IT COUNTS EVERY STROKE.",
    "TAPE: THE STAR PIN WAS BROKEN IN FOUR AND HIDDEN, SO THE BADGER'S DOOR WOULD STAY SHUT.",
    "TAPE: HAZEL, LAST KEEPER ON THE LINKS, GAVE HER SPARK TO THE LAST WARDEN IN THE HOLLOW.",
    "TAPE: WE SCORECROWS WATCH. WE COUNT. WE TELL THE BADGER. FIVE STROKES, THEN WE FLY.",
    "TAPE: IF THE LAST WARDEN SETS THE STAR PIN, THE BADGER MUST COME UP TO MEET IT.",
};

const char *const LNK_ABILITY_NAME[AB_COUNT] = {"THE HAMMERHEAD", "BACKSPIN", "THE DUNE TREAD", "THE SKIPPER"};
const char *const LNK_ABILITY_LINE[AB_COUNT] = {
    "ROLL HARD INTO CRACKED STONE TO SMASH IT.",
    "PRESS " GLYPH_B " WHILE ROLLING TO STOP DEAD. HILLS WEAR IT DOWN.",
    "ROLL OVER SAND. PRESS " GLYPH_A " WHILE ROLLING TO HOP.",
    "ROLL ONTO WATER AND SKIM IT. DON'T STOP OR LAND ON IT, AND NO BRAKING THERE.",
};

const char *const LNK_INTRO[] = {
    "A SPARK. A DIMPLE. SOMETHING SMALL AND ROUND WAKES IN THE DARK.",
    "EVERY ROLL IS A STROKE, AND STROKES ARE ALL YOU HAVE.",
    "RUN OUT, AND YOU WAKE AGAIN AT THE LAST PIN YOU TOUCHED.",
    NULL,
};

const char *const LNK_ENDING[] = {
    "THE BRASS BADGER RATTLES, SPARKS, AND LIES STILL.",
    "UP IN THE HALL THE STAR PIN SHINES, AND THE LINKS GROW GREEN AGAIN.",
    "ONE BY ONE THE KEEPERS CLIMB OUT OF THE HOLES AND BLINK AT THE SUN.",
    "DIMPLE ROLLS TO A STOP ON THE SOUTH GREEN. FOR ONCE, RIGHT WHERE IT MEANT TO.",
    NULL,
};

const char *const LNK_ENDING_ALL[] = {
    "EVERY IRON, EVERY STRAY, EVERY TAPE, EVERY PIECE.",
    "THE WARDENS ROLL OUT TOGETHER TO KEEP THE LINKS. HAZEL WOULD BE PROUD.",
    NULL,
};

const char *const LNK_TREE_LINE =
    "A TREE OF A DIFFERENT COLOUR. CARVED IN THE BARK: \"THE GROUNDS CREW WAS HERE. MIND THE DIVOTS.\"";
const char *const LNK_SAUCER_LINE =
    "A SAUCER, NOSE DOWN IN THE SAND. A BALL SITS BESIDE IT, VERY STILL, TRYING HARD TO LOOK LIKE A ROCK.";
const char *const LNK_ALTAR_LINE[3] = {
    "AN ALTAR WITH A STAR-SHAPED SOCKET. IT WANTS FOUR PIECES.",
    "THE SOCKET TAKES THE PIECES YOU CARRY. IT WANTS FOUR.",
    "THE STAR PIN IS WHOLE! THE GATE GRINDS OPEN.",
};
