/* HOMESPUN - pixel art, drawn for UFO 40 (palette-letter strings, see
 * gfx.h). Walkers face right or down; the game flips them. Foes are
 * 16 x 16, bosses 24 x 24, Old Burl 32 x 32, icons 8 x 8. */
#include "homespun.h"

typedef struct HsSprDef { int id, w, h; const char *px; } HsSprDef;

static const char SPR_0[] =
    ".....kkkkkk....."
    "....kcccccck...."
    "...kcccccccck..."
    "...kcuuuuuuck..."
    "...kcuwwuuuck..."
    "...kccuuuucck..."
    "....kcccccck...."
    "....krrrrrrk...."
    "...kooorroook..."
    "..khoooooooohk.."
    "..khoaooooaohk.."
    "..kkooooooookk.."
    "...kddddddddk..."
    "...kbbbkkbbbk..."
    "...kbbk..kbbk..."
    "...kkkk..kkkk...";
static const char SPR_1[] =
    ".....kkkkkk....."
    "....kcccccck...."
    "...kcccccccck..."
    "...kcuuuuuuck..."
    "...kcuwwuuuck..."
    "...kccuuuucck..."
    "....kcccccck...."
    "....krrrrrrk...."
    "...kooorroook..."
    "..khoooooooohk.."
    "..khoaooooaohk.."
    "..kkooooooookk.."
    "...kddddddddk..."
    "...kbbbkkbbbk..."
    "...kbbk.kbbk...."
    "...kkk..kkkk....";
static const char SPR_2[] =
    ".....kkkkkk....."
    "....kcccccck...."
    "...kcccccccck..."
    "...kcccccccck..."
    "...kcclllllck..."
    "...kcccccccck..."
    "....kcccccck...."
    "....krrrrrrk...."
    "...kooorroook..."
    "..khoooooooohk.."
    "..khoooooooohk.."
    "..kkooooooookk.."
    "...kddddddddk..."
    "...kbbbkkbbbk..."
    "...kbbk..kbbk..."
    "...kkkk..kkkk...";
static const char SPR_3[] =
    ".....kkkkkk....."
    "....kcccccck...."
    "...kcccccccck..."
    "...kcccccccck..."
    "...kcclllllck..."
    "...kcccccccck..."
    "....kcccccck...."
    "....krrrrrrk...."
    "...kooorroook..."
    "..khoooooooohk.."
    "..khoooooooohk.."
    "..kkooooooookk.."
    "...kddddddddk..."
    "...kbbbkkbbbk..."
    "...kbbk.kbbk...."
    "...kkk..kkkk....";
static const char SPR_4[] =
    "....kkkkkk......"
    "...kcccccck....."
    "..kcccccccck...."
    "..kccccuuuuk...."
    "..kcccuwuuuk...."
    "..kccccuuuck...."
    "...kcccccck....."
    "...krrrrrrk....."
    "..krroooooook..."
    "..koooooohhk...."
    "..koaoooookk...."
    "..kkoooooook...."
    "...kdddddk......"
    "...kbbkbbk......"
    "...kbbkbbk......"
    "...kkk.kkk......";
static const char SPR_5[] =
    "....kkkkkk......"
    "...kcccccck....."
    "..kcccccccck...."
    "..kccccuuuuk...."
    "..kcccuwuuuk...."
    "..kccccuuuck...."
    "...kcccccck....."
    "...krrrrrrk....."
    "..krroooooook..."
    "..koooooohhk...."
    "..koaoooookk...."
    "..kkoooooook...."
    "...kdddddk......"
    "..kbbk.kbbk....."
    "..kbk...kbk....."
    "..kkk...kkk.....";
static const char SPR_6[] =
    "....kkkkkk......"
    "...kcccccck....."
    "..kcccccccck...."
    "..kccccuuuuk...."
    "..kcccuwuuuk...."
    "..kccccuuuck...."
    "...kcccccck....."
    "...krrrrrrk....."
    "..krroooooookkk."
    "..kooooookhhhhk."
    "..koaooooookkk.."
    "..kkoooooook...."
    "...kdddddk......"
    "...kbbkbbk......"
    "..kbbk.kbbk....."
    "..kkk..kkkk.....";
static const char SPR_7[] =
    "................"
    "................"
    ".......ll......."
    "....lggll......."
    "....lg..gll....."
    "....g.ll..gl...."
    "....gl.ggl.l...."
    "...l.g..g.gl...."
    ".....lg.ll.g...."
    "......gg..gl...."
    "......lgggl....."
    ".......ll..l...."
    ".......l.gl....."
    "........gl......"
    "........l......."
    "................";
static const char SPR_8[] =
    "................"
    "................"
    "................"
    "................"
    "......kkkk......"
    ".....kKKKKk....."
    "....kKwKKwKk...."
    "....kKkKKkKk...."
    "....kKKKKKKk...."
    "....kKKrrKKk...."
    ".....kKKKKk....."
    "......kKKk......"
    "...eeekKKkeee..."
    "...eebeeeeebe..."
    "...beeebbeeeb..."
    "....bbbbbbbb....";
static const char SPR_9[] =
    "................"
    "................"
    "......kkkk......"
    ".....kqqqqk....."
    "....kqqqqqqk...."
    "...kqwkqqqqqk..."
    "..kqkkqqqqqqk..."
    "...kqqqqqqqqk..."
    "...krrrrqqqqk..."
    "...kqqqqqqqk...."
    "...kqqqqqqk....."
    "....kqqqqk.kk..."
    ".....kkkk.kqk..."
    "..BBuBBBBuBBBB.."
    "..uBBBBuBBBBuB.."
    "................";
static const char SPR_10[] =
    "................"
    "................"
    "................"
    ".....k....k....."
    "......k..k......"
    "....k.kkkk.k...."
    "....kpppppk....."
    "...kkpwpwppkk..."
    "....kppppppk...."
    "...kkppppppkk..."
    "....kkpppkkk...."
    "...k.k.kk.k.k..."
    "...k..k..k..k..."
    "....k......k...."
    "................"
    "................";
static const char SPR_11[] =
    "................"
    "..........kk...."
    ".........kak...."
    "........kaak...."
    ".........kak...."
    ".........kak...."
    "........kaak...."
    ".kk..kaaak..kk.."
    ".kak.kaaaak.kak."
    "..kkkaaaaaakkk.."
    "....kawaawak...."
    "....kaaaaaak...."
    "...k.kaaaak.k..."
    "..k..k.kk.k..k.."
    "................"
    "................";
static const char SPR_12[] =
    "................"
    "................"
    "....II....II...."
    "....IlI..IlI...."
    "....IllIIllI...."
    ".....IllllI....."
    "......kkkk......"
    "....kiiiiik....."
    "...kiwkiwkik...."
    "...kiiiiiiik...."
    "....kiiiiik....."
    ".....kikik......"
    "......k.k......."
    "................"
    "................"
    "................";
static const char SPR_13[] =
    "................"
    ".....PP..PP....."
    "...PKKP.PKKP...."
    "...PKKPPPKKP...."
    "....PPkkkkPP...."
    "..PPPkyyyykPPP.."
    "..PKPkykkykPKP.."
    "..PPPkyrrykPPP.."
    "....PPkkkkPP...."
    "...PKKP..PKKP..."
    "...PP..zz..PP..."
    ".......zz......."
    "....zz.zz.zz...."
    ".....zzzzzz....."
    "......ffff......"
    "................";
static const char SPR_14[] =
    "................"
    "..w..........w.."
    "..wk........kw.."
    "...kkkkkkkkkk..."
    "..kbbbbbbbbbbk.."
    "..kbbwkbbwkbbk.."
    "..kbbkkbbkkbbk.."
    "..kbbbbbbbbbbk.."
    "..kbbwwwwwwbbk.."
    "..kbbbkkkkbbbk.."
    "..hkbbbbbbbbkh.."
    "..hkbbbbbbbbkh.."
    "...kbbbbbbbbk..."
    "...kbbk..kbbk..."
    "...kkkk..kkkk..."
    "................";
static const char SPR_15[] =
    "................"
    ".......kkk......"
    "......kkkkr....."
    "......kkkk.o...."
    "..kkkk..kk......"
    ".ktttk.........."
    "kttwtwk........."
    "ktttttk........."
    "kttrrtk........."
    ".kttttk........."
    "kttttttk........"
    "khttttthk......."
    "kttttttk........"
    ".ktkktk........."
    ".kk..kk........."
    "................";
static const char SPR_16[] =
    "................"
    "................"
    "....k......k...."
    ".....k.kk.k....."
    "......kkkk......"
    "....kBBBBBBk...."
    "...kBuBBBBuBk..."
    "...kBBBBBBBBk..."
    "...kBBBkkBBBk..."
    "...kBBBkkBBBk..."
    "...kBuBBBBuBk..."
    "....kBBBBBBk...."
    "...k.kkkkkk.k..."
    "...k..k..k..k..."
    "................"
    "................";
static const char SPR_17[] =
    "................"
    "................"
    "................"
    ".......kk......."
    "......kCCk......"
    "......kCCk......"
    ".....kCICCk....."
    "....kCIICCk....."
    "....kCCCCCCk...."
    "...kCwkCwkCk...."
    "...kCkkCkkCk...."
    "...kCCCCCCCk...."
    "....kCCCCCCk...."
    ".....kkkkkk....."
    "................"
    "................";
static const char SPR_18[] =
    "................"
    "..kk........kk.."
    "..kok......kok.."
    "..kook....kook.."
    "...kok.ww.kok..."
    "....k.kwk.k....."
    "....kkkkkkk....."
    "...kooooooook..."
    ".kooowoowooook.."
    ".kooookkoooook.."
    "..kooooooooook.."
    "...kooooooook..."
    "..k.k.kkkk.k.k.."
    "..k..k....k..k.."
    "................"
    "................";
static const char SPR_19[] =
    "................"
    "..kk........kk.."
    "..krk......krk.."
    "..krrk....krrk.."
    "...krk.ww.krk..."
    "....k.kwk.k....."
    "....kkkkkkk....."
    "...krrrrrrrrk..."
    "..krrrwrrwrrrk.."
    "..krrrrkkrrrrk.."
    "..krrrrrrrrrrk.."
    "...krrrrrrrrk..."
    "..k.k.kkkk.k.k.."
    "..k..k....k..k.."
    "................"
    "................";
static const char SPR_20[] =
    "................"
    "................"
    "......kkkk......"
    "....kkjjjjkk...."
    "...kjjijjjjjk..."
    "...kjiijjjjjk..."
    "..kjjjjjjjjjjk.."
    "..kjwkjjjjwkjk.."
    "..kjkkjjjjkkjk.."
    "..kjjjjjjjjjjk.."
    "..kjjjfffjjjjk.."
    ".kjjjjjjjjjjjk.."
    "...kjjjjjjjjk..."
    "..kjjkjjjjkjjk.."
    "..kkk.kkkk.kkk.."
    "................";
static const char SPR_21[] =
    "................"
    "......kkkk......"
    "....kkrrrrkk...."
    "...krrwwrrrrk..."
    "..krrrwwrrwwrk.."
    "..krwrrrrrwwrk.."
    "..krwwrrwrrrrk.."
    "..kkkkkkkkkkkk.."
    ".....kcccck....."
    ".....kckkck....."
    ".....kcccck....."
    ".....kccccck...."
    "....kcccccck...."
    "....kkkkkkkk...."
    "................"
    "................";
static const char SPR_22[] =
    "................"
    "................"
    ".kkkk..........."
    "kiiiik.........."
    "kikiwk.........."
    "kiiiiik........."
    ".kkiirr........."
    "...kiik........."
    "..kiik.........."
    ".kiik..kkkk....."
    "kiik..kiiiik...."
    "kiikkkiikkiik..."
    "kiiiiiiik.kk...."
    ".kkkkkkk........"
    "................"
    "................";
static const char SPR_23[] =
    "..k..........k.."
    "...k........k..."
    "....k.kkkk.k...."
    "..k..kVVVVk..k.."
    "...kkVVVVVVkk..."
    "....kVwVVwVk...."
    "..kkVVkVVkVVkk.."
    "....kVVVVVVk...."
    "...kkVVpPpVkk..."
    "..k.kVVpppVk.k.."
    "....kVVVVVVk...."
    "...k.kVVVVk.k..."
    "..k...kkkk...k.."
    "...k........k..."
    "................"
    "................";
static const char SPR_24[] =
    "................"
    "..........kk...."
    ".........kgk...."
    "........kggk...."
    "...kkkkkggkkkk.."
    "..kssssggssssk.."
    "..ksssswwsssk..."
    "..kssssssssssk.."
    "..kkkkkkkkkkkk.."
    "..kgdgdgdgdgdk.."
    "..kdgdgdgdgdgk.."
    "..kkkkkkkkkkkk.."
    "................"
    "................"
    "................"
    "................";
static const char SPR_25[] =
    "................"
    "................"
    "................"
    "....k.k..k.k...."
    ".....kkkkkk....."
    "....kmmmmmmk...."
    "...kmvmmvmmk...."
    "...kmmmmmmmmk..."
    "...kmwkmmwkmk..."
    "...kmkkmmkkmk..."
    "...kmmmmmmmmk..."
    "....kmmmmmmk...."
    "...k.kkkkkk.k..."
    "...k........k..."
    "................"
    "................";
static const char SPR_26[] =
    "........................"
    "........y..y..y........."
    ".......yayyayyay........"
    ".......yyyyyyyyy........"
    "......kkkkkkkkkkkk......"
    "...w.kbbbbbbbbbbbbk.w..."
    "...wkbbbbbbbbbbbbbbkw..."
    "...kbbbwwkbbbbwwkbbk...."
    "..kbbbbwkkbbbbwkkbbbk..."
    "..kbbbbbbbbbbbbbbbbbk..."
    "..kbbbbwwwwwwwwwbbbbk..."
    "..kbbbbwkwkwkwkwbbbbk..."
    "..kbbbbbkkkkkkkbbbbbk..."
    "..hhkbbbbbbbbbbbbbkhh..."
    "..hhkbbbbbbbbbbbbbkhh..."
    "..hhkbbbbbbbbbbbbbkhh..."
    "...kbbbbbbbbbbbbbbbk...."
    "...kbbbbbbbbbbbbbbbk...."
    "....kbbbbk....kbbbbk...."
    "....kbbbbk....kbbbbk...."
    "....kbbbbk....kbbbbk...."
    "...kkkkkkk....kkkkkkk..."
    "........................"
    "........................";
static const char SPR_27[] =
    "......z.........z......."
    ".......zz..PP..zz......."
    "........zPPKKPPz........"
    "......PPPKKKKKKPPP......"
    ".....PKKPPPPPPPPKKP....."
    "....PKKPkkkkkkkkPKKP...."
    "....PKPkyyyyyyyykPKP...."
    "....PPkyyykyykyyykPP...."
    "....zPkyyyyyyyyyykPz...."
    "....zPkyrrrrrrrrykPz...."
    "....zPkyrkrkrkrrykPz...."
    "....PPkyyyyyyyyyykPP...."
    "....PKPkyyyyyyyykPKP...."
    "....PKKPkkkkkkkkPKKP...."
    ".....PKKPPPPPPPPKKP....."
    "......PPPKKzzKKPPP......"
    "........z.zzzz.z........"
    "......zz..zzzz..zz......"
    ".....z..zzzzzzzz..z....."
    "....z.....ffff.....z...."
    "........ffffffff........"
    ".......ffeeeeeeff......."
    "......eeeeeeeeeeee......"
    "........................";
static const char SPR_28[] =
    "........................"
    ".....II.........II......"
    "....IlII.......IIlI....."
    "...IllllI.....IlllllI..."
    "...IlllllI...IlllllI...."
    "....IllllIkkkIllllI....."
    ".....IIIIkyyykIIII......"
    ".........kykykk........."
    ".......kyywyywyk........"
    ".......kykkykkyk........"
    ".......kyyyyyyyk........"
    ".........kkrrkk........."
    ".......kyyyyyyyk........"
    "......kkkkkkkkkkk......."
    "......kyyyyyyyyyk......."
    "......kkkkkkkkkkk......."
    ".......kyyyyyyyk........"
    ".......kkkkkkkkk........"
    "........kyyyyyk........."
    ".........kkkkk.........."
    "..........kak..........."
    "...........k............"
    "........................"
    "........................";
static const char SPR_29[] =
    "........................"
    "......uu....uu.........."
    ".....uCu...uCu.........."
    "......kk..kk............"
    "....kkkkkkkkkkkk........"
    "...ksssssssssssk........"
    "..kssgggsssgggsk........"
    ".ksssgyksssgykssk......."
    ".kssssssssssssssk......."
    "kksssssssssssssssk......"
    "kgsssssssssssssssk......"
    "kgwwsssssssssssssk......"
    "kgkkssssddddssssk......."
    "kgwwssssdCCdssssk......."
    "kkssssssdCCdssssk......."
    ".kssssssddddsssk........"
    ".kssssssssssssssk......."
    "..kkkkkkkkkkkkkk........"
    "..kgdk.kgdk.kgdk........"
    "..kdgk.kdgk.kdgk........"
    "..kkkk.kkkk.kkkk........"
    "........................"
    "........................"
    "........................";
static const char SPR_30[] =
    "k......................k"
    ".k....................k."
    "..k.......kkkk.......k.."
    "...k....kkVVVVkk....k..."
    "k...k..kVVVVVVVVk..k...k"
    ".k...kkVVwVVVVwVVkk...k."
    "..kkkkVVkkVVVVkkVVkkkk.."
    "......kVVVVVVVVVVk......"
    "kkkkkkVVVrrrrrrVVVkkkkkk"
    "......kVVrkkkkrVVk......"
    "....kkkVVVVVVVVVVkkk...."
    "...k..kVVVVIIVVVVk..k..."
    "..k...kVVVIIIIVVVk...k.."
    ".k....kVVVVIIVVVVk....k."
    "k......kVVVVVVVVk......k"
    ".......kkVVVVVVkk......."
    "........kkkkkkkk........"
    "........................"
    "........................"
    "........................"
    "........................"
    "........................"
    "........................"
    "........................";
static const char SPR_31[] =
    "........................"
    "......kkkkkkkkkkkk......"
    "....kkppppppppppppkk...."
    "...kpppppppppppppppk...."
    "..kppwwkpppppppwwkppk..."
    "..kppwkkpppppppwkkppk..."
    ".kppppppppppppppppppppk."
    ".kppkkkkkkkkkkkkkkkkppk."
    "kppkwkwkwkwkwkwkwkwkppk."
    "kppkrrrrrrrrrrrrrrrkppk."
    "kppkrrrrrrrrrrrrrrrkppk."
    "kppkwkwkwkwkwkwkwkwkppk."
    ".kppkkkkkkkkkkkkkkkkpk.."
    ".kpppppppppppppppppppk.."
    "...kppppppVVVVVpppppk..."
    "...kppppVVVVVVVppppk...."
    ".....kkppppppppppkk....."
    "...kpk.kkkkkkkkkk.kpk..."
    "...kpk............kpk..."
    "...kkk............kkk..."
    "........................"
    "........................"
    "........................"
    "........................";
static const char SPR_32[] =
    ".....kkkkkk....."
    "....kcccccck...."
    "...kcccccccck..."
    "...kcuuuuuuck..."
    "...kcuwwuuuck..."
    "...kccuuuucck..."
    "....kcccccck...."
    "....kyyyyyyk...."
    "...kBBByyBBBk..."
    "..khBBBBBBBBhk.."
    "..khBaBBBBaBhk.."
    "..kkBBBBBBBBkk.."
    "...kddddddddk..."
    "...kbbbkkbbbk..."
    "...kbbk..kbbk..."
    "...kkkk..kkkk...";
static const char SPR_33[] =
    "....kkkkkkkk...."
    "...kPPPPPPPPk..."
    "..kPPPyyPPPPk..."
    "..kkkkkkkkkkkk.."
    "....khhhhhhk...."
    "....khwhhwhk...."
    "....khhhhhhk...."
    "....khhrrhhk...."
    ".....kkkkkk....."
    "....kPPPPPPk...."
    "...kPPKPPKPPk..."
    "..kPPPPPPPPPk..."
    "..kPPKPPPKPPk..."
    "..kPPPPPPPPPPk.."
    "..kPPPPPPPPPPk.."
    "..kkkkkkkkkkkk..";
static const char SPR_34[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "......kkkk......"
    ".....kBBBBk....."
    "....kBBBBBBk...."
    "...kBwkBwkBk...."
    "...kBkkBkkBk...."
    "...kBBBBBBBk...."
    "...kBBBKKBBk...."
    "....kBBBBBBk...."
    "......kBBBBk...."
    "......kk..kk...."
    "................";
static const char SPR_35[] =
    "................"
    "................"
    ".....k....k....."
    "....kok..kok...."
    "...koookkoook..."
    ".koooooooooook.."
    ".kooowooowoook.."
    ".koookoookoook.."
    ".koooooooooook.."
    ".koooorrroooook."
    "..koooooooook..."
    "..kooooooooook.."
    "...koooooook...."
    "...kook.kook...."
    "...kkk...kkk...."
    "................";
static const char SPR_36[] =
    "........kkkk...."
    "......kggggk...."
    ".....kgggggk...."
    ".....khwhwhk...."
    ".....khhhhhk...."
    ".....kgggggk...."
    "......kggggk...."
    "....kgggggggk..."
    "..kgggggggggk..."
    "..kgggggggggk..."
    "..kgggggggggk..."
    "....kkkkkkkk...."
    "................"
    "................"
    "................"
    "................";
static const char SPR_37[] =
    "...w............"
    "...w...kkkk....."
    "...w..ktttk....."
    "...w.ktttttk...."
    "...wkttwtwtk...."
    "...wktttttk....."
    "..hhkttrttk....."
    "..hkkkkkkkk....."
    "...kssssssk....."
    "...ksssssssk...."
    "...khsssssk....."
    "...ksssssk......"
    "...kbbkbbk......"
    "...kbbkbbk......"
    "...kkk.kkk......"
    "................";
static const char SPR_38[] =
    ".....kkkkkk....."
    "....kwwwwwwk...."
    "....kkkkkkkk...."
    "....khhhhhhk...."
    "....khwhhwhk...."
    "....khhhhhhk...."
    "....khhmmhhk...."
    ".....kkkkkk....."
    "....kwwwwwwk...."
    "...khwwwwwwhk..."
    "...khwwrwwwhk..."
    "...kkwwwwwwkk..."
    "....kwwwwwwk...."
    "....kbbkkbbk...."
    "....kkk..kkk...."
    "................";
static const char SPR_39[] =
    ".....kkkkk......"
    "....kgggggk....."
    "...kgggggggk...."
    "...khhhhhhhk...."
    "...kkhhkkhhk...."
    "...kIwkkIwkk...."
    "...khhhhhhhk...."
    "....khhhhhk....."
    ".....kkkkk......"
    "....klllllllk..."
    "..khlllllllhk..."
    "...khlBllllhk..."
    "..kklllllllkk..."
    "....klllllllk..."
    "....kbbk.kbbk..."
    "....kkk..kkk....";
static const char SPR_40[] =
    "................"
    "................"
    "................"
    "................"
    "......kkkk......"
    ".....kjjjjk....."
    "....kjjwjwjk...."
    "....kjjjjjjk...."
    ".....kjjjjk....."
    "......kkkk......"
    ".....kaaaak....."
    "....kjkaakjk...."
    ".....kaaaak....."
    ".....kjkkjk....."
    ".....kk..kk....."
    "................";
static const char SPR_41[] =
    "....z..z..z....."
    "...zi.zi.zi.z..."
    "..zi.zi.zi.zi..."
    "..zizzizzizzi..."
    "..zzwkzzzwkzz..."
    "..zzkkzzzkkzz..."
    "..zzzzzzzzzzz..."
    "..zzzkkkkkzzz..."
    "..zizzzzzzziz..."
    "..zzizzzzzizz..."
    "..zizzizzizzi..."
    "...zi.zi.zi.z..."
    "..zi.zi.zi.zi..."
    "..z..z..z..z...."
    "...z..z..z..z..."
    "................";
static const char SPR_42[] =
    "................................"
    "..........zzzzzzzzzzz..........."
    "........zzziiizzzzzzzzz........."
    ".......zziiiizzzzzzzzzzzz......."
    "......zziiizzzzzzzfzzzzzzz......"
    ".....zzzizzzzzfzzzzzzzzfzzz....."
    "....zzzzzzzzzzzzzzzzzzzzzzzz...."
    "....zzzfzzzzzzzzzzzzzzzzzfzz...."
    "....zzzzzzzzzzzzzzzfzzzzzzzz...."
    ".....zzzzzzfzzzzzzzzzzzzzzz....."
    "......zzzzzzzzzzzzzzzzzzzz......"
    ".......zzzfzzzzzzzzzzfzzz......."
    "........zzzzbbbbbbzzzzz........."
    "..........kbbbbbbbbbk..........."
    "..........kbbwkbbwkbk..........."
    "..........kbbkkbbkkbk..........."
    "..........kbbbbbbbbbk..........."
    "..........kbbbbbbbbbk..........."
    "..........kbbkbbbbkbk..........."
    "..........kbbbkkkkbbk..........."
    "..........kbbbbbbbbbk..........."
    "..........kbebbbbbebk..........."
    "..........kbbbbbbbbbk..........."
    ".........kbbbbbbbbbbbk.........."
    "........kbbbbebbbbbbbbk........."
    ".......kbbbbbkbbbbkbbbbk........"
    "......kbbbkk..kbbk..kkbbbk......"
    "......kkk.....kkkk.....kkk......"
    "................................"
    "................................"
    "................................"
    "................................";
static const char SPR_43[] =
    "...kk..."
    "..kCCk.."
    ".kCICk.."
    ".kCIICk."
    ".kCCCCk."
    "..kCCk.."
    "...kk..."
    "........";
static const char SPR_44[] =
    "........"
    "........"
    ".kkkkkk."
    "kyyyyyak"
    "kaaaaaak"
    "kkkkkkkk"
    "........"
    "........";
static const char SPR_45[] =
    "........"
    "...kk..."
    "..kbbk.."
    "..kbbk.."
    "...kbbk."
    "...kbbk."
    ".....kk."
    "........";
static const char SPR_46[] =
    "........"
    "..kkkk.."
    ".kyyyyk."
    ".kyakyk."
    ".kyakyk."
    ".kyyyyk."
    "..kkkk.."
    "........";
static const char SPR_47[] =
    "........"
    ".kkkkkk."
    ".kIIIIk."
    ".kBBBIk."
    ".kIIIIk."
    ".kBBIIk."
    ".kkkkkk."
    "........";
static const char SPR_48[] =
    "........"
    ".kkkkkk."
    "..kwwk.."
    "..kwlk.."
    "..kwwk.."
    "..klwk.."
    ".kkkkkk."
    "........";
static const char SPR_49[] =
    "...kk..."
    "...kk..."
    "..kwwk.."
    ".krrrrk."
    ".krwrrk."
    ".krrrrk."
    "..kkkk.."
    "........";
static const char SPR_50[] =
    "..kkkk.."
    ".kwwwwk."
    ".kryrrk."
    ".kyyyrk."
    ".kryrrk."
    ".krrrrk."
    "..kkkk.."
    "........";
static const char SPR_51[] =
    ".k.kk.k."
    "..kggk.."
    "kggkggk."
    "kgk.kgk."
    "kgk.kgk."
    "kggkggk."
    "..kggk.."
    ".k.kk.k.";
static const char SPR_52[] =
    "..kkkk.."
    ".koook.."
    "koaoook."
    "koooook."
    "kkkoook."
    "..koook."
    "...kkkk."
    "........";
static const char SPR_53[] =
    "..kkkk.."
    ".kyyyyk."
    ".kykyky."
    ".kyyyyk."
    ".kkyykk."
    ".kyykyk."
    "..kyyk.."
    "..kkkk..";
static const char SPR_54[] =
    "........"
    "kkkk...."
    "ksssk..."
    "kssssk.."
    ".kkkssk."
    "...kssk."
    "...kbbk."
    "....kk..";
static const char SPR_55[] =
    "..kkkk.."
    ".krrrrk."
    ".krwrrk."
    ".kkkkkk."
    ".krrrrk."
    ".krrrrk."
    "..kkkk.."
    "........";
static const char SPR_56[] =
    "........"
    "kkkkkkkk"
    "kwkwwkwk"
    "kwwkkwwk"
    "kwwwwwwk"
    "kwwwwwwk"
    "kkkkkkkk"
    "........";

const void *hs_sprite_table(int *n);
static const HsSprDef DEFS[] = {
    {HS_WICK_D0, 16, 16, SPR_0},
    {HS_WICK_D1, 16, 16, SPR_1},
    {HS_WICK_U0, 16, 16, SPR_2},
    {HS_WICK_U1, 16, 16, SPR_3},
    {HS_WICK_S0, 16, 16, SPR_4},
    {HS_WICK_S1, 16, 16, SPR_5},
    {HS_WICK_THROW, 16, 16, SPR_6},
    {HS_FOE0+E_SPINNER, 16, 16, SPR_7},
    {HS_FOE0+E_GRUBLET, 16, 16, SPR_8},
    {HS_FOE0+E_SPLOSH, 16, 16, SPR_9},
    {HS_FOE0+E_SKITTER, 16, 16, SPR_10},
    {HS_FOE0+E_STINGLE, 16, 16, SPR_11},
    {HS_FOE0+E_GNATTER, 16, 16, SPR_12},
    {HS_FOE0+E_SPITBLOOM, 16, 16, SPR_13},
    {HS_FOE0+E_GRUMMLE, 16, 16, SPR_14},
    {HS_FOE0+E_LOBBER, 16, 16, SPR_15},
    {HS_FOE0+E_SHELLBACK, 16, 16, SPR_16},
    {HS_FOE0+E_DRIPLET, 16, 16, SPR_17},
    {HS_FOE0+E_CLACKER, 16, 16, SPR_18},
    {HS_FOE0+E_REDCLACKER, 16, 16, SPR_19},
    {HS_FOE0+E_OOZER, 16, 16, SPR_20},
    {HS_FOE0+E_PUFFCAP, 16, 16, SPR_21},
    {HS_FOE0+E_ZIPSNAKE, 16, 16, SPR_22},
    {HS_FOE0+E_BROODER, 16, 16, SPR_23},
    {HS_FOE0+E_TREADLE, 16, 16, SPR_24},
    {HS_FOE0+E_LEECHLING, 16, 16, SPR_25},
    {HS_FOE0+E_GRUMMKING, 24, 24, SPR_26},
    {HS_FOE0+E_THORNMOTHER, 24, 24, SPR_27},
    {HS_FOE0+E_ZIZZIK, 24, 24, SPR_28},
    {HS_FOE0+E_VOLTHOG, 24, 24, SPR_29},
    {HS_FOE0+E_LOOM, 24, 24, SPR_30},
    {HS_FOE0+E_MAWBO, 24, 24, SPR_31},
    {HS_NPC0+N_KIT, 16, 16, SPR_32},
    {HS_NPC0+N_SHUFFLE, 16, 16, SPR_33},
    {HS_NPC0+N_HUSH, 16, 16, SPR_34},
    {HS_NPC0+N_TANGER, 16, 16, SPR_35},
    {HS_NPC0+N_HERMIT, 16, 16, SPR_36},
    {HS_TOLLY, 16, 16, SPR_37},
    {HS_GRISTLE, 16, 16, SPR_38},
    {HS_ORRERY, 16, 16, SPR_39},
    {HS_HAND, 16, 16, SPR_40},
    {HS_NOODLER, 16, 16, SPR_41},
    {HS_BURL, 32, 32, SPR_42},
    {HS_ICON0+IT_GLINT, 8, 8, SPR_43},
    {HS_ICON0+IT_BAR, 8, 8, SPR_44},
    {HS_ICON0+IT_JERKY, 8, 8, SPR_45},
    {HS_ICON0+IT_ODD, 8, 8, SPR_46},
    {HS_ICON0+IT_DATA, 8, 8, SPR_47},
    {HS_ICON0+IT_THREAD, 8, 8, SPR_48},
    {HS_ICON0+IT_TONIC, 8, 8, SPR_49},
    {HS_ICON0+IT_BIGTONIC, 8, 8, SPR_50},
    {HS_ICON0+IT_GEAR, 8, 8, SPR_51},
    {HS_ICON0+IT_PART, 8, 8, SPR_52},
    {HS_ICON0+IT_IDOL, 8, 8, SPR_53},
    {HS_ICON_PIPE, 8, 8, SPR_54},
    {HS_ICON_YOYO, 8, 8, SPR_55},
    {HS_ICON_LETTER, 8, 8, SPR_56},
};

const void *hs_sprite_table(int *n) {
    *n = (int)(sizeof DEFS / sizeof DEFS[0]);
    return DEFS;
}
