/* TINTAIL - the fifteen levels of Salt Island, west to east. All original.
 *
 * ground: g grass  s sand  w swamp  r rock  u/d switch grass (wet / dry)
 *         ~ sea  T palm  B boulder  o bush  - | hollow log  H the burrow
 * things: K Twig  F prickly pear  Y hatchling  ^ > v < a toad facing that way
 *         R rain pad  S sun pad
 * storks: "x y beats-per-step MOVES", a loop that ends where it began.
 * Every level is proved escapable with all three collectibles by the solver
 * (tests/tn_10_all_levels.ufs). */
#include "tintail.h"

const TtLevelDef TN_LEVEL_DEFS[TN_LEVELS] = {
    /* 1: learn to change colour */
    {"DRIFTWOOD SHORE",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~~sssss~~BBBBBBBB~~~",
      "~sssssssBBBBBBBBBBB~",
      "~sssssssssssssssssr~",
      "~sssssssBBBBBBBsBBB~",
      "~sssss~~gggggggsgTT~",
      "~~sss~~ggggggggggTT~",
      "~~~s~~ggggggggggggH~",
      "~~~~~~~gggggggggg~~~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "....................",
      "....................",
      "..K..........F...<..",
      "....................",
      "..Y.................",
      "....................",
      "............>.......",
      "...............F....",
      "...................."},
     {0}},
    /* 2: swamp pools, two colours in one crossing */
    {"REED POOLS",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~gggggowwwwwwoossss~",
      "~ggggggwwwwwwwsssss~",
      "~ggggowwwwwwwwossss~",
      "~ggggwwwwwwwwwwssss~",
      "~ggggowwwwwwwwosssH~",
      "~ggggggwwwwwwwsssss~",
      "~gggggowwwwwwoossss~",
      "~ggggggrrrrrrrsssss~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      ".........v..........",
      "..K...............v.",
      "....................",
      "..........F.........",
      "....................",
      "..Y.............F...",
      "..........^.........",
      "....................",
      "...................."},
     {0}},
    /* 3: a patchwork creek no colour can cross; the logs can */
    {"HOLLOW LOG CREEK",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~ggggggswBgBswgrrrr~",
      "~gggggg--------rrrr~",
      "~ggggggssssgwsrrrrr~",
      "~ggggggwgw|swgsrrrr~",
      "~ggggggsws|gsgwrrrr~",
      "~ggggggwgw|wswsrrrr~",
      "~ggggggsws|gwgsrrrr~",
      "~ggggggBBBsBBBBrrrH~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "..........v.........",
      "..K.................",
      "....................",
      "..................v.",
      ".....>.........<....",
      ".................F..",
      "....................",
      "..Y.......F.........",
      "...................."},
     {0}},
    /* 4: three watchers and one winding colour path */
    {"THE THREE TOADS",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~sssoooooBgBooooorr~",
      "~sssssggrssrwwrrrrr~",
      "~sssswrsrgwgrsgwrrr~",
      "~sssgrgwrsrswrwswrr~",
      "~ssssgwrswgwrwrgsrr~",
      "~ssssswwrrrrggrrrrH~",
      "~sssooooooooooooorr~",
      "~sssBoooooooooooBrr~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "..........v.........",
      "..........F.........",
      "....................",
      "...>.............<..",
      "....................",
      ".K...........FY.....",
      "....................",
      "....................",
      "...................."},
     {0}},
    /* 5: the first stork; follow it past the toad */
    {"STORK FLATS",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~ggggooooooooooogrr~",
      "~ggggogoosoogooogrr~",
      "~ggggogoosoogooogrr~",
      "~gggsgsgsgsgsgsggrr~",
      "~ggggoosoogowoooorr~",
      "~ggggooooooowwwwwwr~",
      "~ggggooooooowwwwwwH~",
      "~ggggooooooowwwwwwr~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      ".................F..",
      "....................",
      ".........Y..........",
      "...............<....",
      "....................",
      ".K..................",
      "..............>.....",
      "................F...",
      "...................."},
     {"4 4 2 R10L10"}},
    /* 6: a swamp full of wading storks */
    {"MANGROVE DASH",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~sswwwwwowwwwwowwss~",
      "~sswwowwwwwoowwwwss~",
      "~sswwwwwwwssswwwwss~",
      "~ssswwwowwssswwowsH~",
      "~sswwwwwwwwsswwwwss~",
      "~sswwowwwwwwwwowwss~",
      "~sswwwwwowwwwwwwwss~",
      "~sswwwwwwwwowwwwwss~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "......v.............",
      "..............F...v.",
      "....................",
      ".K..........F.......",
      "....................",
      "....................",
      "...........Y........",
      "..............^.....",
      "...................."},
     {"9 1 2 D7U7", "16 8 2 U7D7"}},
    /* 7: boulders cut the sightlines; a stork circles the rocks */
    {"RED ROCK HOLLOW",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~rrrrrrrrrssssrrrrr~",
      "~rrBBrrrrrssssrrrrr~",
      "~rrBBrrrBBBsssrrBBr~",
      "~rrrrrrrBBBrrrrrBBr~",
      "~rrrrsssBBBrrrrrrrr~",
      "~rrBBsssrrrrrrBBrrr~",
      "~rrBBsssrrrrrrBBrrH~",
      "~rrrrsssrrrrrrrrrrr~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      ".....v...F........v.",
      "....................",
      "....................",
      ".K..................",
      "....................",
      "....................",
      "....................",
      "..........Y...>.....",
      "...................."},
     {"7 2 2 R5D5L5U5"}},
    /* 8: storks wade across the ford; cross between them */
    {"THE FORD",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggg~",
      "~ggggsswwwwwwsssggH~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      ".....v......F.......",
      "....................",
      ".K..................",
      "....................",
      "..........Y.........",
      "....................",
      "....................",
      "...............^....",
      "...................."},
     {"6 2 2 R7L7", "13 4 3 L7R7", "6 6 2 R7L7"}},
    /* 9: palms throw shade around the spring */
    {"PALM SPRING",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~sssssTsssssssTssss~",
      "~ssggggggggggggggss~",
      "~sgggTwwwwwwwTgggss~",
      "~sgggwwwwwwwwwwggsH~",
      "~sgggwwwwwwwwwwggss~",
      "~sgggTwwwwwwwTgggss~",
      "~ssggggggggggggggss~",
      "~sssssTsssssssTssss~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "..........v.........",
      "....................",
      "....................",
      ".K...>......F.......",
      "..............<.....",
      "....................",
      "..............Y.....",
      "..........^.......F.",
      "...................."},
     {"4 2 2 R13D5L13U5"}},

    /* 10: the sun pad dries the bank: pick the pear before you press it */
    {"SUNBAKED BANK",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~ssssoogggoosududss~",
      "~sssssugggussduduss~",
      "~ssssoouguoosududss~",
      "~sssssssssssdduduss~",
      "~sssssssssssuududsH~",
      "~sssssssssssoduduss~",
      "~sssssssssssoududss~",
      "~sssssssssssoduduss~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "....................",
      "........F........<..",
      "....................",
      ".K......^........<..",
      "....................",
      "...............F....",
      "...S......Y......<..",
      "....................",
      "...................."},
     {0}},
    /* 11: a thorny serpentine; storks pace its lanes */
    {"THORN PASS",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~ggggggggggggggggoo~",
      "~ggggggsgggggggggro~",
      "~oooooooooooooorrrr~",
      "~rrrrrrrrrrrgrgrgrr~",
      "~rrrrrrrrrrrrgrrrgr~",
      "~rrrroooooooooooooo~",
      "~sssssgsssssssssssH~",
      "~sssssgsgssssssssss~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "....................",
      ".K..................",
      "....................",
      ".................F<.",
      "....................",
      "....................",
      "....................",
      ".>............Y..F..",
      "...................."},
     {"3 1 2 R12L12", "15 4 2 L12R12", "5 8 2 R12L12"}},
    /* 12: a dry gully of straw; the rain pad greens it */
    {"CRACKED GULLY",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~sssssooooooooossss~",
      "~sssssTTTTdTTTTssss~",
      "~ssssssdgdgdgdgssss~",
      "~sssssdgdgdgdgdsssH~",
      "~sssssgdgdgdgdgssss~",
      "~sssssdgdgdgdgdssss~",
      "~sssssTTTTdTTTTssss~",
      "~sssssooooooooossss~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "..................v.",
      "..........v.........",
      "...............<.F..",
      ".K...>..............",
      ".....>....F.........",
      "...............<....",
      "..........^......Y..",
      "..R.................",
      "...................."},
     {0}},
    /* 13: rain and shine: dry, wet, then dry again */
    {"CLOUDBURST",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~sssosoossogoosssoo~",
      "~sssouoossodoosssoo~",
      "~sssusuossdgdossuso~",
      "~ssssusussgdgdsssuH~",
      "~sssususssdgdgssuso~",
      "~sssousussodgdsssuo~",
      "~sssoouossoodossoso~",
      "~sssoosossoogossoso~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      ".....v.....v....v...",
      "....................",
      ".K..................",
      ".....F........Y.....",
      "................F...",
      "...............S....",
      "..S......R..........",
      "......^.....^....^..",
      "...................."},
     {0}},
    /* 14: cliffs, a log chute and storks on the salt flats */
    {"SALT CLIFFS",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~rrrrBrrrsssssBgggH~",
      "~rrrrBr|rssssssgggg~",
      "~rrBBBr|rsssssBgBgg~",
      "~rrrrrr|rssswssgggg~",
      "~BBBrrr|rsswwwsggBg~",
      "~rrrrrr|rssswssgggg~",
      "~rrBBrrrrsssssBgBgg~",
      "~rrrrBBrrsssssBgggg~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      "....................",
      ".K..................",
      "....................",
      ".....v..............",
      "............F.....<.",
      "....................",
      ".Y...............F..",
      "................^...",
      "...................."},
     {"9 1 2 D7U7", "13 8 2 U7D7", "9 3 2 R4L4"}},
    /* 15: the Sun Gate: no fruit, just the way through */
    {"THE SUN GATE",
     {"~~~~~~~~~~~~~~~~~~~~",
      "~ssssswwwwwwBBrrrrr~",
      "~ssssswwwwwwBBrgrgr~",
      "~ssssswwwwswBBrrgrr~",
      "~sssTswwswswBBgrrrg~",
      "~ssssswwwwsw--rgrrH~",
      "~sssTswwswwwBBrrgrr~",
      "~ssssswwswwwBBrgrgr~",
      "~ssssswwswwwBBrrrrr~",
      "~~~~~~~~~~~~~~~~~~~~"},
     {"....................",
      ".................v..",
      "........v...........",
      "....................",
      ".K..................",
      "....................",
      "....................",
      "..........^.........",
      "..................^.",
      "...................."},
     {"7 1 2 D7U7", "9 8 2 U7D7", "16 1 2 D7U7"}},
};
