/* ROOFCAT - pixel art (palette-letter strings, see gfx.h). */
#include "roofcat.h"

Sprite rc_spr[R_SPRITE_COUNT];

/* Harissa, facing right */
static const char CAT_RUN1[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "k.......kozoozok"
    "ok......koooKook"
    ".rk....kkhhkhhk."
    ".okkkkkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kok.kk...kok.."
    ".kok...kok..kok."
    ".kk.....kk...kk."
    "................";
static const char CAT_RUN2[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    ".k......kozoozok"
    "kok.....koooKook"
    "..rk...kkhhkhhk."
    "..okkkkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "...kokkok.kok..."
    "...kk.kok.kk...."
    "......kk........"
    "................";
static const char CAT_RUN3[] =
    "................"
    "................"
    ".........k...k.."
    "........kok.kok."
    "k.......koookook"
    "ok......kozoozok"
    ".rk.....koooKook"
    ".okkkkkkkhhkhhk."
    "..korooroooooBk."
    "..kooroorooBBBk."
    "..koooooooooBuBk"
    "..khhhhhhhhhhBk."
    "...kok.kok.kk..."
    "...kok..kokk...."
    "....kk...kk....."
    "................";
static const char CAT_RUN4[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "........kozoozok"
    ".kk.....koooKook"
    "kork...kkhhkhhk."
    ".kokkkkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kokkok..kok..."
    ".kok..kk...kok.."
    ".kk.........kk.."
    "................";
static const char CAT_JUMP[] =
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "........kozoozok"
    "........koooKook"
    ".......kkhhkhhk."
    "kk...kkoooooook."
    "okkkkoorooooBBk."
    ".kkooroorooBuBk."
    "...koooooooooBk."
    "...khhhhhhhhhk.."
    "....kok..kokk..."
    "...kok....kok..."
    "...kk......kk..."
    "................"
    "................";
static const char CAT_SPIN[] =
    "................"
    "....kkkkkkk....."
    "..kkooorooookk.."
    ".kooroooooroook."
    ".koookkkkkooork."
    "kooookzozkoorook"
    "kororkoKokoooook"
    "koooookkkkkooork"
    "koroooooooooroBk"
    ".koooroooorooBk."
    ".kkooooooooookk."
    "..kkhhhhhhhhkk.."
    "....kkkkkkkk...."
    "................"
    "................"
    "................";
static const char CAT_FALL[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "........kozoozok"
    "........koooKook"
    "..k....kkhhkhhk."
    ".kok.kkoooooook."
    ".kokooroooooBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    ".kok.kk....kok.."
    "kok...kok...kok."
    "kk.....kk....kk."
    "................";
static const char CAT_THROW[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "k.......kozoozok"
    "ok......koooKook"
    ".rk....kkhhkhhkk"
    ".okkkkkooooookhk"
    "..korooroooBBkk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kok.kk...kok.."
    ".kok...kok..kok."
    ".kk.....kk...kk."
    "................";
static const char CAT_SPIRIT1[] =
    "................"
    ".........I...I.."
    "........ICI.ICI."
    "........ICCCICCI"
    "........ICuCCuCI"
    "........ICCCwCCI"
    ".......IICCCCCI."
    "..IIIIICCCCCCCI."
    ".ICCCCCCCCCCCCI."
    ".ICCCCCCCCCCCI.."
    "..ICCCCCCCCCCI.."
    "...IICCCCCCII..."
    ".....ICCCCI....."
    "......ICCI......"
    ".......II......."
    "................";
static const char CAT_SPIRIT2[] =
    "................"
    ".........I...I.."
    "........ICI.ICI."
    "........ICCCICCI"
    "........ICuCCuCI"
    "........ICCCwCCI"
    ".......IICCCCCI."
    "...IIIICCCCCCCI."
    "..ICCCCCCCCCCCI."
    ".ICCCCCCCCCCCCI."
    ".ICCCCCCCCCCCI.."
    "..IICCCCCCCII..."
    "....ICCCCCI....."
    ".....ICCCI......"
    "......III......."
    "................";
static const char CAT_HURT[] =
    "................"
    "..k...k........."
    ".kok.kok........"
    "kookookoo......."
    "kokkookkok......"
    "koookKookk......"
    ".khhkkhhk......."
    ".kooooooookkk..."
    "kBBoooroooorok.."
    "kBuBooroorooook."
    ".kBooooooooooork"
    "..khhhhhhhhhhk.k"
    "..kok..kok..kok."
    "..kk...kk...kk.."
    "................"
    "................";
static const char CAT_IDLE[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    ".k......kozoozok"
    "kok.....koooKook"
    "kok....kkhhkhhk."
    ".kok.kkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kok.kok.kok..."
    "..kok.kok.kok..."
    "..kk..kk..kk...."
    "................";

static const char STAR1[] =
    "...ww..."
    "..wllw.."
    "wwwyywww"
    "wlyaaylw"
    "wlyaaylw"
    "wwwyywww"
    "..wllw.."
    "...ww...";
static const char STAR2[] =
    "w......w"
    "ww..w.ww"
    ".wwyyww."
    "..yaay.w"
    "w.yaay.."
    ".wwyyww."
    "ww.w..ww"
    "w......w";
static const char WISP_SHOT[] =
    "..II.."
    ".ICCI."
    "ICwwCI"
    "ICwwCI"
    ".ICCI."
    "..II..";

/* foes */
static const char PIGEON1[] =
    "................"
    "................"
    "........kkk....."
    ".......kgggk...."
    ".......kgkgak..."
    ".......kggggaa.."
    "..kkkkkkjjjk...."
    ".kgggggjzjgk...."
    "kgllgggggggk...."
    "kgllllgggggk...."
    ".kglllgggkk....."
    "..kkkggggk......"
    "....kkkkk......."
    ".....ok.ok......"
    "....oo..oo......"
    "................";
static const char PIGEON2[] =
    "................"
    "................"
    "................"
    "........kkk....."
    ".......kgggk...."
    ".......kgkgak..."
    "..kkkk.kggggaa.."
    ".kgggkkjjjjk...."
    "kgllgggjzjgk...."
    "kgllllgggggk...."
    ".kglllgggkk....."
    "..kkkggggk......"
    "....kkkkk......."
    "......ok.ok....."
    ".....oo..oo....."
    "................";
static const char GULL1[] =
    "kk..........kk.."
    "kwk........kwk.."
    ".kwk......kwk..."
    "..kwk....kwk...."
    "...kwwkkwwk....."
    "....kwwwwwkkk..."
    ".....kwwwwwwak.."
    "......kkwwwkk..."
    "........kk......"
    "................";
static const char GULL2[] =
    "................"
    "................"
    "................"
    "....kkkkkk......"
    "..kkwwwwwwkkk..."
    ".kwwlwwwwwwwak.."
    "kwwkkkwwwwkkk..."
    "kkk..kwwlk......"
    ".....kwlk......."
    "......kk........";
static const char RAT1[] =
    "................"
    "................"
    "................"
    "................"
    "........kk.kk..."
    ".......kKkkKk..."
    "..kkkkkkggggk..."
    ".kgggggggkgggk.."
    "kgggggggggggKKk."
    "kkgggggggggkkk.."
    "k.kkggggggk....."
    "k...kk.kk.k....."
    ".k..k...k.k....."
    "................"
    "................"
    "................";
static const char RAT2[] =
    "................"
    "................"
    "................"
    "........kk.kk..."
    ".......kKkkKk..."
    "..kkkkkkggggk..."
    ".kgggggggkgggk.."
    "kgggggggggggKKk."
    "kkgggggggggkkk.."
    ".kkkggggggkk...."
    ".k..k....k.k...."
    "k..k......k.k..."
    "................"
    "................"
    "................"
    "................";
static const char SLINGER1[] =
    "................"
    ".....kkkkk......"
    "....ktttttk....."
    "...kthhhhhtk...."
    "...kthkhkhtk...."
    "...kthhhhhtk...."
    "....kthrrhk....."
    ".kk.kkttttk....."
    "kttkktttttk....."
    ".kttttttttk....."
    "...kttttttk....."
    "...kttkkttk....."
    "...ktk..ktk....."
    "..kttk..kttk...."
    "..kkk....kkk...."
    "................";
static const char SLINGER2[] =
    "..kk............"
    ".kssk.kkkkk....."
    ".ksskktttttk...."
    "..kktthhhhhtk..."
    "...ktthkhkhtk..."
    "...kkthhhhhtk..."
    ".....kthrrhk...."
    ".....kkttttk...."
    "....kttttttk...."
    "....kttttttk...."
    "....kttttttk...."
    "....kttkkttk...."
    "....ktk..ktk...."
    "...kttk..kttk..."
    "...kkk....kkk..."
    "................";
static const char MIRAGE1[] =
    "......kkkk......"
    "....kkPPPPkk...."
    "...kPVVVVVVPk..."
    "..kPVwkVVwkVPk.."
    "..kPVkkVVkkVPk.."
    "..kPVVVVVVVVPk.."
    "..kPVVkkkkVVPk.."
    "..kPVVVVVVVVPk.."
    "..kPPVVVVVVPPk.."
    "..kPkPVVVVPkPk.."
    "...k.kPPPPk.k..."
    ".....k.kk.k....."
    "................"
    "................"
    "................"
    "................";
static const char MIRAGE2[] =
    "......kkkk......"
    "....kkPPPPkk...."
    "...kPVVVVVVPk..."
    "..kPVwkVVwkVPk.."
    "..kPVkkVVkkVPk.."
    "..kPVVVVVVVVPk.."
    "..kPVVVkkVVVPk.."
    "..kPVVVVVVVVPk.."
    "..kPPVVVVVVPPk.."
    "...kPkPVVPkPk..."
    "....k.kPPk.k...."
    "......k..k......"
    "................"
    "................"
    "................"
    "................";
static const char BOBBER1[] =
    ".......y........"
    "......yak......."
    ".......k........"
    ".......k........"
    ".....kkkkk......"
    "....krrrrrk....."
    "...krwwrrrrk...."
    "...krwrrrrrk...."
    "...krrrrrrrk...."
    "...kvrrrrrvk...."
    "....kvvvvvk....."
    ".....kkkkk......"
    ".......k........"
    "......kkk......."
    "................"
    "................";
static const char BOBBER2[] =
    "......y.a......."
    ".......yk......."
    ".......k........"
    ".......k........"
    ".....kkkkk......"
    "....krrrrrk....."
    "...krwwrrrrk...."
    "...krwrrrrrk...."
    "...krrrrrrrk...."
    "...kvrrrrrvk...."
    "....kvvvvvk....."
    ".....kkkkk......"
    ".......k........"
    "......kkk......."
    "................"
    "................";
static const char VENT1[] =
    "..kkkkkkkkkkkk.."
    "..kssssssssssk.."
    "..kkkkkkkkkkkk.."
    "...knnnnnnnnk..."
    "...knyknnykkk..."
    "...knnnnnnnnk..."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kkkkkkkkkkk..";
static const char VENT2[] =
    "..kkkkkkkkkkkk.."
    "..kssssssssssk.."
    "..kkkkkkkkkkkk.."
    "...knnnnnnnnk..."
    "...knakknakkk..."
    "...knnnnnnnnk..."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kteetteettk.."
    "...ktttttttttk.."
    "...kkkkkkkkkkk..";
static const char MAGPIE1[] =
    "................"
    "......kkkk......"
    ".....kkkkkk....."
    ".....kkwkkkaa..."
    "..kk.kkkkkk....."
    ".kwwkkkkkkk....."
    "kwwwwkkkNNk....."
    "kkwwwwwkNNk....."
    ".kkkwwwwkkk....."
    "...kkkkkkk......"
    ".....kk.k......."
    "....kk..kk......"
    "................"
    "................"
    "................"
    "................";
static const char MAGPIE2[] =
    "..kk............"
    ".kwwk..kkkk....."
    ".kwwwkkkkkkk...."
    "..kwwkkkwkkkaa.."
    "...kwwkkkkkk...."
    "....kkkkkkkk...."
    "....kkkkkNNk...."
    "....kkwwwNNk...."
    ".....kkwwkkk...."
    "......kkkkk....."
    ".......kk.k....."
    "......kk..kk...."
    "................"
    "................"
    "................"
    "................";

static const char PEBBLE[] = ".kk.kglkksdkk.kk";
static const char SEED[] = ".kk.kaek.kk.";
static const char BUBBLE[] =
    ".kkkk."
    "kwIICk"
    "kICCCk"
    "kCCCuk"
    "kCCuuk"
    ".kkkk.";
static const char BOMB[] =
    "...y..."
    "..yak.."
    "...k..."
    ".kkkkk."
    "kdwddsk"
    "kdddddk"
    "kndddnk"
    ".kkkkk.";
static const char SHARD[] =
    ".kkk."
    "kteek"
    "kttek"
    ".kbk."
    "..k..";

/* pickups */
static const char FISH[] =
    "..kkkk...."
    ".kCCCCkk.k"
    "kCwkCCCCkk"
    "kCCCCCCCuk"
    ".kuuuukk.k"
    "..kkkk....";
static const char DATE[] =
    "...kk..."
    "..kbbk.."
    ".kbttbk."
    ".kbtebk."
    ".kbttbk."
    ".kbbbbk."
    "..kkkk..";
static const char ORANGE_[] =
    "....zk.."
    "..kkjk.."
    ".kooaok."
    "koaaooak"
    "kooooook"
    "kroooork"
    ".krrrrk."
    "..kkkk..";
static const char POMEGRANATE[] =
    "...kk..."
    "..kvvk.."
    ".kvrrvk."
    "kvrKrrvk"
    "kvrrrrvk"
    "kvrrrrvk"
    ".kvvvvk."
    "..kkkk..";
static const char BREAD[] =
    "..kkkkkk.."
    ".keeeeeek."
    "kehheheehk"
    "keeeheeeek"
    "ktteeeettk"
    ".kttttttk."
    "..kkkkkk..";
static const char LETTER[] =
    "kkkkkkkkkk"
    "kcccccccck"
    "kkcccccckk"
    "kckccccckc"
    "kcckrrckck"
    "kcccrrccck"
    "kcccccccck"
    "kkkkkkkkkk";
static const char LANTERN_[] =
    "...kk..."
    "..kkkk.."
    ".kkkkkk."
    "krryyrrk"
    "kryccyrk"
    "krywcyrk"
    "kryccyrk"
    "krryyrrk"
    ".kkkkkk."
    "...kk..."
    "...ak..."
    "..a.a...";
static const char CATNIP[] =
    "...kk..."
    "..kzzk.."
    ".kzizzk."
    "kzzkzizk"
    ".kzzzzk."
    "..kjjk.."
    "...kk..."
    "........";
static const char HEART[] =
    ".kk.kk."
    "kKKkrrk"
    "kKrrrrk"
    ".krrrk."
    "..krk.."
    "...k...";

/* bosses */
static const char BOSS_PIGEON1[] =
    "................................................"
    "................................................"
    "........................kkkkkk.................."
    "......................kkggggggkk................"
    ".....................kggggggggggk..............."
    "....................kggggkkggggggk.............."
    "....................kgggkwrkggggggk............."
    "....................kgggkrrkgggggaaak..........."
    "....................kggggkkggggggaaaaak........."
    "....................kgggggggggggggkaak.........."
    "....................kjjjjgggggggggkkk..........."
    "...........kkkkkkkkkjjjzjjjjjggggk.............."
    ".........kkggggggggjjjzzzjjjjjgggk.............."
    ".......kkgggggggggggjjjzjjjjggggggk............."
    "......kggllllgggggggggjjjgggggggggk............."
    ".....kgllllllllgggggggggggggggggggk............."
    "....kgllllllllllllggggggggggggggggk............."
    "...kgllllllggllllllgggggggggggggggk............."
    "..kglllllllggglllllggggggggggggggk.............."
    ".kgglllllllgggglllllgggggggggggggk.............."
    "kggglllllllgggggllllgggggggggggggk.............."
    "kgggglllllgggggggllggggggggggggggk.............."
    "kkgggggllgggggggggggggggggggggggk..............."
    ".kkggggggggggggggggggggggggggggk................"
    "..kkkgggggggggggggggggggggggggk................."
    "....kkkkggggggggggggggggggkkkk.................."
    "........kkkkkkkkkkkkkkkkkk......................"
    "..............ook....ook........................"
    ".............oook...oook........................"
    "............oo.ok..oo.ok........................"
    "................................................"
    "................................................";
static const char BOSS_PIGEON2[] =
    "................................................"
    "........................kkkkkk.................."
    "......................kkggggggkk................"
    ".....................kggggggggggk..............."
    "....................kggggkkggggggk.............."
    "....................kgggkwrkggggggk............."
    "....................kgggkrrkgggggak............."
    "....................kggggkkggggggaaaak.........."
    "....................kgggggggggggggkaaaak........"
    "....................kjjjjgggggggggkk.k.........."
    "...........kkkkkkkkkjjjzjjjjjggggk.............."
    ".........kkggggggggjjjzzzjjjjjgggk.............."
    ".......kkgggggggggggjjjzjjjjggggggk............."
    "......kggllllgggggggggjjjgggggggggk............."
    ".....kgllllllllgggggggggggggggggggk............."
    "....kgllllllllllllggggggggggggggggk............."
    "...kgllllllggllllllgggggggggggggggk............."
    "..kglllllllggglllllggggggggggggggk.............."
    ".kgglllllllgggglllllgggggggggggggk.............."
    "kggglllllllgggggllllgggggggggggggk.............."
    "kgggglllllgggggggllggggggggggggggk.............."
    "kkgggggllgggggggggggggggggggggggk..............."
    ".kkggggggggggggggggggggggggggggk................"
    "..kkkgggggggggggggggggggggggggk................."
    "....kkkkggggggggggggggggggkkkk.................."
    "........kkkkkkkkkkkkkkkkkk......................"
    "................ook..ook........................"
    "...............oook.oook........................"
    "..............oo.okoo.ok........................"
    "................................................"
    "................................................"
    "................................................";
static const char POT[] =
    "......kkkkkkkkkkkk......"
    ".....keeeeeeeeeeeek....."
    "......kkkkkkkkkkkk......"
    ".......kttttttttk......."
    "......kttteeeetttk......"
    "....kkteeeeeeeeeetkk...."
    "...kteeeehhheeeeeeetk..."
    "..kteeehhhheeeeeeeeetk.."
    "..ktrrrrrrrrrrrrrrrrtk.."
    "..kteeeeeeeeeeeeeeeetk.."
    "..ktecececececececetk..."
    "..kteeeeeeeeeeeeeeeetk.."
    "..ktrrrrrrrrrrrrrrrrtk.."
    "...kteeeeeeeeeeeeeetk..."
    "....kttteeeeeeeettk....."
    ".....kktttttttttkk......"
    ".......kkkkkkkkkk......."
    "........................"
    "........................"
    "........................";
static const char POT_EYES[] =
    "......kkkkkkkkkkkk......"
    ".....keeeeeeeeeeeek....."
    "......kkkkkkkkkkkk......"
    ".......kttttttttk......."
    "......kttteeeetttk......"
    "....kkteeeeeeeeeetkk...."
    "...kteekkkeeeekkkeetk..."
    "..kteekwwkeeeekwwkeetk.."
    "..ktrrkwkkrrrrkwkkrrtk.."
    "..kteekkkeeeeeekkkeetk.."
    "..kteeeeeekkkkeeeeeetk.."
    "..kteeeeekrrrrkeeeeetk.."
    "..ktrrrrrrkkkkrrrrrrtk.."
    "...kteeeeeeeeeeeeeetk..."
    "....kttteeeeeeeettk....."
    ".....kktttttttttkk......"
    ".......kkkkkkkkkk......."
    "........................"
    "........................"
    "........................";
static const char CRAB1[] =
    "..kkk......................kkk.."
    ".krrrk....................krrrk."
    "krkk.rk..................kr.kkrk"
    "krk..rk..................kr..krk"
    ".krrrrk.......kk..kk.....krrrrk."
    "..krrk.......kwk..kwk.....krrk.."
    "...krk.......kkk..kkk.....krk..."
    "...krk.....kkkrrkkrrkkk...krk..."
    "....krk..kkrrrrrrrrrrrrkk.krk..."
    ".....krkkrrorrrrrrrrrorrrkrk...."
    "......krrrrrrrrrrrrrrrrrrrk....."
    ".....krrrorrrrrrrrrrrrrorrrk...."
    ".....krrrrrrrrvvvvvrrrrrrrrk...."
    "......krrrrrvvvvvvvvvrrrrrk....."
    ".......kkrrrrrrrrrrrrrrrkk......"
    ".....kk.kkkkkkkkkkkkkkkk.kk....."
    "....kk..k.k.k......k.k.k..kk...."
    "...k...k..k..k....k..k..k...k..."
    "................................"
    "................................";
static const char CRAB2[] =
    "................................"
    "................................"
    "..kkk......................kkk.."
    ".krrrk....................krrrk."
    "krkk.rk.......kk..kk.....kr.kkrk"
    "krk..rk......kwk..kwk....kr..krk"
    ".krrrrk......kkk..kkk....krrrrk."
    "..krrk.....kkkrrkkrrkkk...krrk.."
    "...krk...kkrrrrrrrrrrrrkk.krk..."
    "....krkkkrrorrrrrrrrrorrrkkrk..."
    "......krrrrrrrrrrrrrrrrrrrk....."
    ".....krrrorrrrrrrrrrrrrorrrk...."
    ".....krrrrrrrrvvvvvrrrrrrrrk...."
    "......krrrrrvvvvvvvvvrrrrrk....."
    ".......kkrrrrrrrrrrrrrrrkk......"
    "......kk.kkkkkkkkkkkkkkk.kk....."
    ".....k..k.k.k......k.k.k..k....."
    "....k..k..k..k....k..k..k..k...."
    "................................"
    "................................";
static const char MKING1[] =
    "........kk..............kk......"
    ".......kyyk....kkkk....kwwk....."
    "......kyayyk..kkkkkk..kwwwwk...."
    "......kkkkkk.kkkwkkkkkwwwwwk...."
    "..kkk..kkkkkkkkkkkkkkwwwwwk....."
    ".kwwwkkkkkkkkkkkkkkkwwwwkk......"
    "kwwwwwkkkkkkkkkkkkkkkkkk........"
    "kwwwwwwkkkkkkNNNNkkkkaaaa......."
    ".kkwwwwwkkkkNNBBNNkkkk.........."
    "...kkwwwwkkkNBBBBNkkk..........."
    ".....kkkkkkkNNBBNNkk............"
    "........kkkkkNNNNkk............."
    "..........kkkkkkkk.............."
    "..........kk.kk.kk.............."
    ".........kk..kk..kk............."
    "................................";
static const char MKING2[] =
    "........kk......................"
    ".......kyyk....kkkk............."
    "......kyayyk..kkkkkk............"
    "......kkkkkk.kkkwkkkk..........."
    ".......kkkkkkkkkkkkkkk.........."
    "......kkkkkkkkkkkkkkkkaaaa......"
    "...kkkkkkkkkkNNNNkkkkk.........."
    "..kwwwwkkkkkNNBBNNkkkkkk........"
    ".kwwwwwwkkkkNBBBBNkkwwwwk......."
    "kwwwwwwkkkkkNNBBNNkkwwwwwk......"
    "kwwwwwkk.kkkkNNNNkk.kwwwwwk....."
    ".kkkkk....kkkkkkkk...kwwwwwk...."
    "..........kk.kk.kk....kkkkk....."
    ".........kk..kk..kk............."
    "................................"
    "................................";
static const char PARCEL[] =
    "..kkkkkkkkkkkk.."
    ".kPPPPPkkPPPPPk."
    ".kPKKPkyykPKKPk."
    "kkkkkkkyykkkkkkk"
    "kttttttyyttttttk"
    "kteeeeeyyeeeeetk"
    "kteeeeeyyeeeeetk"
    "kyyyyyyyyyyyyyyk"
    "kteeeeeyyeeeeetk"
    "kteeeeeyyeeeeetk"
    "kttttttyyttttttk"
    "kkkkkkkkkkkkkkkk";
static const char CAT_HEAD[] =
    "k...k.."
    "kokok.."
    "kooook."
    "kozozk."
    "koKook."
    ".kkkk..";
static const char POW[] =
    "..kk..."
    ".kyak.."
    "kyywak."
    "kawyyk."
    ".kaak.."
    "..kk...";

typedef struct { int id, w, h; const char *px; } Art;
static const Art ART[] = {
    {R_CAT_RUN1, 16, 16, CAT_RUN1}, {R_CAT_RUN2, 16, 16, CAT_RUN2}, {R_CAT_RUN3, 16, 16, CAT_RUN3},
    {R_CAT_RUN4, 16, 16, CAT_RUN4}, {R_CAT_JUMP, 16, 16, CAT_JUMP}, {R_CAT_SPIN, 16, 16, CAT_SPIN},
    {R_CAT_FALL, 16, 16, CAT_FALL}, {R_CAT_THROW, 16, 16, CAT_THROW}, {R_CAT_SPIRIT1, 16, 16, CAT_SPIRIT1},
    {R_CAT_SPIRIT2, 16, 16, CAT_SPIRIT2}, {R_CAT_HURT, 16, 16, CAT_HURT}, {R_CAT_IDLE, 16, 16, CAT_IDLE},
    {R_STAR1, 8, 8, STAR1}, {R_STAR2, 8, 8, STAR2}, {R_WISP_SHOT, 6, 6, WISP_SHOT},
    {R_PIGEON1, 16, 16, PIGEON1}, {R_PIGEON2, 16, 16, PIGEON2}, {R_GULL1, 16, 10, GULL1}, {R_GULL2, 16, 10, GULL2},
    {R_RAT1, 16, 16, RAT1}, {R_RAT2, 16, 16, RAT2}, {R_SLINGER1, 16, 16, SLINGER1}, {R_SLINGER2, 16, 16, SLINGER2},
    {R_MIRAGE1, 16, 16, MIRAGE1}, {R_MIRAGE2, 16, 16, MIRAGE2}, {R_BOBBER1, 16, 16, BOBBER1},
    {R_BOBBER2, 16, 16, BOBBER2}, {R_VENT1, 16, 16, VENT1}, {R_VENT2, 16, 16, VENT2},
    {R_MAGPIE1, 16, 16, MAGPIE1}, {R_MAGPIE2, 16, 16, MAGPIE2},
    {R_PEBBLE, 4, 4, PEBBLE}, {R_SEED, 4, 3, SEED}, {R_BUBBLE, 6, 6, BUBBLE}, {R_BOMB, 7, 8, BOMB},
    {R_SHARD, 5, 5, SHARD},
    {R_FISH, 10, 6, FISH}, {R_DATE, 8, 7, DATE}, {R_ORANGE, 8, 8, ORANGE_}, {R_POMEGRANATE, 8, 8, POMEGRANATE},
    {R_BREAD, 10, 7, BREAD}, {R_LETTER, 10, 8, LETTER}, {R_LANTERN, 8, 12, LANTERN_}, {R_CATNIP, 8, 8, CATNIP},
    {R_HEART, 7, 6, HEART},
    {R_BOSS_PIGEON1, 48, 32, BOSS_PIGEON1}, {R_BOSS_PIGEON2, 48, 32, BOSS_PIGEON2},
    {R_POT, 24, 20, POT}, {R_POT_EYES, 24, 20, POT_EYES}, {R_CRAB1, 32, 20, CRAB1}, {R_CRAB2, 32, 20, CRAB2},
    {R_MKING1, 32, 16, MKING1}, {R_MKING2, 32, 16, MKING2},
    {R_PARCEL, 16, 12, PARCEL}, {R_CAT_HEAD, 7, 6, CAT_HEAD}, {R_POW, 7, 6, POW},
};

void rc_art_load(void) {
    static int loaded;
    if (loaded) return;
    for (int i = 0; i < ARRAY_LEN(ART); i++) {
        int len = (int)strlen(ART[i].px);
        if (len != ART[i].w * ART[i].h) {
            fprintf(stderr, "roofcat art %d: expected %d got %d\n", ART[i].id, ART[i].w * ART[i].h, len);
            char *tmp = (char *)calloc((size_t)ART[i].w * ART[i].h + 1, 1);
            memset(tmp, '.', (size_t)ART[i].w * ART[i].h);
            memcpy(tmp, ART[i].px, (size_t)imin(len, ART[i].w * ART[i].h));
            spr_make(&rc_spr[ART[i].id], ART[i].w, ART[i].h, tmp);
            free(tmp);
        } else {
            spr_make(&rc_spr[ART[i].id], ART[i].w, ART[i].h, ART[i].px);
        }
    }
    loaded = 1;
}
