/* ROOFCAT - pixel art (palette-letter strings, see gfx.h). All drawn for UFO 40. */
#include "roofcat.h"

Sprite rc_spr[R_SPRITE_COUNT];

static const char CAT_RUN1[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "k.......kozoozok"
    "ok......koooKook"
    ".rk....kkhhkhhk."
    ".okkkkkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kok.kk...kok.."
    ".kok...kok..kok."
    ".kk.....kk...kk."
    "................";
static const char CAT_RUN2[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    ".k......kozoozok"
    "kok.....koooKook"
    "..rk...kkhhkhhk."
    "..okkkkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "...kokkok.kok..."
    "...kk.kok.kk...."
    "......kk........"
    "................";
static const char CAT_RUN3[] =
    "................"
    "................"
    ".........k...k.."
    "........kok.kok."
    "k.......koookook"
    "ok......kozoozok"
    ".rk.....koooKook"
    ".okkkkkkkhhkhhk."
    "..korooroooooBk."
    "..kooroorooBBBk."
    "..koooooooooBuBk"
    "..khhhhhhhhhhBk."
    "...kok.kok.kk..."
    "...kok..kokk...."
    "....kk...kk....."
    "................";
static const char CAT_RUN4[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "........kozoozok"
    ".kk.....koooKook"
    "kork...kkhhkhhk."
    ".kokkkkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kokkok..kok..."
    ".kok..kk...kok.."
    ".kk.........kk.."
    "................";
static const char CAT_JUMP[] =
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "........kozoozok"
    "........koooKook"
    ".......kkhhkhhk."
    "kk...kkoooooook."
    "okkkkoorooooBBk."
    ".kkooroorooBuBk."
    "...koooooooooBk."
    "...khhhhhhhhhk.."
    "....kok..kokk..."
    "...kok....kok..."
    "...kk......kk..."
    "................"
    "................";
static const char CAT_SPIN[] =
    "................"
    "....kkkkkkk....."
    "..kkooorooookk.."
    ".kooroooooroook."
    ".koookkkkkooork."
    "kooookzozkoorook"
    "kororkoKokoooook"
    "koooookkkkkooork"
    "koroooooooooroBk"
    ".koooroooorooBk."
    ".kkooooooooookk."
    "..kkhhhhhhhhkk.."
    "....kkkkkkkk...."
    "................"
    "................"
    "................";
static const char CAT_FALL[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "........kozoozok"
    "........koooKook"
    "..k....kkhhkhhk."
    ".kok.kkoooooook."
    ".kokooroooooBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    ".kok.kk....kok.."
    "kok...kok...kok."
    "kk.....kk....kk."
    "................";
static const char CAT_THROW[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    "k.......kozoozok"
    "ok......koooKook"
    ".rk....kkhhkhhkk"
    ".okkkkkooooookhk"
    "..korooroooBBkk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kok.kk...kok.."
    ".kok...kok..kok."
    ".kk.....kk...kk."
    "................";
static const char CAT_SPIRIT1[] =
    "................"
    ".........I...I.."
    "........ICI.ICI."
    "........ICCCICCI"
    "........ICuCCuCI"
    "........ICCCwCCI"
    ".......IICCCCCI."
    "..IIIIICCCCCCCI."
    ".ICCCCCCCCCCCCI."
    ".ICCCCCCCCCCCI.."
    "..ICCCCCCCCCCI.."
    "...IICCCCCCII..."
    ".....ICCCCI....."
    "......ICCI......"
    ".......II......."
    "................";
static const char CAT_SPIRIT2[] =
    "................"
    ".........I...I.."
    "........ICI.ICI."
    "........ICCCICCI"
    "........ICuCCuCI"
    "........ICCCwCCI"
    ".......IICCCCCI."
    "...IIIICCCCCCCI."
    "..ICCCCCCCCCCCI."
    ".ICCCCCCCCCCCCI."
    ".ICCCCCCCCCCCI.."
    "..IICCCCCCCII..."
    "....ICCCCCI....."
    ".....ICCCI......"
    "......III......."
    "................";
static const char CAT_HURT[] =
    "................"
    "..k...k........."
    ".kok.kok........"
    "kookookoo......."
    "kokkookkok......"
    "koookKookk......"
    ".khhkkhhk......."
    ".kooooooookkk..."
    "kBBoooroooorok.."
    "kBuBooroorooook."
    ".kBooooooooooork"
    "..khhhhhhhhhhk.k"
    "..kok..kok..kok."
    "..kk...kk...kk.."
    "................"
    "................";
static const char CAT_IDLE[] =
    "................"
    ".........k...k.."
    "........kok.kok."
    "........koookook"
    ".k......kozoozok"
    "kok.....koooKook"
    "kok....kkhhkhhk."
    ".kok.kkoooooook."
    "..korooroooBBBk."
    "..kooroorooBuBk."
    "..koooooooooBk.."
    "..khhhhhhhhhhk.."
    "..kok.kok.kok..."
    "..kok.kok.kok..."
    "..kk..kk..kk...."
    "................";
static const char STAR1[] =
    "...ww..."
    "..wllw.."
    "wwwyywww"
    "wlyaaylw"
    "wlyaaylw"
    "wwwyywww"
    "..wllw.."
    "...ww...";
static const char STAR2[] =
    "w......w"
    "ww..w.ww"
    ".wwyyww."
    "..yaay.w"
    "w.yaay.."
    ".wwyyww."
    "ww.w..ww"
    "w......w";
static const char WISP_SHOT[] =
    "..II.."
    ".ICCI."
    "ICwwCI"
    "ICwwCI"
    ".ICCI."
    "..II..";
static const char PIGEON1[] =
    "................"
    "................"
    "........kkk....."
    ".......kgggk...."
    ".......kgkgak..."
    ".......kggggaa.."
    "..kkkkkkjjjk...."
    ".kgggggjzjgk...."
    "kgllgggggggk...."
    "kgllllgggggk...."
    ".kglllgggkk....."
    "..kkkggggk......"
    "....kkkkk......."
    ".....ok.ok......"
    "....oo..oo......"
    "................";
static const char PIGEON2[] =
    "................"
    "................"
    "................"
    "........kkk....."
    ".......kgggk...."
    ".......kgkgak..."
    "..kkkk.kggggaa.."
    ".kgggkkjjjjk...."
    "kgllgggjzjgk...."
    "kgllllgggggk...."
    ".kglllgggkk....."
    "..kkkggggk......"
    "....kkkkk......."
    "......ok.ok....."
    ".....oo..oo....."
    "................";
static const char GULL1[] =
    "kk..........kk.."
    "kwk........kwk.."
    ".kwk......kwk..."
    "..kwk....kwk...."
    "...kwwkkwwk....."
    "....kwwwwwkkk..."
    ".....kwwwwwwak.."
    "......kkwwwkk..."
    "........kk......"
    "................";
static const char GULL2[] =
    "................"
    "................"
    "................"
    "....kkkkkk......"
    "..kkwwwwwwkkk..."
    ".kwwlwwwwwwwak.."
    "kwwkkkwwwwkkk..."
    "kkk..kwwlk......"
    ".....kwlk......."
    "......kk........";
static const char MAGPIE1[] =
    "................"
    "......kkkk......"
    ".....kkkkkk....."
    ".....kkwkkkaa..."
    "..kk.kkkkkk....."
    ".kwwkkkkkkk....."
    "kwwwwkkkNNk....."
    "kkwwwwwkNNk....."
    ".kkkwwwwkkk....."
    "...kkkkkkk......"
    ".....kk.k......."
    "....kk..kk......"
    "................"
    "................"
    "................"
    "................";
static const char MAGPIE2[] =
    "..kk............"
    ".kwwk..kkkk....."
    ".kwwwkkkkkkk...."
    "..kwwkkkwkkkaa.."
    "...kwwkkkkkk...."
    "....kkkkkkkk...."
    "....kkkkkNNk...."
    "....kkwwwNNk...."
    ".....kkwwkkk...."
    "......kkkkk....."
    ".......kk.k....."
    "......kk..kk...."
    "................"
    "................"
    "................"
    "................";
static const char PEBBLE[] = ".kk.kglkksdkk.kk";
static const char SEED[] = ".kk.kaek.kk.";
static const char BUBBLE[] =
    ".kkkk."
    "kwIICk"
    "kICCCk"
    "kCCCuk"
    "kCCuuk"
    ".kkkk.";
static const char BOMB[] =
    "...y..."
    "..yak.."
    "...k..."
    ".kkkkk."
    "kdwddsk"
    "kdddddk"
    "kndddnk"
    ".kkkkk.";
static const char FISH[] =
    "..kkkk...."
    ".kCCCCkk.k"
    "kCwkCCCCkk"
    "kCCCCCCCuk"
    ".kuuuukk.k"
    "..kkkk....";
static const char DATE[] =
    "...kk..."
    "..kbbk.."
    ".kbttbk."
    ".kbtebk."
    ".kbttbk."
    ".kbbbbk."
    "..kkkk..";
static const char LETTER[] =
    "kkkkkkkkkk"
    "kcccccccck"
    "kkcccccckk"
    "kckccccckc"
    "kcckrrckck"
    "kcccrrccck"
    "kcccccccck"
    "kkkkkkkkkk";
static const char LANTERN_[] =
    "...kk..."
    "..kkkk.."
    ".kkkkkk."
    "krryyrrk"
    "kryccyrk"
    "krywcyrk"
    "kryccyrk"
    "krryyrrk"
    ".kkkkkk."
    "...kk..."
    "...ak..."
    "..a.a...";
static const char CATNIP[] =
    "...kk..."
    "..kzzk.."
    ".kzizzk."
    "kzzkzizk"
    ".kzzzzk."
    "..kjjk.."
    "...kk..."
    "........";
static const char HEART[] =
    ".kk.kk."
    "kKKkrrk"
    "kKrrrrk"
    ".krrrk."
    "..krk.."
    "...k...";
static const char CRAB1[] =
    "..kkk......................kkk.."
    ".krrrk....................krrrk."
    "krkk.rk..................kr.kkrk"
    "krk..rk..................kr..krk"
    ".krrrrk.......kk..kk.....krrrrk."
    "..krrk.......kwk..kwk.....krrk.."
    "...krk.......kkk..kkk.....krk..."
    "...krk.....kkkrrkkrrkkk...krk..."
    "....krk..kkrrrrrrrrrrrrkk.krk..."
    ".....krkkrrorrrrrrrrrorrrkrk...."
    "......krrrrrrrrrrrrrrrrrrrk....."
    ".....krrrorrrrrrrrrrrrrorrrk...."
    ".....krrrrrrrrvvvvvrrrrrrrrk...."
    "......krrrrrvvvvvvvvvrrrrrk....."
    ".......kkrrrrrrrrrrrrrrrkk......"
    ".....kk.kkkkkkkkkkkkkkkk.kk....."
    "....kk..k.k.k......k.k.k..kk...."
    "...k...k..k..k....k..k..k...k..."
    "................................"
    "................................";
static const char CRAB2[] =
    "................................"
    "................................"
    "..kkk......................kkk.."
    ".krrrk....................krrrk."
    "krkk.rk.......kk..kk.....kr.kkrk"
    "krk..rk......kwk..kwk....kr..krk"
    ".krrrrk......kkk..kkk....krrrrk."
    "..krrk.....kkkrrkkrrkkk...krrk.."
    "...krk...kkrrrrrrrrrrrrkk.krk..."
    "....krkkkrrorrrrrrrrrorrrkkrk..."
    "......krrrrrrrrrrrrrrrrrrrk....."
    ".....krrrorrrrrrrrrrrrrorrrk...."
    ".....krrrrrrrrvvvvvrrrrrrrrk...."
    "......krrrrrvvvvvvvvvrrrrrk....."
    ".......kkrrrrrrrrrrrrrrrkk......"
    "......kk.kkkkkkkkkkkkkkk.kk....."
    ".....k..k.k.k......k.k.k..k....."
    "....k..k..k..k....k..k..k..k...."
    "................................"
    "................................";
static const char PARCEL[] =
    "..kkkkkkkkkkkk.."
    ".kPPPPPkkPPPPPk."
    ".kPKKPkyykPKKPk."
    "kkkkkkkyykkkkkkk"
    "kttttttyyttttttk"
    "kteeeeeyyeeeeetk"
    "kteeeeeyyeeeeetk"
    "kyyyyyyyyyyyyyyk"
    "kteeeeeyyeeeeetk"
    "kteeeeeyyeeeeetk"
    "kttttttyyttttttk"
    "kkkkkkkkkkkkkkkk";
static const char CAT_HEAD[] =
    "k...k.."
    "kokok.."
    "kooook."
    "kozozk."
    "koKook."
    ".kkkk..";
static const char PIGEON_ROLL[] =
    "................"
    "................"
    "................"
    "................"
    "......kkkk......"
    "....kkggggkk...."
    "...kglllgggak..."
    "...kglllgkgak..."
    "..kgglllggggak.."
    "..kgggggggjjgk.."
    "..kggjjjjjjzgk.."
    "...kgggjzjggk..."
    "...kkgggggggk..."
    ".....kkkkkkk...."
    "................"
    "................";
static const char CROW1[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    ".....kkkk......."
    "....knnnnk......"
    "...knwknnnk....."
    ".aaknkknnnk....."
    "..akknnnnnkk...."
    "...knnnnnnnnk..."
    "...kndnnnnndnk.."
    "...knndnnndnnk.."
    "...kndnnnnndnk.."
    "...kkkkkkkkkkk.."
    "................";
static const char CROW2[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    ".....kkkk......."
    "....knnnnk......"
    "...knwknnnk....."
    "aaaknkknnnk....."
    ".a.kknnnnnkk...."
    "...knnnnnnnnk..."
    "...kndnnnnndnk.."
    "...knndnnndnnk.."
    "...kndnnnnndnk.."
    "...kkkkkkkkkkk.."
    "................";
static const char GECKO1[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "..kkk..........."
    ".kziwk....kk...."
    "kzzzzkkkkkzzk..."
    ".kkzzzzzzzzzzkkk"
    "..kzkzzjjjzkzzzk"
    "..kk.kk..kk.kkk."
    "................";
static const char GECKO2[] =
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "................"
    "..kkk..........."
    ".kziwk....kk...."
    "kzzzzkkkkkzzk..."
    ".kkzzzzzzzzzzkk."
    "...kzzzjjjzzkzzk"
    "...kk..kkk..kk.k"
    "................";
static const char LAMP[] =
    "....kkkk...."
    "...kaaaak..."
    "..kkkkkkkk.."
    "..kyyyyyyk.."
    ".kywcyyycyk."
    ".kyccyyccyk."
    ".kyyyyyyyyk."
    ".kyccyyccyk."
    ".kywcyyycyk."
    "..kyyyyyyk.."
    "..kkkkkkkk.."
    "...kaaaak..."
    "....kkkk...."
    "............";
static const char SPIKE[] =
    "...k..."
    "..kgk.."
    ".kglgk."
    "kglwlgk"
    ".kglgk."
    "..kgk.."
    "...k...";
static const char FFISH1[] =
    "....kkkk...."
    "..kkyyyykk.k"
    ".kywkyyyyykk"
    "kyyyyyyyyyak"
    ".kaaaaayykkk"
    "..kkkkkkk..k"
    "............"
    "............";
static const char FFISH2[] =
    "...k........"
    "..kyk.kk...."
    "..kkkyyyykkk"
    ".kywkyyyyyak"
    "kyyyyyyyyyak"
    ".kaaaaayykkk"
    "..kkkkkkk..."
    "....kyk.....";
static const char WASP1[] =
    ".ll..ll."
    "lwwlkwwl"
    ".lkkykl."
    ".kykykk."
    "kykykyk."
    ".kkykyk."
    "..kkkk.k"
    "........";
static const char WASP2[] =
    "........"
    ".ll..ll."
    "lwwlkwwl"
    ".kkykkk."
    "kykykyk."
    ".kkykyk."
    "..kkkk.k"
    "........";
static const char SNAIL1[] =
    "................"
    "........kkkk...."
    ".......krrrrk..."
    "......krowrork.."
    "......kroorrrk.."
    ".k.k..krrorork.."
    "kwkwk.krroorrk.."
    "khhhkkkrrrrrk..."
    "khhhhhhkkkkkhk.."
    ".khhhhhhhhhhhhk."
    "..kkkkkkkkkkkk.."
    "................";
static const char SNAIL2[] =
    "................"
    "........kkkk...."
    ".......krrrrk..."
    "......krowrork.."
    ".k.k..kroorrrk.."
    "kwkwk.krrorork.."
    "khhhk.krroorrk.."
    "khhhkkkrrrrrk..."
    "khhhhhhkkkkkhk.."
    ".khhhhhhhhhhhhk."
    "..kkkkkkkkkkkk.."
    "................";
static const char TOAD1[] =
    "................"
    "....kk....kk...."
    "...kwkk..kkwk..."
    "..kzkzzkkzzkzk.."
    ".kzzzzzzzzzzzzk."
    "kjzzzzzzzzzzzzjk"
    "kjjzzzzzzzzzzjjk"
    "kjjzcccccccczjjk"
    ".kjjcccccccjjjk."
    "..kkjjjjjjjjkk.."
    ".kzzk......kzzk."
    "kkkk........kkkk";
static const char TOAD2[] =
    "....kk....kk...."
    "...kwkk..kkwk..."
    "..kzkzzkkzzkzk.."
    ".kzzzzzzzzzzzzk."
    "kjzzzzzzzzzzzzjk"
    "kjjzzzzzzzzzzjjk"
    "kjjzcccccccczjjk"
    ".kjjcccccccjjjk."
    "..kkjjjjjjjjkk.."
    "..kzk......kzk.."
    "..kzk......kzk.."
    ".kkk........kkk.";
static const char PELICAN1[] =
    "..........kk...."
    "...kkk...kllk..."
    "..kwwwk.kllk...."
    "aaaakwk.kkkkkkk."
    "kaaaaakkkwwwwwwk"
    ".kkkaakwwwwwwlwk"
    "....kkwwwwwwllk."
    ".....kkwwwllkk.."
    ".......kkkkk...."
    "................"
    "................"
    "................";
static const char PELICAN2[] =
    "................"
    "...kkk.........."
    "..kwwwk........."
    "aaaakwk..kkkkkk."
    "kaaaaakkkwwwwwwk"
    ".kkkaakwwwwwwlwk"
    "....kkwwwwwwllk."
    ".....kkwwlllkk.."
    "......klllk....."
    ".......kllk....."
    "........kk......"
    "................";
static const char JAR1[] =
    "...kkkkkk..."
    "..keeeeeek.."
    "...kttttk..."
    "..kteeeetk.."
    ".kteewweetk."
    ".ktekweketk."
    ".kteeeeeetk."
    ".ktbbbbbbtk."
    ".kteeeeeetk."
    "..kteeeetk.."
    "...kkkkkk..."
    "............";
static const char JAR2[] =
    "..keeeeeek.."
    "...kttttk..."
    "..kteeeetk.."
    ".kteewweetk."
    ".ktekweketk."
    ".kteeeeeetk."
    ".ktbbbbbbtk."
    ".kteeeeeetk."
    "..kteeeetk.."
    "...kkkkkk..."
    "...k....k..."
    "..kk....kk..";
static const char CRACKER1[] =
    "......k....."
    ".....kak...."
    "......k....."
    "..kkkkkkkk.."
    ".krrkrrkrrk."
    ".krwkrwkrwk."
    ".krrkrrkrrk."
    ".kyykyykyyk."
    ".krrkrrkrrk."
    ".krrkrrkrrk."
    ".kyykyykyyk."
    ".krrkrrkrrk."
    "..kkkkkkkk.."
    "............";
static const char CRACKER2[] =
    ".....y.y...."
    "......a....."
    "......k....."
    "..kkkkkkkk.."
    ".korkorkork."
    ".kowkowkowk."
    ".korkorkork."
    ".kyykyykyyk."
    ".korkorkork."
    ".korkorkork."
    ".kyykyykyyk."
    ".korkorkork."
    "..kkkkkkkk.."
    "............";
static const char PUFFER1[] =
    "...k..k..k.."
    "..kkkkkkkk.."
    ".kllllllllk."
    "kllwkllllllk"
    "kllkkllllllk"
    "kaallllllllk"
    "kllccccccllk"
    ".kllccccllk."
    "..kkllllkk.."
    "...k.kk.k..."
    "............"
    "............";
static const char PUFFER2[] =
    ".k.k..k..k.k"
    "..kkkkkkkk.."
    "kkllllllllkk"
    "kllwkllllllk"
    "kllkkllllllk"
    "kaallllllllk"
    "kllccccccllk"
    "kkllccccllkk"
    "..kkllllkk.."
    ".k.k.kk.k.k."
    "............"
    "............";
static const char SPIDER1[] =
    "k...kk...k"
    ".k.kddk.k."
    "..kddddk.."
    "kkkdwwdkkk"
    "..kddddk.."
    ".k.kddk.k."
    "k...kk...k"
    "..........";
static const char SPIDER2[] =
    ".k..kk..k."
    "k..kddk..k"
    ".kkddddkk."
    "..kdwwdk.."
    ".kkddddkk."
    "k..kddk..k"
    ".k..kk..k."
    "..........";
static const char FLASHER1[] =
    "................"
    "......kkkk......"
    ".....knnnnk....."
    "....knwknnnk...."
    "..aaknkknnnk...."
    "...akknnnnnkk..."
    "..kIIk.nnnnnnk.."
    ".kICCIknwwnnnk.."
    ".kCIICknwwwnnk.."
    ".kICCIknnwwnnk.."
    "..kIIk.knnnnk..."
    "...k....knnk...."
    "........k..k...."
    ".......kk..kk..."
    "................"
    "................";
static const char FLASHER2[] =
    "................"
    "......kkkk......"
    ".....knnnnk....."
    "....knwknnnk...."
    "..aaknkknnnk...."
    "...akknnnnnkk..."
    "..kwwk.nnnnnnk.."
    ".kwwwwknwwnnnk.."
    ".kwwwwknwwwnnk.."
    ".kwwwwknnwwnnk.."
    "..kwwk.knnnnk..."
    "...k....knnk...."
    "........k..k...."
    ".......kk..kk..."
    "................"
    "................";
static const char SHEET1[] =
    "................"
    "....kkkkkkkk...."
    "...kwwwwwwwwk..."
    "..kwwkwwwkwwwk.."
    "..kwwkwwwkwwwk.."
    "..kwwwwwwwwwwk.."
    "..kuuuuuuuuuuk.."
    "..kwwwwwwwwwwk.."
    "..kwwwwwwwwwwk.."
    "..kuuuuuuuuuuk.."
    "..kwwwwwwwwwwk.."
    "..kwwwwwwwwwwk.."
    "..kwkwwkwwkwwk.."
    "..kk.kkk.kk.kk.."
    "................"
    "................";
static const char SHEET2[] =
    "................"
    "................"
    ".....kkkkkkkk..."
    "...kkwwwwwwwwk.."
    "..kwwkwwwkwwwwk."
    ".kwwwkwwwkwwwwk."
    ".kwwwwwwwwwwwk.."
    ".kuuuuuuuuuuuk.."
    "..kwwwwwwwwwwk.."
    "..kwwwwwwwwwwwk."
    "..kuuuuuuuuuuuk."
    "...kwwwwwwwwwk.."
    "...kwkwwkwwkwk.."
    "...kk.kk.kk.kk.."
    "................"
    "................";
static const char MOTH1[] =
    "............"
    ".kk......kk."
    "kgglk..klggk"
    "kglllkklllgk"
    ".kgllkkllgk."
    "..kgkddkgk.."
    "...kddddk..."
    "....kddk...."
    ".....kk....."
    "............";
static const char MOTH2[] =
    "...kk..kk..."
    "..kglk.klgk."
    "..kgllkllgk."
    "...kglklgk.."
    "....kddk...."
    "....kddk...."
    "...kddddk..."
    "....kddk...."
    ".....kk....."
    "............";
static const char ORB[] =
    "..kkkk.."
    ".kPPPPk."
    "kPKwPPPk"
    "kPwPPPVk"
    "kPPPPPVk"
    "kPPPPVVk"
    ".kVVVVk."
    "..kkkk..";
static const char FIG[] =
    "...zk..."
    "...kk..."
    "..kVVk.."
    ".kVPVVk."
    "kVPVVVpk"
    "kVVVVVpk"
    ".kppppk."
    "..kkkk..";
static const char TEA[] =
    "..z.z..."
    "...zz..."
    ".kkkkkk."
    ".kIaaIk."
    ".kaaaak."
    ".kaaaak."
    "..kaak.."
    ".kkkkkk.";
static const char CROWN_[] =
    "k...k...k"
    "kk.kyk.kk"
    "kykyyykyk"
    "kyyyyyyyk"
    "kyryyyryk"
    "kyyyyyyyk"
    "kkkkkkkkk";
static const char CLAW[] =
    "......kkkkk........."
    "....kkrrrrrk........"
    "...krrrorrrrk......."
    "..krrorrrrrrk......."
    "..krrrrrkkkkk......."
    "..krrrrk............"
    "..krrrrrkk.........."
    "..krrorrrrkkk......."
    "...krrrrrrrrrk......"
    "....kkrrrrrrrrkk...."
    "......kkkrrrrrrrkkkk"
    "........kkrrrrrrrrrk"
    "..........kkkkkkkkkk"
    "....................";

typedef struct { int id, w, h; const char *px; } Art;
static const Art ART[] = {
    {R_CAT_RUN1, 16, 16, CAT_RUN1}, {R_CAT_RUN2, 16, 16, CAT_RUN2}, {R_CAT_RUN3, 16, 16, CAT_RUN3},
    {R_CAT_RUN4, 16, 16, CAT_RUN4}, {R_CAT_JUMP, 16, 16, CAT_JUMP}, {R_CAT_SPIN, 16, 16, CAT_SPIN},
    {R_CAT_FALL, 16, 16, CAT_FALL}, {R_CAT_THROW, 16, 16, CAT_THROW}, {R_CAT_SPIRIT1, 16, 16, CAT_SPIRIT1},
    {R_CAT_SPIRIT2, 16, 16, CAT_SPIRIT2}, {R_CAT_HURT, 16, 16, CAT_HURT}, {R_CAT_IDLE, 16, 16, CAT_IDLE},
    {R_STAR1, 8, 8, STAR1}, {R_STAR2, 8, 8, STAR2}, {R_WISP_SHOT, 6, 6, WISP_SHOT},
    {R_PIGEON1, 16, 16, PIGEON1}, {R_PIGEON2, 16, 16, PIGEON2}, {R_PIGEON_ROLL, 16, 16, PIGEON_ROLL},
    {R_GULL1, 16, 10, GULL1}, {R_GULL2, 16, 10, GULL2}, {R_CROW1, 16, 16, CROW1}, {R_CROW2, 16, 16, CROW2},
    {R_GECKO1, 16, 16, GECKO1}, {R_GECKO2, 16, 16, GECKO2}, {R_LAMP, 12, 14, LAMP}, {R_SPIKE, 7, 7, SPIKE},
    {R_FFISH1, 12, 8, FFISH1}, {R_FFISH2, 12, 8, FFISH2}, {R_WASP1, 8, 8, WASP1}, {R_WASP2, 8, 8, WASP2},
    {R_SNAIL1, 16, 12, SNAIL1}, {R_SNAIL2, 16, 12, SNAIL2}, {R_TOAD1, 16, 12, TOAD1}, {R_TOAD2, 16, 12, TOAD2},
    {R_PELICAN1, 16, 12, PELICAN1}, {R_PELICAN2, 16, 12, PELICAN2}, {R_JAR1, 12, 12, JAR1}, {R_JAR2, 12, 12, JAR2},
    {R_CRACKER1, 12, 14, CRACKER1}, {R_CRACKER2, 12, 14, CRACKER2}, {R_PUFFER1, 12, 12, PUFFER1},
    {R_PUFFER2, 12, 12, PUFFER2}, {R_SPIDER1, 10, 8, SPIDER1}, {R_SPIDER2, 10, 8, SPIDER2},
    {R_MAGPIE1, 16, 16, MAGPIE1}, {R_MAGPIE2, 16, 16, MAGPIE2}, {R_FLASHER1, 16, 16, FLASHER1},
    {R_FLASHER2, 16, 16, FLASHER2}, {R_SHEET1, 16, 16, SHEET1}, {R_SHEET2, 16, 16, SHEET2},
    {R_MOTH1, 12, 10, MOTH1}, {R_MOTH2, 12, 10, MOTH2},
    {R_PEBBLE, 4, 4, PEBBLE}, {R_SEED, 4, 3, SEED}, {R_BUBBLE, 6, 6, BUBBLE}, {R_BOMB, 7, 8, BOMB}, {R_ORB, 8, 8, ORB},
    {R_FISH, 10, 6, FISH}, {R_DATE, 8, 7, DATE}, {R_FIG, 8, 8, FIG}, {R_TEA, 8, 8, TEA}, {R_CROWN, 9, 7, CROWN_},
    {R_LETTER, 10, 8, LETTER}, {R_LANTERN, 8, 12, LANTERN_}, {R_CATNIP, 8, 8, CATNIP}, {R_HEART, 7, 6, HEART},
    {R_CRAB1, 32, 20, CRAB1}, {R_CRAB2, 32, 20, CRAB2}, {R_CLAW, 20, 14, CLAW},
    {R_PARCEL, 16, 12, PARCEL}, {R_CAT_HEAD, 7, 6, CAT_HEAD},
};

void rc_art_load(void) {
    static int loaded;
    if (loaded) return;
    for (int i = 0; i < ARRAY_LEN(ART); i++) {
        int len = (int)strlen(ART[i].px);
        if (len != ART[i].w * ART[i].h) {
            fprintf(stderr, "roofcat art %d: expected %d got %d\n", ART[i].id, ART[i].w * ART[i].h, len);
            char *tmp = (char *)calloc((size_t)ART[i].w * ART[i].h + 1, 1);
            memset(tmp, '.', (size_t)ART[i].w * ART[i].h);
            memcpy(tmp, ART[i].px, (size_t)imin(len, ART[i].w * ART[i].h));
            spr_make(&rc_spr[ART[i].id], ART[i].w, ART[i].h, tmp);
            free(tmp);
        } else {
            spr_make(&rc_spr[ART[i].id], ART[i].w, ART[i].h, ART[i].px);
        }
    }
    loaded = 1;
}
